### ISSUE TITLE
Update to JUnit 5

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#100]

**Comment by phillip-kruger** [comment]
@t1 any progress on getting this onto smallrye-parent ?

**Comment by t1** [comment]
I'm busy writing the article, so this will have to wait for another week or so. But it's not forgotten :-)

**Comment by phillip-kruger** [comment]
Cool thanks !

**Comment by phillip-kruger** [comment]
@t1 - parent is now updated to include JUnit 5. We can start to migrate all tests over to 5
