### ISSUE TITLE
Handling `"null"` `path` on error

### ISSUE THREAD

**Issue by christianThor** [smallrye/smallrye-graphql#1065]
I am using `smallrye-graphql-client-1.3.2`. I have a simple Query. When it errors out due to a validation error on the graphql server, I get the following exception:

```
java.lang.ClassCastException: class javax.json.JsonValueImpl cannot be cast to class javax.json.JsonArray (javax.json.JsonValueImpl and javax.json.JsonArray are in unnamed module of loader 'app')
```

It looks like this happens when the code in `ResultBuilder.java` expects that the `path` property on the JSON object is an array, but in reality it is `"null"`. 

Here is a screenshot that might be helpful..
<img width="983" alt="Screen Shot 2021-09-24 at 6 51 26 PM" src="https://user-images.githubusercontent.com/25309109/134753939-f68b404a-a501-412b-82ea-acc362b945bb.png">

Let me know if you need more info, thank you!

**Comment by jmartisk** [comment]
Hi, thanks for reporting. This indeed looks like a bug and we should expect a `null` path. I'll prepare a fix
