### ISSUE TITLE
Enum vulnerable to injection attack

### ISSUE THREAD

**Issue by cherrydev** [smallrye/smallrye-graphql#1140]
Other value types get formatted and/or quoted by `ValueFormatter` but Enum get placed into the document raw when created using the builder DSL. While there is no indication anywhere that this code should be responsible for quoting or formatting an enum, all of the other types seem to do this. I would expect, at the very least, that any programmatic DSL like this would produce a well-formed document when used, and as far as I can see, Enum is the only Buildable type that makes no attempt to enforce this.

For example:
```
ValueFormatter.format(Enum.gqlEnum("foo {"))
```
will produce the enum value `foo {` which will cause, at best, a malformed document. I believe it is necessary to either have `ValueFormatter.format()` or `Enum.gqlEnum()` reject invalid enum values, or clearly document that any values passed to `Enum.gqlEnum()` must be thoroughly input checked to conform with valid GraphQL enum values.

**Comment by cherrydev** [comment]
By the way, enums are defined as conforming to a GraphQL [_Name_](http://spec.graphql.org/June2018/#Name) but [not *true*, *false* or *null*](http://spec.graphql.org/June2018/#sec-Enum-Value)

**Comment by jmartisk** [comment]
this was resolved via https://github.com/smallrye/smallrye-graphql/pull/1141
