### ISSUE TITLE
ResponseReader locations parsing error

### ISSUE THREAD

**Issue by cherrydev** [smallrye/smallrye-graphql#1153]
When parsing errors out of a response, each `location` is assumed to be a map containing only integer values. The spec states that a location must contain `line` and `column` keys with integer values, but it does not specifically forbid other entries from being in that map. Some server implementations (AWS AppSync) include a `sourceName` value which can contain a string, or (often) null. Since the implementation currently iterates through each map key and coerces the value to a `JsonNumber`, this results in ClassCastExceptions. This could be avoided by simply reading the two specific `line` and `column` map keys instead of iterating. I'll make a PR.

**Comment by cherrydev** [comment]
Never mind, I see there's already a newer version that fixes this similarly.

**Comment by jmartisk** [comment]
Hi @cherrydev, note that we also have an issue https://github.com/smallrye/smallrye-graphql/issues/1136 where we might introduce a different abstraction for representing the locations. But it's only an idea right now, so should you have any comments on it, feel free to add them to that issue.
