### ISSUE TITLE
@ErrorCode not working with Quarkus 2.4.2

### ISSUE THREAD

**Issue by mklueh** [smallrye/smallrye-graphql#1173]
Hi,

I'm not sure what is wrong, but I'm throwing this custom exception annotated with `@ErrorCode`

```
@ErrorCode("user not registered")
public class UserNotRegisteredException extends RuntimeException {
    public UserNotRegisteredException(String s) {
        super(s);
    }
}
```

All I'm getting is this:

```
{
  "errors": [
    {
      "message": "System error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "myPath"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "myResult": null
  }
}
```

By the way, why is this annotation even required and why can't GraphQL just populate whatever exception is thrown by default?

**Comment by phillip-kruger** [comment]
Runtime errors are "hidden" by default. You can change that with config. See https://download.eclipse.org/microprofile/microprofile-graphql-1.0/microprofile-graphql.html#_unchecked_exceptions

For Quarkus you can use `quarkus.smallrye-graphql.show-runtime-exception-message` - See https://quarkus.io/guides/smallrye-graphql#quarkus-smallrye-graphql_quarkus.smallrye-graphql.show-runtime-exception-message

You might also want to configure the fields that should show: see https://quarkus.io/guides/smallrye-graphql#quarkus-smallrye-graphql_quarkus.smallrye-graphql.error-extension-fields

You might be able to omit the `@ErrorCode` annotation , as the default might be fine for you.

Please let us know if this solves your issue.

**Comment by mklueh** [comment]
@phillip-kruger 

Many thanks, I applied your recommendations and I'm getting the correct error message, but with the same classification:

```
{
  "errors": [
    {
      "message": "User not registered",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "myPath"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "myResult": null
  }
}
```

Not sure if I'm still missing something, but I somehow need a classification other than DataFetchingException to tell the frontend what to do.

The config property description as well is only related to the message, not the exception type:

```
quarkus.smallrye-graphql.show-runtime-exception-message

List of Runtime Exceptions class names that should show the error message. By default Runtime Exception messages will be hidden and a generic Server Error message will be returned.
```

I'm currently extending my custom exception from "Exception.class" and not "RuntimeException.class" anymore.

**Comment by phillip-kruger** [comment]
I think the idea of error code it for the front end to know what to do. So make sure `code` is in `quarkus.smallrye-graphql.error-extension-fields` and use that. You can then customize the code with `@ErrorCode`

**Comment by mklueh** [comment]
Thanks @phillip-kruger .

I've added code and exception now and I can work with that perfectly. I was a bit mislead by the "classification" exception.

is it common to use HttpStatusCodes as error codes like'

```
@ErrorCode("" + HttpStatus.SC_UNAUTHORIZED)
public class UserNotRegisteredException extends Exception {
    public UserNotRegisteredException(String s) {
        super(s);
    }
}

```

or do people usually use some telling message there?

**Comment by phillip-kruger** [comment]
Hi @mklueh - Honestly I do not know, I guess whatever works for you. I personally would not use it, but rather use my own code/enum. GraphQL is not tied to HTTP, and could later be exposed over another transport. But I do not think that is wrong, it's just my own preference. If it's ok I am closing here. Please reopen if needed :)

**Comment by t1** [comment]
@mklueh: just my to cent: we always use textual codes. I've repeatedly seen people using http status codes in the wrong context. Esp. `409 Conflict` is often used to indicate that the provided data was not consistent, while the status code is exclusively reserved for optimistic lock failures. So I'm very careful with http status codes, as they have a very technical background, while these types of errors often are much more business exceptions.
