### ISSUE TITLE
Support WebSockets and Subscriptions on the client side

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#1220]
In addition to the vert.x http client, we could support endpoint URLs with `ws://...`

**Comment by jmartisk** [comment]
I'm not sure I understand what this is about - we already have support for websocket-based subscriptions through the Vert.x HTTP client, is this about supporting the same through something else than Vert.x?

**Comment by t1** [comment]
Oh, I didn't get that! Sorry.
