### ISSUE TITLE
How cancel subscription 

### ISSUE THREAD

**Issue by rullyalves** [smallrye/smallrye-graphql#1268]
Initially I would like to thank you for this repository, it has been very useful to me. While developing, a little question about subscriptions came up, I know that to receive a subscription, just send a similar json with: 

{"query":"your subscription", "variables"}

 I would like to know how I can cancel a specific subscription, what payload should I send to get this, or if it doesn't work that way, a suggested way to do this.

**Comment by jmartisk** [comment]
Hi, currently the server side library supports only a basic protocol that doesn't have any specific operation to cancel a subscription. The way to cancel a subscription currently is to simply close the websocket connection - the server will stop emitting events.
In the near future, we will implement some smarter protocols, like `graphql-transport-ws`, specified here https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md . As of SmallRye GraphQL 1.4.2, this is already supported in the client-side library (in case you want to use the client library to connect to a different GraphQL engine such as Hasura), but it's not supported by the server-side library yet.

**Comment by rullyalves** [comment]
thanks for the reply, could I help by opening a PR to add this functionality? Could you tell me how subscriptions are currently stored? another question I have, can I currently do more than one subscription on the same websocket connection? or would each subscription be a different websocket connection?

**Comment by jmartisk** [comment]
I suppose it would be possible to add a way to cancel a subscription with the current protocol, but frankly I don't see much value in it - we will switch to the `graphql-transport-ws` protocol soon anyway, and that will enable that. 
The current protocol also does not offer multiplexing of more subscriptions over one websocket connection, so in that case simply closing the connection should be a sufficient way to tell the server to stop the subscription in my opinion. If one connection equals one subscription (for now), we don't need any special protocol capability for cancelling.

The `graphql-transport-ws` protocol will soon solve both of these features (cancelling and multiple subscriptions). I'm just waiting for @phillip-kruger to come back from his leave to sort out some details before implementing it.

**Comment by jmartisk** [comment]
We now have the server understand the `graphql-transport-ws` and `graphql-ws` protocols which have support for cancelling. And the client library supports that too; when you cancel a Multi corresponding to a subscription, then it sends a cancel operation to the server.
