### ISSUE TITLE
RESTEASY003145: Unable to find a MessageBodyReader of content-type */*

### ISSUE THREAD

**Issue by emeraldhieu** [smallrye/smallrye-graphql#1297]
Hi guys,

I have a Eureka client works successfully as a normal JAX-RS endpoint but when called with `@GraphQLApi`, it shows the below error. Anyone got any idea?

Configuration
```
@ApplicationScoped
public class ClientConfiguration {
    @Inject
    @LoadBalanced(type = LoadBalancerType.RANDOM)
    EurekaClient eurekaClient;

    @Produces
    FooClient fooClient() {
        return ServiceClientBuilder.newBuilder(eurekaClient, "foo")
            .build(FooClient.class);
    }
```

GraphQL
```
@GraphQLApi
@RequiredArgsConstructor
public class FooResource {

    private final FooClient fooClient;

    @Query("getBar")
    @Description("Get a bar")
    public Bar getBar() {
        Foo foo = fooClient.getFoo(); // <<<< ERROR HERE
        return Bar.builder().build();
    }
}
```

Error
```
2022-03-03 18:08:34,123 ERROR [io.sma.graphql] (vert.x-worker-thread-0) SRGQL012000: Data Fetching Error: javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type */* and type class io.quarkus.eureka.client.ServiceResponseException
	at org.jboss.resteasy.core.interception.jaxrs.ClientReaderInterceptorContext.throwReaderNotFound(ClientReaderInterceptorContext.java:47)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:133)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:75)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:217)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:90)
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:262)
	at io.quarkus.eureka.client.ServiceResponseExceptionMapper.toThrowable(ServiceResponseExceptionMapper.java:11)
	at io.quarkus.eureka.client.ServiceResponseExceptionMapper.toThrowable(ServiceResponseExceptionMapper.java:8)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:153)
```

**Comment by phillip-kruger** [comment]
Any reason you are using jax-rs here ? No need for that. If you use the smallrye graphql client that should work

**Comment by phillip-kruger** [comment]
If you want to use this client, then you need to set the headers to content type and accept, and probably add a json message body writer

**Comment by emeraldhieu** [comment]
> Any reason you are using jax-rs here ? No need for that. If you use the smallrye graphql client that should work

I mean this works.

```
@Path("/v1")
@RequiredArgsConstructor
@ApplicationScoped
public class TestResource {

    private final FooClient fooClient;

    @GET
    @Path("/test")
    public Foo get() {
        Foo foo = fooClient.getFoo();
        return foo;
    }
}
```

But with `@GraphQLApi`, it doesn't work.

**Comment by phillip-kruger** [comment]
Graphql is not jax-rs. Like I said, you going to have to set some headers in the client for this to work. Are you doing a post ? Or a get ?

**Comment by phillip-kruger** [comment]
Ok wait, I see now the issue, you are making a client call from the server ? That should work , you might miss some libs. Can you create a reproducer that I can look at ?

**Comment by emeraldhieu** [comment]
> Ok wait, I see now the issue, you are making a client call from the server ? That should work , you might miss some libs. Can you create a reproducer that I can look at ?

I'm doing a POST for GraphQL. Hm... I'm not sure how to create a repdoducer because it requires JHipsterRegistry as a Eureka server.

**Comment by phillip-kruger** [comment]
I would try to add some message body writer extensions, like the jsonb or Jackson, from rest easy or resteasy client and see if that works, you probably already have them in the jax-rs example, that is why it's working

**Comment by phillip-kruger** [comment]
Like this one io.quarkus:quarkus-rest-client-jackson

Let me know if that works

**Comment by emeraldhieu** [comment]
Adding the dependency doesn't work. I've debugged the app using Proxyman and found that the Eureka client request (#getFoo) failed with 401 Unauthorized because it doesn't have header "Authorization" passed from GraphQL request.

It seems that the Eureka client interface running in JAX-RS context doesn't have HTTP headers and have to be propagated like mentioned at https://github.com/eclipse/microprofile-rest-client/blob/f66e802cecc3cca973ebaa079ea3cc02c845c172/spec/src/main/asciidoc/integration.asciidoc#jax-rs

This is my fix.

```
@RequestScoped
public class GraphQLHeaderFactory implements ClientHeadersFactory {

    @Inject
    CurrentVertxRequest request;

    @Override
    public MultivaluedMap<String, String> update(MultivaluedMap<String, String> incomingHeaders,
                                                 MultivaluedMap<String, String> clientOutgoingHeaders) {
        MultivaluedMap<String, String> propagatingHeaders = new MultivaluedHashMap<>();
        List<String> headersToPut = List.of("Authorization");
        request.getCurrent().request().headers().entries().stream()
            .filter(entry -> headersToPut.stream()
                .anyMatch(headerToPut -> headerToPut.equalsIgnoreCase(entry.getKey())))
            .forEach(entry -> propagatingHeaders.put(entry.getKey(), List.of(entry.getValue())));
        return propagatingHeaders;
    }
}

@RegisterRestClient
@RegisterClientHeaders(GraphQLHeaderFactory.class)
public interface FooClient {
   ...
}
```
