### ISSUE TITLE
How to create dynamic schema?

### ISSUE THREAD

**Issue by magick93** [smallrye/smallrye-graphql#1299]
Hi

I'm trying to dynamically create a Graphql schema (at runtime).

The background is, I'm using https://github.com/yavin-dev/gsheet-jdbc to connect to a google spreadsheet. This is using H2 and creating a table per sheet at runtime. 

As such, there is no concrete class representing these tables. 

I'm trying to use smallrye-graphql to create a graphql server to expose these tables. However, the primary use case for small-rye is when there is an orm - and classes and schema are known.

Can you advise how I might use smallrye-graphql dynamically? 

Thanks and kind regards

**Comment by phillip-kruger** [comment]
You can use graphql-java directly in that case

**Comment by phillip-kruger** [comment]
Closing. No feedback

**Comment by magick93** [comment]
Apologies for the no feedback. I felt like a bit of dick for thinking there was a problem when there wasnt. I really appreciate your responsiveness and support.
