### ISSUE TITLE
Nested Records as input do not work if not all parameters are present, and it is in a list

### ISSUE THREAD

**Issue by robp94** [smallrye/smallrye-graphql#1316]
If the nested input is inside a list, it does not work.

Same reproducer as in the old issue, just change Parent to:

```
public record Parent(String s,
                     List<TestRecord> testRecord) {
    @JsonbCreator
    public Parent {
    }
}
```

server/implementation/src/main/java/io/smallrye/graphql/execution/datafetcher/helper/ArgumentHelper.java

```
                if (m.get(s) instanceof Map) {
                    m.put(s, includeNullCreatorParameters((Map) m.get(s), f));
                }
```

`m.get(s)` is a List and in there is the map.

https://github.com/smallrye/smallrye-graphql/issues/1152

**Comment by jmartisk** [comment]
Hey thanks for reporting, I'll have a look into it later this week, hopefully (but if you want to prepare a PR yourself you're welcome to do so, it's not a complicated fix)
