### ISSUE TITLE
Transform bean validation constraints into directives in the schema

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#1329]
We will need to decide whether there will be just one directive type (like `@constraint`), or a different directive per constraint type. But a single `@constraint` directive containing a textual description would probably be enough.
For built-in constraints, coming up with a description is relatively easy. Problem is with custom constraints, where we would probably be able to add only a very generic description, like the annotation name and parameter values.

**Comment by t1** [comment]
If we had this, probably #977 would become obsolete.

@jmartisk: how do other GraphQL server stacks convey field constraints beyond non-null? And just as a thought: if constraints where machine readable, a frontend could use that metadata to directly validate user input.

**Comment by jmartisk** [comment]
There's a javascript library with something like that and it looks like it has a relatively large user base: https://github.com/confuser/graphql-constraint-directive it uses a single `@constraint` directive
For most built-in constraints from Bean Validation, we could probably just follow the same format. For custom constraints we would emit something like `@constraint(annotation: "org.acme.MyCustomValidation(param=43)")`?

Not sure if we want to follow also their strategy for returning validation errors (https://github.com/confuser/graphql-constraint-directive#constraintdirectiveerror), ours is slightly different

**Comment by t1** [comment]
Yeah, that sounds like a good match to bean validation. I'd really like to see things like `@constraint(minLength: 5)` in my schemas!

I'm not so sure about the `annotation` field. For my taste, your suggestion reveals too much implementation detail: it's an annotation and this is the class name, etc. But I currently don't really have a better idea. Maybe we can postpone that for a moment until we have some real use-case to think about?

I don't quite get the `ConstraintDirectiveError`: are these the entries in the `errors` field or is it a Union? It all looks strange to me, but probably only my JavaScript skills are to meager ;-)

BTW: The API-Guru project they link to, is dead, obviously.

**Comment by jmartisk** [comment]
Yeah I'd say do it only for built-in constraints for now, custom ones are hard to capture.
And let's not change the error handling either, that would be a breaking change and needs very thorough thinking..

**Comment by jmartisk** [comment]
I'll try experimenting and maybe come up with an impl
