### ISSUE TITLE
Work with stork

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#1338]
Make sure stork works with graphql client. @jmartisk w.d.y.t ?

**Comment by t1** [comment]
I didn't know what stork is. I found this: http://smallrye.io/smallrye-stork

"SmallRye Stork is a service discovery and client-side load-balancing framework."

**Comment by phillip-kruger** [comment]
Yea, so it works nice for rest client, not sure what the effort is to get it to work for graphql client

**Comment by t1** [comment]
I just briefly looked at the Concepts page, but how does it work with the MP REST Client? My first guess is that you can use a logical service name in the URI?

**Comment by phillip-kruger** [comment]
https://www.youtube.com/watch?v=l3mLKU3wR2A

**Comment by t1** [comment]
Okay, so you'd use a URI `stork://my-service`. Sounds cool!

**Comment by phillip-kruger** [comment]
You want to work on implementing it ? Might need some work in stork repo

**Comment by t1** [comment]
I'm unsure, because we won't be able to use Stork in our project ATM: we need load balancers for external calls anyway and we use Config Sources for the lookup part. Federation is more important and I simply need to focus (which is not easy for me ;-).

Just a thought: I would not really like to use the `stork` URI scheme directly in my `GraphQlClientApi` annotation, as that's somewhat a too technical a detail. So I'd slightly prefer to configure it externally.

**Comment by t1** [comment]
BTW: Stork may be just perfect for Feder ;-)

**Comment by jmartisk** [comment]
This is something we certainly want to do. My understanding is that on the GraphQL client side we will need to add support for the `stork` URI scheme which, if it's configured for a client, means that the client will, for each request separately, retrieve the actual target URI (using some sort of Stork API) that it should send the request to. For simple HTTP requests this is clear, not completely sure about websocket traffic, but probably it should be that before establishing a websocket, retrieve the target URI from Stork, but after establishing it, keep using that, don't load-balance anymore. 
Maybe @michalszynkiewicz can confirm or correct me.

**Comment by jmartisk** [comment]
In any case let me assign it to myself, unless someone really wants to do it :)

**Comment by phillip-kruger** [comment]
I was hoping you will do it ;)

**Comment by michalszynkiewicz** [comment]
> This is something we certainly want to do. My understanding is that on the GraphQL client side we will need to add support for the `stork` URI scheme which, if it's configured for a client, means that the client will, for each request separately, retrieve the actual target URI (using some sort of Stork API) that it should send the request to. For simple HTTP requests this is clear, not completely sure about websocket traffic, but probably it should be that before establishing a websocket, retrieve the target URI from Stork, but after establishing it, keep using that, don't load-balance anymore. Maybe @michalszynkiewicz can confirm or correct me.

I don't know how websockets work with graphql, for "normal" usage of web sockets, making them _sticky_ is I think the way to go.

If what graphql does through websockets is stateless, probably on failure, Stork should be called once again to select a service instance
