### ISSUE TITLE
TypeSafe Client how to use List of Ids

### ISSUE THREAD

**Issue by robp94** [smallrye/smallrye-graphql#1359]
How to have a List of Ids as Parameter.
For the server, I can do something like this:

```
@NonNull
fun getByIds(@Id @NonNull ids: List<String>): Uni<List<Order>> {
```
(kotlin not tested in java, but should be similar)
which results in graphql like this:

```
"Query root"
type Query {
  _entities(representations: [_Any!]!): [_Entity]!
  _service: _Service!
  getByIds(ids: [ID]!): [Order]!
}
```

But if I create a Client with Java or Kotlin like this:
```
    Uni<List<Order>> getOrdersByIds(@Id @NonNull List<String> ids);
```
I get an error 
```
GraphQlClientException: errors from service
errors:
- Error{message=Validation error of type VariableTypeMismatch: Variable type 'ID!' doesn't match expected type '[ID]!' @ 'getOrdersByIds', locations=[{line=1, column=55}], path=null, extensions={queryPath=["getOrdersByIds"], description=Variable type 'ID!' doesn't match expected type '[ID]!', classification=ValidationError, validationErrorType=VariableTypeMismatch}})
```
I can't put the Annotation inside the list like:
```
Uni<List<OrderGQL>> getOrdersByIds(@NonNull List<@Id String> ids);
```
Since the target is not allowed.

Without the Id Annotation, it does work.

**Comment by phillip-kruger** [comment]
@jmartisk can you help ?

**Comment by jmartisk** [comment]
Please check if https://github.com/smallrye/smallrye-graphql/pull/1365 helps

**Comment by robp94** [comment]
I only have quarkus based tests. The current quarkus version seems not to work with the branch, so I can't test it.

If it is possible to get a schema with list of IDs in the client, it should be fine:

```
ids(list: [ID]): String
```
