### ISSUE TITLE
Server records arrays and sets not working

### ISSUE THREAD

**Issue by robp94** [smallrye/smallrye-graphql#1384]
With quarkus 2.8.2 arrays in records-inputs are always empty. This worked fine with 2.7.x.

They were usable fine with the @JsonbCreator workaround.

Reproducer:
[code-with-quarkus-set.zip](https://github.com/smallrye/smallrye-graphql/files/8630709/code-with-quarkus-set.zip)

**Comment by phillip-kruger** [comment]
Thats not good. We probably need tests for this then, so that it doe not happen again. @robp94 you keen to do a PR ?

**Comment by robp94** [comment]
Not sure if I have time for it. Maybe on the weekend.

**Comment by tigerinus** [comment]
I've just hit this bug using latest Quarkus 2.9.2 Final release, which includes smallrye-graphql-1.4.5 It's pretty blocking since an API of ours does need passing in an array of strings according to the design requirement.

I couldn't find any information about this fix being part of next Quarkus release. Do you have anything to share?

Thanks.

**Comment by tigerinus** [comment]
OK... I got my answer here:

https://github.com/smallrye/smallrye-graphql/compare/1.6.x...2.0.0.RC4

Quarkus 2.10 will include smallrye-graphql-1.6.0, which doesn't include this fix. 😐

**Comment by phillip-kruger** [comment]
Is there a fix ? Do you have the PR link for that fix ? Most things in 2.x is backported to 1.6.x. the only difference is the Jakarta namespace

**Comment by tigerinus** [comment]
> Is there a fix ? Do you have the PR link for that fix ? Most things in 2.x is backported to 1.6.x. the only difference is the Jakarta namespace

https://github.com/smallrye/smallrye-graphql/pull/1385

Isn't this the fix?

**Comment by phillip-kruger** [comment]
O, I missed that. It does not seem to have the backport label, so probably not. @jmartisk w.d.y.t ? Can we backport this ?

**Comment by robp94** [comment]
Should be in 1.6.x https://github.com/smallrye/smallrye-graphql/commits/1.6.x 9. May

**Comment by jmartisk** [comment]
Yeah I think I backported that while I was checking that the branch has everything it should contain. Nevertheless, we should try to use the label to avoid forgetting in the future

**Comment by phillip-kruger** [comment]
So this should be in Quarkus 2.10
