### ISSUE TITLE
no io.smallrye.graphql.client.dynamic.api.DynamicGraphQLClientBuilder in classpath when it obviously is

### ISSUE THREAD

**Issue by maxandersen** [smallrye/smallrye-graphql#1398]
I have these dependencies (which btw does not seem to be documented anywhere what dependencies to use):

```
//DEPS io.smallrye:smallrye-graphql-client:2.0.0.RC3
//DEPS io.smallrye:smallrye-graphql-client-api:2.0.0.RC3
```

then when calling:

```
 DynamicGraphQLClient graphql = DynamicGraphQLClientBuilder.newBuilder()
            .url("https://api.github.com/graphql")
            .header("Authorization", String.format("Bearer %s", ghToken))
            .build();
```

I get:

```
Exception in thread "main" java.util.ServiceConfigurationError: no io.smallrye.graphql.client.dynamic.api.DynamicGraphQLClientBuilder in classpath
	at io.smallrye.graphql.client.dynamic.api.DynamicGraphQLClientBuilder.newBuilder(DynamicGraphQLClientBuilder.java:35)
	at appstore.graph(appstore.java:73)
```

Which is obvious not true given that `io.smallrye.graphql.client.dynamic.api.DynamicGraphQLClientBuilder` is where the code fails.

What am I missing?

**Comment by phillip-kruger** [comment]
@jmartisk ^^^ ?

**Comment by jmartisk** [comment]
You need to add `io.smallrye:smallrye-graphql-client-implementation-vertx`. Right, the error message is a bit confusing, it should probably contain the word "implementation" because we're looking for an implementation of the `DynamicGraphQLClientBuilder` interface registered via ServiceLoader. I'll send a PR to improve it
Let me close this, if there are more issues let me know

**Comment by maxandersen** [comment]
Sounds good - should I open another issue for docs mentioning those required dependencies ? (I at least couldn't find it mentioned the places I looked)

**Comment by jmartisk** [comment]
We don't have a document describing how to run the client standalone, we generally assume that most people use it either through the Quarkus extension, or the WildFly feature pack, and these have their own ways and documentation.. 
But ok I guess we can create a short document for the standalone case, and maybe even a snippet with JBang. I'll write up something today.
