### ISSUE TITLE
Wrong schema for subscriptions with list as return value

### ISSUE THREAD

**Issue by LukasLeppich** [smallrye/smallrye-graphql#1401]
The return value of Subscriptions is not properly recognized when returning a list of items. 

```java
@Subscription("listSubscription")
public Multi<List<String>> listSubscription() {
    return Multi.createFrom().converter(MultiRx3Converters.fromObservable(), service.subject);
}
```

This code will create the following schema:

```graphql
"Subscription root"
type Subscription {
  listSubscription: String
}
```

I think it has something to do with the `isAsync` method in `DataFetcherFactory.java`, it only handles `Uni` but not `Multi`.

I created a minimal example with unit tests for this issue:
[https://github.com/LukasLeppich/graphql_array_subscription](https://github.com/LukasLeppich/graphql_array_subscription)

**Comment by phillip-kruger** [comment]
Thanks for this ! We will look at it a.s.a.p

**Comment by phillip-kruger** [comment]
@LukasLeppich you are spot on, that was the issue. Fixed now. Thanks. Should be part of v1.5.1 that we might pull into Quarkus 2.10.0
