### ISSUE TITLE
Subscription onClose: activeOperations not canceled

### ISSUE THREAD

**Issue by LukasLeppich** [smallrye/smallrye-graphql#1414]
The `Multi` response will not be closed if the websocket connection is canceled without an `COMPLETE` message type.
This result in an subscription leak. 

I added a new branch (`unsubscribe`) to my last minimal example:
https://github.com/LukasLeppich/graphql_array_subscription

There is an test case `testUnsubscribe` in `GraphqlTest.java` which shows the success case. Here the `cancel` function of the subscription is called which result in a `COMPLETE` message to be send to the subscription handler. Therefore if you use the `GraphQLClientApi` there is no subscription leak. 

In `src/main/resources/META-INF/resources` is a simple web application with a graphql subscription (http://localhost:8080/index.html). After 5 seconds the subscription is closed. If you refresh the browser with F5 within this 5 seconds you get a new subscription without canceling the old one. The old subscriptions keep sending out items until they are stopped by the `take(10)` operator. If you have no stop condition this would continue until a restart of the server. 

I tested it with quarkus 2.9.1.Final, so your latest changes are not in yet, but I think the subscriptions are still not canceled.

I think the `activeOperations` should all be unsubscribed in the [onClose()](https://github.com/smallrye/smallrye-graphql/blob/2557338b75074e9298ee3f19198c273abe8138b6/server/implementation/src/main/java/io/smallrye/graphql/websocket/AbstractGraphQLWebsocketHandler.java#L69) method of the `AbstractGraphQLWebsocketHandler`.

**Comment by jmartisk** [comment]
Hi, thanks for reporting - I'll look into this asap and let you know

**Comment by jmartisk** [comment]
Fixed in 1.6 and main branches
