### ISSUE TITLE
[Client] Generics: Enum in Generic Produces Malformed Query

### ISSUE THREAD

**Issue by schulzp** [smallrye/smallrye-graphql#1465]
Hi!

When using the type-safe client I notices the following behavior. Let's assume a generic type `DescribedValue<V>`:

```java
import org.eclipse.microprofile.graphql.NonNull;

public class DescribedValue<V> {

  @NonNull value;
  
  String description;
  
  /* ... */
  
}

public enum Option {
  OPTION_A, OPTION_B  
}

public class Resolver {
  @Query @NonNull DescribedValue<Option> getOption() {
    return new DescribedValue<>(Option.OPTION_A, "Option A");
  }
}
```

Then the client generates a query as follows:

````graphql
query option { option {value {name ordinal} description} }
````

That is malformed as enums do not allow sub selection (of `name` or `ordinal`).

Please see my M(N)WE: https://github.com/schulzp/smallrye-graphql-generics

**Comment by phillip-kruger** [comment]
@jmartisk @t1 I'll leave this for you yo comment. thanks :)

**Comment by jmartisk** [comment]
Seems we're not properly resolving type variables when generics are used with enums. I'll create a fix
