### ISSUE TITLE
TypeNameHelper breaking GraphQL Validation

### ISSUE THREAD

**Issue by Jacrispys** [smallrye/smallrye-graphql#1467]
> The system will add Input to the input GraphQL (that is why you see InputInput). Let me know if this works

Is there anyways around this?

_Originally posted by @Jacrispys in https://github.com/smallrye/smallrye-graphql/discussions/1454#discussioncomment-3159735_

This is a problem because if you have a class ending with `Input` it duplicates the name making it `InputInput`... This is specifically bad for my schema because it requires using an input object for all resolvers and mutations so we don't have a bunch of one offs...

It seems like you could probably just add a check in the `TypeNameHelper#getNameForClassType` method to see if the `annotationValue` is contained in the `ClassInfo`, I would/will PR this, but I want to make sure it is the correct solve for this issue...

**Comment by phillip-kruger** [comment]
Have you tried adding a @Name annotation on the class?

**Comment by Jacrispys** [comment]
There we go! That worked, I figured there was an annotation to bypass this, but wasn't sure what it was! That seemed to have worked!

**Comment by Jacrispys** [comment]
Might still be nice to automatically scan class names for the Annotation Value to prevent this before it happens though.
