### ISSUE TITLE
Gradle plugin does not work with Kotlin

### ISSUE THREAD

**Issue by re-thc** [smallrye/smallrye-graphql#1468]
See [GenerateSchemaTask.java LINE 288](https://github.com/smallrye/smallrye-graphql/blob/main/tools/gradle-plugin/plugin/src/main/java/io/smallrye/graphql/gradle/tasks/GenerateSchemaTask.java#L288) where it's hardcoded to only Java files.

Any chance this can be amended to also support Kotlin?

**Comment by phillip-kruger** [comment]
You keen to do a PR?

**Comment by jmartisk** [comment]
I'll look into this and while at it, try to fix our not-quite-good testing infrastructure for the gradle plugin

**Comment by jmartisk** [comment]
Done, this will be fixed in 1.7.1 and 2.0.0
