### ISSUE TITLE
Authorization in graphql with application properties

### ISSUE THREAD

**Issue by debu999** [smallrye/smallrye-graphql#1517]
Currently the only way to add Authorization is via @RolesAllowed.

  But same is also provided in Rest Controller Resources.

What i wanted to know is can we have it in application properties
This allows us to have common place to maintain the roles for queries and not to have several @RolesAllowed in each query if they are specific.

This might need a enhancement but definitely can be a good thing. As a lot comes via properties in Quarkus.

so i can state something like below

```quarkus.graphql.auth.policy.role-policy1.roles-allowed=AuditUser quarkus.graphql.auth.permission.role1.queries=auditQuery,auditManagement quarkus.graphql.auth.permission.role1.mutations=auditMutation,auditDelete quarkus.graphql.auth.permission.role1.policy=role-policy1 quarkus.graphql.auth.policy.role-policy2.roles-allowed=CaseUser quarkus.graphql.auth.permission.role2.queries=caseQuery,caseManagement quarkus.graphql.auth.permission.role2.mutations=caseMutation,caseDelete,escalateCase quarkus.graphql.auth.permission.role2.policy=role-policy2```

**Comment by phillip-kruger** [comment]
This will be implemented in Quarkus, not here in SmallRye. We can use the open ticket in Quarkus. Closing here. Thanks :)
