### ISSUE TITLE
Restructure

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#152]
change the root level pom to have better structure.

**Comment by phillip-kruger** [comment]
@andymc12 @t1 @ybroeker @jmartisk :

We have a lot of top level modules. That might not be an issue, so I want to get your feedback here.

I am thinking to have 3 top level modules:

common
client
server

Then under common, things that we share between client and server, not sure what that is at the moment, maybe the schema-model and schema-builder ?

All client stuff under client and server stuff under server.

The artifact Ids will stay the same so nothing will break. 

w.d.y.t ?

**Comment by t1** [comment]
I like the idea. Maybe we can also evolve the structure of the server module (currently artifact id `smallrye-graphql`): it could become `smallrye-graphql-server`, while we add a new module to `common` with only a pom with the artifact id `smallrye-graphql` pulling dependencies on `smallrye-graphql-server` and `smallrye-graphql-client`. Migrating to a new version would then simply pull client and server. It would be nice, if we could merge the servlet module into the server module, and it would magically only activate, if it recognizes a servlet environment. Same for the cdi module. I think the latter would be easy with a service loader, but I'm not sure how this could work with a servlet.

**Comment by jmartisk** [comment]
+1 for common/client/server modules with more submodules

To @t1 's suggestion about merging servlet+cdi into server, it would surely be convenient, I'm just not entirely sure if we will be able to do that without causing class loading problems if servlet/cdi classes are not present at runtime. And it feels kinda hacky. And it would mean some deployments would contain unnecessary classes, increasing the size of the deployment.

**Comment by t1** [comment]
Maybe `smallrye-graphql-server` could also be just a pom depending on `smallrye-graphql-server-core`, `...-cdi`, and `...-servlet`? Applications would depend only on `smallrye-graphql-server-api` as a `compile` dependency. If the application runs in a runtime directly supporting MP GraphQL (like Wildfly would do it with a MP GraphQL module), nothing else is required. If the runtime requires some activation dependency (like Quarkus would do it), a special runtime dependency is required, e.g. `quarkus-mp-graphql`. If there is no support from the runtime provider, the application developer will have to pull in some `runtime` dependency, and it would be very helpful if this would not have to be 3.

**Comment by t1** [comment]
We will have the same issue with #190 and probably other extensions. I'd like to have a convenient have-it-all dependency and leave the pick-and-choose for users that want to do so.

**Comment by jmartisk** [comment]
> Maybe `smallrye-graphql-server` could also be just a pom depending on `smallrye-graphql-server-core`, `...-cdi`, and `...-servlet`? 

That's what I understood from @phillip-kruger 's comment. The app can either depend on the whole `smallrye-graphql-server`, which includes `cdi` and `servlet`, or it can depend just on the `core` if it's enough.

> Applications would depend only on `smallrye-graphql-server-api` as a `compile` dependency. If the application runs in a runtime directly supporting MP GraphQL (like Wildfly would do it with a MP GraphQL module), nothing else is required. 

In that case, shouldn't the app just depend on `microprofile-graphql-server-api` with a `provided` dependency? If it does not need anything vendor-specific.

> If the runtime requires some activation dependency (like Quarkus would do it), a special runtime dependency is required, e.g. `quarkus-mp-graphql`. 

Yes, this is how it should be done. Just to clarify the extension will be `quarkus-smallrye-graphql`. I think the extension itself will depend on `smallrye-graphql-server-core` and `smallrye-graphql-cdi`, but not `-servlet`, because the extension itself will provide Vert.x routes instead of servlets.

**Comment by phillip-kruger** [comment]
Ok, so added to the above mentioned top level structure, now we also add `devtools` that will contain the maven module and maybe later the gradle one. Then I also want to add `ui` (or a better name if you can suggest it) that contains graphiql and/or graphql-playground. developers can then just include that jar to get the ui (same as swagger-ui for REST).

I am not sure where schema-builder and schema-model fits. Maybe it's common ?

So now we will have:

**common**
- ?
- schema-builder
- schema-model

**client**
- api
- implementation
- tck

**server**
- api
- implementation-cdi
- implementation-servlet
- implementation
- runner
- integration-tests

**devtools**
- common
- maven-plugin
- gradle-plugin

**ui**
- graphiql
- graphql-playground

w.d.y.t ?
