### ISSUE TITLE
Support some kind of controlled order from ServiceLoader for LookupService

### ISSUE THREAD

**Issue by brainlag** [smallrye/smallrye-graphql#1520]
Currently you can provide your own LookupService but this only works as long only on implementation is on the classpath.
If you have 2 or more the order is undefined and the wrong one might be used. We have this problem because we want to provide your
own but also use the smallrye-graphql-cdi dependency which already comes with its own implementation. Any way to control the order so it is possible to choose which implementation is used would be helpful.

**Comment by jmartisk** [comment]
Guess we could simply make it prioritize user-supplied implementations outside of the `io.smallrye` package? @phillip-kruger

**Comment by phillip-kruger** [comment]
Yes, or Quarkus
