### ISSUE TITLE
Record as input - @JsonbCreator on custom constructor is ignored

### ISSUE THREAD

**Issue by rmanig** [smallrye/smallrye-graphql#1523]
Hello,
I'm unable to use a custom constructor annotated with @JsonbCreator as my input type, the annotation will be just ignored.
Only the canonical constructor of the record and its parameters turn up in the generated schema.
Example: 

```
public record aRecord(Integer id, String name) {

    @JsonbCreator
    public aRecord(String name) {
        this(null, name);
    }

}
```

Generated input type:
```
input aRecordInput {
  id: Int
  name: String
}
```
Expected:
```
input aRecordInput {
  name: String
}
```
Shouldn't be there a precedence for an existing creator annotation? https://github.com/smallrye/smallrye-graphql/pull/1045/commits/23aa62a7667726f62d5e2dc0fbf2f52b122b9da5 seems to be the related change.
I'm happy to provide a PR.

Thanks in advance!

- Quarkus Version  2.11.2.
- java -version
openjdk version "17.0.4" 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)

**Comment by phillip-kruger** [comment]
Hi thanks for reporting this issue. A PR would help a lot !

**Comment by jmartisk** [comment]
Yeah! And with adding a little test into`integration-tests-jdk16/src/test/java/io/smallrye/graphql/tests/records/RecordTest.java` it would be even better. 
Let us know if you need any assistance
