### ISSUE TITLE
GraphQL @Source Mapping Enhancement from List 

### ISSUE THREAD

**Issue by debu999** [smallrye/smallrye-graphql#1528]
Current batch implementation for @Source assumes we get a list and return a list with same length.

Lets take a example for parent child relationship. 
```
public class Parent{
    String id;
    String name;
}
```

```
public class Child {
    String id;
    String name;
    String parentId;
}
```
so there are 2 parents A and B and 2 children both for A
<img width="1150" alt="Screenshot 2022-08-30 at 10 44 58 AM" src="https://user-images.githubusercontent.com/1910577/187354985-1c18b71a-ec44-4cee-ba83-c0e76592aa95.png">

adding a @Source for children to parent we now get incorrect result.
So there is match to list index to assign the results.
As you can see one child is now with Parent B. 

<img width="1267" alt="Screenshot 2022-08-30 at 10 49 40 AM" src="https://user-images.githubusercontent.com/1910577/187355690-affba18b-123d-4984-875a-d09857da35ef.png">

Suggession:
somehow we need to have a mapping for the object we processed and the results we received to track the final data stitching.
for example if we have first Parent with 2 results and 2nd with zero that mapping should be presented to do the mapping.

This prevents having lists at parent level. 
we have to do ChildrenWrapper class wtih List<Child> to achive. We should make this clear in documentation as well that if there is null then we need to explictly add null to list index to match Else we get errors as parent list size and child list size does not match.

@phillip-kruger hope the issue is clear. Let me know if any more clarification is required.

**Comment by debu999** [comment]
```
public List<Child> children(@Source List<Parent> p)
    {
        List<Child> children = new ArrayList<>();
        for(Parent p1: p){
            children.addAll(GraphqlResource.children.stream().filter(c->c.parentId.equalsIgnoreCase(p1.id)).toList());
        }
        return children;
    }
```

**Comment by phillip-kruger** [comment]
You keen to do a PR ?

**Comment by debu999** [comment]
I can give it a try for sure over weekends.

**Comment by t1** [comment]
If you look closely, the `children` field that you return is only an object, not a list, i.e. in your schema, one can only have a single child. Your batch resolver method needs to return a list of a list, i.e.:

```java
public List<List<Child>> children(@Source List<Parent> p)
    {
        List<List<Child>> children = new ArrayList<>();
        for(Parent p1: p){
            children.add(GraphqlResource.children.stream().filter(c->c.parentId.equalsIgnoreCase(p1.id)).toList());
        }
        return children;
    }
```

**Comment by phillip-kruger** [comment]
Well spotted. I wonder if we can build in some detection to warn / fail on these cases ?

**Comment by t1** [comment]
Hmmm... no, I don't think we can't detect that.

**Comment by t1** [comment]
Maybe we should improve the documentation and add an example, as it's something that newcomers may often get wrong.

**Comment by debu999** [comment]
This is perfect. Missed that analogy. Thanks a lot. We are good . Closing it.

**Comment by debu999** [comment]
There are assertions which guides in that direction anyways. So easy to figure out. But List<List<String>> as a definitely overlook from my side. Thanks a ton for the guidance. :s
