### ISSUE TITLE
EventingService.errorDataFetch not called on failed synchronous graphql operations

### ISSUE THREAD

**Issue by computerlove** [smallrye/smallrye-graphql#1530]
For synchronous graphql operations exceptions thrown does not result in invocations of `EventingService.errorDataFetch`.
Changing to `Uni<T>` gives the expected behaviour.

[Reproducer](https://github.com/computerlove/missing-error-eventingservice)

**Comment by phillip-kruger** [comment]
Thanks ! I'll have a look

**Comment by phillip-kruger** [comment]
This will  be fixed in Quarkus. I'll link back to here

**Comment by phillip-kruger** [comment]
Closing here. Fix is in a open PR in Quarkus
