### ISSUE TITLE
graphiql explorer features in graphql-ui

### ISSUE THREAD

**Issue by debu999** [smallrye/smallrye-graphql#1548]
Can the features of https://github.com/OneGraph/graphiql-explorer incorporated in graphql-ui

autocomplete of all variables is a must have feature on the UI.

**Comment by phillip-kruger** [comment]
Hi thanks for this. Are you keen to do a PR?

**Comment by debu999** [comment]
While looking at it now i find a lot of updates with graphiql 2.x raised 2 prs for 1.9.x and 2.0.0 for upgrade of the ui to latest version of 2.2.0 graphiql and onboarded the same to org.webjars.npm as well can those be merged?
https://github.com/smallrye/smallrye-graphql/pull/1658
https://github.com/smallrye/smallrye-graphql/pull/1659
