### ISSUE TITLE
Not possible to add Directives to Queries or Mutations for scheme generation

### ISSUE THREAD

**Issue by AlekseyMay** [smallrye/smallrye-graphql#1562]
Hi. I am using @MyDirective for fields on entities and it works great. Scheme generates correctly with needed directives. But if I want to add a directive to `@Query` method it doesn`t generate anything.
This is my directive:
```
@Directive(
		on = {DirectiveLocation.FIELD_DEFINITION}
)
@Retention(RetentionPolicy.RUNTIME)
public @interface MyDirective {
	@NonNull
	String operationId();
	@NonNull
	String domainId();
	@NonNull
	String describe();
}
```

```
@Data
public class Test {
	@MyDirective(operationId = "test", domainId = "test1", describe = "test2")
	String hello;
	int number;
}
```

That works correctly and generates directive for type field like this:
```
type Test {
  hello: String @myDirective(describe : "test2", domainId : "test1", operationId : "test")
  number: Int!
}
```
, but this:

```
@GraphQLApi
public class ExampleResource {
	@Query
	@MyDirective(operationId = "test", domainId = "test1", describe = "test2")
	public Test hello() {
		return new Test();
	}
}
```
is not generating anything in my schema. 
Expected behavior to see this, after scheme generation:
```
type Query {
  hello: Test @myDirective(describe : "test2", domainId : "test1", operationId : "test")
}
```

Have started using quarkus and gql several weeks ago, sry if my question is stupid. 
Is it smth wrong in my code? Or this feature is not supported?

**Comment by t1** [comment]
Thanks for your report, but it looks like @acanda was quicker than you 😜 see the PR #1557: It's been merged and will be in the next release.
