### ISSUE TITLE
Provide a way to access an ExecutionResult instance

### ISSUE THREAD

**Issue by ikenox** [smallrye/smallrye-graphql#1570]
Currently there seems no way to access an `ExecutionResult` instance, because it is directly consumed by `ExecutionResponse` and `ExecutionResponseWriter`.
https://github.com/smallrye/smallrye-graphql/blob/main/server/implementation/src/main/java/io/smallrye/graphql/execution/ExecutionService.java#L210

If we have the way to access that result instance, it's convenient to execute some result-dependent functionality e.g. custom logging.

How about to emit `@AfterExecute` event with not only `Context` instance but also `ExecutionResult` instance?
As a precedent, `@ErrorExecute` event is emitted with context and throwable instance.
https://github.com/smallrye/smallrye-graphql/blob/d15bbd47085f2dceddf4d5e655d3cc459fb008b2/server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/event/EventsService.java#L76

**Comment by t1** [comment]
Do you have very specific logging requirements, or could we integrate better logging into SmallRye GraphQL?

**Comment by ikenox** [comment]
In my case, I want to logging all errors at once. Currently it's a little difficult because `@ErrorDataFetch` event is emitted on each exceptions.
In addition, my logging output format is a specific json format of the our underlying logging service.

I can't determine whether it's a very specific requirement, but I think it's better to provide a simple way to just access the result instance because it's difficult to cover various requirements and situations explicitly.
On top of that simple feature, additionally providing the more-specific logging feature is good I think.

**Comment by t1** [comment]
If the logging would happen via, e.g., `slf4j`, then the actual output, e.g. JSON, would be defined by the runtime, not by SmallRye GraphQL. So the question would be: what data do you need? The `query` and `operation`, obviously. Do you want the `variables`? All headers (with a reduced Authorization header)? We could provide all of this data, e.g., in the MDC.

**Comment by ikenox** [comment]
Thanks for replying.

> If the logging would happen via, e.g., slf4j, then the actual output, e.g. JSON, would be defined by the runtime, not by SmallRye GraphQL.

That's right. So my explanation about logging format was not suitable reason for this issue, sorry.

> So the question would be: what data do you need?

The data I need is just a list of all errors that are occurred during the query execution. It can be obtained by `getErrors()` method of the `ExecutionResult` instance.

I want to see the all errors at once in order to summarize/filter and logging it. 
When a batch-query for N entities is failed (and `smallrye.graphql.printDataFetcherException` is enabled), it will produce N error logs. If there are many entities to batch-query, too many error logs will be printed. It's undesirable behavior for me.
Therefore I want to summarize/filter the all errors as I need. It can be achieved if the `ExecutionResult` is just provided.

**Comment by phillip-kruger** [comment]
We can maybe make the ExecutionResult available in the Context. Then you can listen to `afterExecute` event and unwrap from there.... keen to do a PR ?

Basically, add a new field on Context, `executionResult` that can be accessed via the unwrap method (so enhance that in context, handling null, as this will only be set right at the end).

Then in both `writeAsync` and `writeSync` in `EcexutionService`, set the field before firing the event. Here: https://github.com/smallrye/smallrye-graphql/blob/94079408e2dfd719274e5d2ce0c17cfc733c54ef/server/implementation/src/main/java/io/smallrye/graphql/execution/ExecutionService.java#L226

**Comment by ikenox** [comment]
I think I can try to make a PR. 
Before I do that, I want to make sure that the change does not break this library's existing design policy.
Do you have any concerns about the change, or do you have any better solution to get `ExecutionResult`?

Also, I think it's possible to fork the repository myself if my this requirement can be considered as too specific.
I'd be happy to hear your frank opinion. Thanks

**Comment by phillip-kruger** [comment]
No I think this is valid, and why we made the unwrap method in the context. Your PR is welcome
