### ISSUE TITLE
@GraphQLApi annotated classes Inheritance dont work from v1.4.3.1

### ISSUE THREAD

**Issue by galiatsatosc** [smallrye/smallrye-graphql#1592]
### **Use Case**
I have been using Smallrye-GraphQL in a Quarkus application.

I have a generated @GraphlQLApi Resolver class as a **base resolver** per entity with a generic implementations for list, create, update and delete entity operation.

I also have an other @GraphlQLApi per entity that **extends** the respective base class to override methods annotated with @Query that needs custom logic that i dont want to be lost every time the **base resolver** classes are generated again.  

### **Problem**
This implementations worked well till Quarkus version 2.8.0.CR1 and Smallrye-GraphQL version 1.4.3.

Starting from Smallrye-GraphQL version 1.4.3.1 this @GraphlQLApi class inheritance implementation fails at runtime with exception **AmbiguousResolutionException** when a query hits the inheritance related resolvers, as a result of **CdiLookupService** finding two beans.

From what I have seen,  **CdiLookupService** method **getInstance** implementation have been changed in Smallrye-GraphQL version 1.4.3.1 causing this behavior.

I understand that such kind of inheritance in Resolver classes is a bit too much and may be out of Smallrye-GraphQL support. But it would be nice if you continue supporting this kind of implementations.

A repository to reproduce this can be found here: https://github.com/galiatsatosc/graphql-api-inheritance

**Comment by jmartisk** [comment]
So you want to have two `@GraphQLApi` classes that (basically) contain the same operations, but how would the framework choose which of the implementations to use to handle a request? This feels a bit weird to me, wouldn't it be better to remove the `@GraphQLApi` annotation from the "base" API and use only the extending one?

**Comment by galiatsatosc** [comment]
Hello @jmartisk,

Yes its a bit weird to override a Resolver class.

The idea is to have the generic logic in the base classes as @Query annotated methods. 
If I remove the @GraphQLApi from the base i think in wont recognize the @Query annotated methods.

It worked until v1.4.3.1 because base resolver classes are annotated as @Dependent and the extending classes as @Alternative and @Priority(1) so CDI always selected the extending classes instead of the base resolver classes i think.

I will try to remove the @GraphQLApi to check if its by any chance working.

**Comment by galiatsatosc** [comment]
Unfortunately, removing the @GraphQLApi annotation from the base resolver class resulted in not recognizing the API methods annotated with @Query.

**Comment by phillip-kruger** [comment]
I think we can make that work.

**Comment by jmartisk** [comment]
Annotated methods from superclasses should probably be taken into account. I'll look into how complicated it will be to fix

**Comment by jmartisk** [comment]
I've submitted https://github.com/smallrye/smallrye-graphql/pull/1594 that might kinda resolve this - please have a look. It allows GraphQLApi classes to inherit annotated operations from superclasses. As long as that superclass is not a CDI bean, it should work. Otherwise you would still get the ambiguity problem.

**Comment by jmartisk** [comment]
Ok it will  be solved in SmallRye GraphQL 1.8.2, 1.9.0 and 2.0.0, so.. Quarkus 2.14
I'll close this, let us know in case you have more issues
