### ISSUE TITLE
Make ErrorExtensionProvider a singleton

### ISSUE THREAD

**Issue by pipinet** [smallrye/smallrye-graphql#1616]
<img width="1766" alt="image" src="https://user-images.githubusercontent.com/6096680/202229443-10cedfe9-e46b-45aa-9191-7586a80d7122.png">

it will create new instance every times error.
```java
ServiceLoader.load(ErrorExtensionProvider.class)
```

**Comment by phillip-kruger** [comment]
Would you be keen to provide an pull request with the fix ?

**Comment by jmartisk** [comment]
This will be resolved in 2.0.0, 1.9.0 and 1.8.3
