### ISSUE TITLE
Union Type of Scalars

### ISSUE THREAD

**Issue by panphg** [smallrye/smallrye-graphql#1624]
I'm trying to define a union type consisting of scalars, e.g.
```
union DateTimeOrDate = DateTime | Date
```
I tried the following with `@AdaptWith` (in Kotlin):

```kotlin
@Union
interface DateTimeOrDate

@AdaptWith(DateTimeScalarAdapter::class)
class DateTimeScalar(val value: Instant): DateTimeOrDate

class DateTimeScalarAdapter : Adapter<DateTimeScalar, Instant> {
    override fun to(s: DateTimeScalar?): Instant? = s?.value
    override fun from(i: Instant?): DateTimeScalar? = i?.let { DateTimeScalar(it) }
}

@AdaptWith(DateScalarAdapter::class)
class DateScalar(val value: LocalDate): DateTimeOrDate

class DateScalarAdapter : Adapter<DateScalar, LocalDate> {
    override fun to(s: DateScalar?): LocalDate? = s?.value
    override fun from(d: LocalDate?): DateScalar? = d?.let { DateScalar(it) }
}
```

This doesn't work and I get the exception `graphql.AssertException: A Union type must define one or more member types.` when starting my application.

If I do the same without the `@AdaptWith` annotations, then it generates the following union type:
```
union DateTimeOrDate = DateTimeScalar | DateScalar

type DateScalar {
  "ISO-8601"
  value: Date!
}

type DateTimeScalar {
  "ISO-8601"
  value: DateTime!
}
```

Is it possible to define a union type consisting of scalars?

**Comment by phillip-kruger** [comment]
Maybe @t1 know ?

**Comment by t1** [comment]
I just looked it up in [the spec](https://spec.graphql.org/draft/#sec-Unions.Type-Validation): "Scalar, Interface and Union types must not be member types of a Union.".

**Comment by t1** [comment]
sorry, wrong resolution
