### ISSUE TITLE
Improve error mapping (client)

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#167]
Currently, when there is an error response, a `GraphQlClientException` is thrown with the error list in the message... as a String.

1. Make the full error structure available to an exception handler.
1. Allow for a field in the expected result to contain error results (e.g. for partial results).
1. Introduce an error mapper that can throw specific exceptions derived from the errors received.

**Comment by Flame239** [comment]
Throwing an exception is not an option if we want to be able to read partial results. What I can propose here is to return `GraphQLResponse` here, something like:
```
class GraphQLResponse<RESULT> {
    // ...
    T getResponse();
     List<GraphQLError> getErrors();
}
```
and api class will look like:
```
public interface Client {
    @Query("findPugs")
    GraphQLResponse<Pug> findPugs(@NonNull PugColor color);
}
```
What do you think?

**Comment by t1** [comment]
@Flame239: Thanks for the feedback! I had almost that in mind for the number two in the description. I was more into something like `ErrorOr<Pug>`, which is a little bit like an `Optional`, only that the not-present alternative has also a value: the error. This could be used not only in the return type itself, but also in nested POJOs, i.e.:

```java
public interface SuperHeroes {
    ErrorOr<SuperHero> findByName(@NonNull String name);
}

public class SuperHero {
  private String name;
  private ErrorOr<Team> team;
}

...

ErrorOr<SuperHero> spidy = superHeroes.findByName("Spider Man");
if (spidy.isError()) {
  throw new SpidyNotFoundException(spidy.getError().getCode());
}
if (spidy.get().getTeam().isError()) {
  throw new NoTeamForSpidyException(spidy.get().getTeam().getError().getCode());
}
```

WDYT?

**Comment by Flame239** [comment]
Hm, having this wrapper for nested properties will add too much clutter: imagine having 10 properties in response and you will have to access them via response.get().getNested().get() all the time. 
Having error response is far more rare situation (hopefully :)) that having no errors, and I think having all errors in single object (like in graphql response) should suffice.

**Comment by t1** [comment]
You would use the `ErrorOr` only when actually needed, i.e. when you know that the server can return errors for this field. This can happen with separate root queries/mutations, or with a resolver method. You wouldn't do that for all fields.

And, like the `Optional` class, the `ErrorOr` class should have a `orThrow` method, so the demo code would be much simpler:

```java
SuperHero spidy = superHeroes.findByName("Spider Man")
    .orThrow(error -> new SpidyNotFoundException(error.getCode()));
Team team = spidy.getTeam()
    .orThrow(error -> new NoTeamForSpidyException(error.getCode()));
```

**Comment by Flame239** [comment]
Theoretically, server could return error for every field. Picking only some of them doesn't make much sense from clients perspective as we don't even know how server works. 
In addition to that, what we gonna do if field is not declared as `ErrorOr` but in response we got error for this field?

**Comment by t1** [comment]
> server could return error for every field

Yes, but the client needs to check for every possible error anyway. I'd still throw an exception if an error can't be mapped, either because the target is not an `ErrorOr` field, or because the error doesn't have a `path`, or there are two errors for one field. I think that's better than having an error go unnoticed.

BTW: I've started implementing this. It add complexity to the implementation, but I think it's a good investment for the simpler usage.

**Comment by t1** [comment]
Actually the `ErrorOr` class could hold multiple errors.

**Comment by Flame239** [comment]
> Yes, but the client needs to check for every possible error anyway
That is why I propose to keep all errors in one place

In real world I think there will be a lot of cases when clients just checks for error and if there are any - just treat whole request as failed. 

Anyways, I dont really understand based on what logic should we put `ErrorOr` or not. Could please give a tiny example?

**Comment by t1** [comment]
If you just want to react to _any_ error, you can simply catch the exception... we can even add the partial result data to the exception.

I see the whole topic more like #400 Union Types: if you want partial results, it's not really an error, is it? Maybe we should implement both variants and see which ones are actually being used.

**Comment by Flame239** [comment]
Alright, I'll implement this logic with `GraphQLResponse<>` and will create a PR

**Comment by t1** [comment]
That would be cool. Could you just hold your feet still just a little longer until I've added the other variant, as we will get into merge conflicts otherwise?

**Comment by t1** [comment]
@Flame239: can you take a look? I looks quite good to me in the tests and I'll use it in a project soon.

I'll break out number 3 into a separate issue.

**Comment by Flame239** [comment]
Hey, sorry I had a busy week, I'll take a look at this

**Comment by t1** [comment]
@Flame239: no worries! There's not time pressure, here.

**Comment by t1** [comment]
Nr. 1 has also been split out into a separate issue #509.
