### ISSUE TITLE
Default methods on interfaces lead to invalid schema

### ISSUE THREAD

**Issue by abeggchr** [smallrye/smallrye-graphql#1692]
### Reproduce
1. Clone the Git repository: git clone https://github.com/quarkusio/quarkus-quickstarts.git
2. Open solution microprofile-graphql-quickstart 
3. Add the `Person` interface (see below)
4. Make `Hero` implement person (see below)
5. Start Quarkus

``` java
public interface Person {
    default int getAge() {
        return 42;
    }
}

public class Hero implements Person {
    // no other changes in this class
}
```

Reproduction repository: https://github.com/abeggchr/smallrye-graphql-default-method

### Expected
- Quarkus starts
- The following query responds with age being 42:

```
query getFilmHeroes {
  film(filmId: 1) {
    heroes {
      age
    }
  }
}
```

### Actual
- An `InvalidSchemaException` is thrown because "object type 'Hero' does not implement interface 'Person' because field 'age' is missing"

### Question
- Is the actual behaviour a bug or expected?
- [if expected] Why is this expected?
- [if expected] What is the recommended way of dealing with default methods on interfaces, in particular in the case where you do not have control over the library providing classes and interfaces?
- [if expected] Is there a way to ignore certain properties for the schema, even if the properties are defined in classes we have no control over?

**Comment by abeggchr** [comment]
Possible workaround (when in control of the classes):

```java
public abstract class Person {
    default int getAge() {
        return 42;
    }
}

public class Hero extends Person {
    // no other changes in this class
}
```

**Comment by phillip-kruger** [comment]
This seems like it should work. So I would say this is a bug. Can you share the generated schema ?

**Comment by abeggchr** [comment]
As Quarkus does not start (due to the `InvalidSchemaExepction`) I am unable to get the schema at http://localhost:8080/graphql/schema.graphql. Please advise if there is another way to get the schema.

**Comment by phillip-kruger** [comment]
O, ok. Myself or @jmartisk will have a look a.s.a.p

**Comment by abeggchr** [comment]
Just a quick update from my side: I no longer need default methods to work. So you can relax the a.s.a.p
