### ISSUE TITLE
Allow java.lang.Iterable<T> as return type

### ISSUE THREAD

**Issue by krisraich** [smallrye/smallrye-graphql#1695]
When implementing a GraphQL query that yields a  java.lang.Iterable<T>, the following error is thrown:

```
2023-01-12 09:30:32,612 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.IllegalArgumentException: Invalid return type [java.lang.Iterable]
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getNonIndexedReference(ReferenceCreator.java:548)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:394)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForOperationField(ReferenceCreator.java:125)
        at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:68)
        at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:320)
        at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:122)
        at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:91)
        at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:267)
```

Method:

```
@Query("all")
public Iterable<TestEntity> getAll() {
    return this.testRepository.findAll();
}
```

It works flawlessly when wrapped in a List:

```
@Query("all")
public List<TestEntity> getAll() {
    return Lists.newLinkedList(this.testRepository.findAll());
}
```

Used with Quarkus version 2.15.3.Final and Smallrye GraphQL version 1.19.1

**Comment by phillip-kruger** [comment]
I think this is a reasonable request. @jmartisk w.d.y.t ?

**Comment by jmartisk** [comment]
So that would be translated, just like a collection/list, to `[TestEntity]` on the output, right?
Isn't it a possible issue that an Iterable may possibly be infinite? I assume that would be up to the application developer to make sure that the Iterable is finite and can be fully iterated through in a reasonable time.

**Comment by krisraich** [comment]
The reason i came upon this issue is, that many DB APIs (like MongoDB) return an Iterable<E> as result. It would be really handy and just more efficient to pass on this cursor. 

Also, i do not see any benefits (besides the assurance of a finite set) by using a List. Furthermore, the function `recursiveTransformCollection` in `io.smallrye.graphql.execution.datafetcher.helper.AbstractHelper.java` iterates over this list in a while loop and i can not find any other instances, where the list interface methods are utalised.

I would therefore even suggest to replace List<E> with  Iterable<E>. This won't break compatibility and would imo greatly enhance usability.

**Comment by krisraich** [comment]
I understand your concerns. The `ReactiveMongoClient` from quarkus uses unis and multis. However, i often use MongoJack. And this lib does not work well with the reactive mongodb client.
Since the rest api from quarkus is able to process an iterable, i would just make integrating graphql more seamless.

My request is solely a nice to have.

**Comment by jmartisk** [comment]
>  Since the rest api from quarkus is able to process an iterable, i would just make integrating graphql more seamless.

I tried doing this with RESTEasy Reactive, I can return an iterable from a REST endpoint, but it won't actually get iterated, the Iterator object is just converted by `toString()` and that is returned. Which is not quite useful. Thus I would rather say that it's not supported by REST either. Unless you're aware of some switch to make it behave differently?

All in all, I think that the possible complications (having to handle iterator's exceptions in the library, not knowing whether `next()` is a blocking operation, etc) outweigh the benefits, where it would only save you from having to convert an Iterable into a collection - which is not hard in most cases, but can get tricky when it involves remote calls etc., and that should be handled by application code, not the library.

I'll close it, unless someone brings up a good reason for changing my mind..
