### ISSUE TITLE
Boolean and null Request variables filtered before sent via GraphQL client

### ISSUE THREAD

**Issue by akarle** [smallrye/smallrye-graphql#1704]
Hello! First off, thank you for all your work on this library.

I wanted to report a small bug I noticed in the GraphQL client. Specifically, variables of native type "boolean" or "null" get filtered out of the payload. It's possible "null" is intentional, but booleans feel like they should be included!

Here's a small repro in Kotlin:

```kotlin
    val r = RequestImpl("foo")
    r.setVariables(mapOf("int" to 1, "str" to "bar", "bool" to true, "null" to null))
    println(r.variables)
    println(r.toJsonObject())
```

Prints:

```
{int=1, str=bar, bool=true, null=null}
{"query":"foo","variables":{"int":1,"str":"bar"}}
```

I've tracked the bug down to the `RequestImpl`'s `toJsonObject()` call on the `variables` property. Specifically, in `_formatJsonVariables` there doesn't seem to be a branch for these types:

```java
    private JsonObject _formatJsonVariables() {
        JsonObjectBuilder varBuilder = Json.createObjectBuilder();

        variables.forEach((k, v) -> {
            // Other types to process here
            if (v instanceof String) {
                varBuilder.add(k, (String) v);
            } else if (v instanceof Integer) {
                varBuilder.add(k, (Integer) v);
            } else if (v instanceof JsonValue) {
                varBuilder.add(k, (JsonValue) v);
            } else {
                try (Jsonb jsonb = JsonbBuilder.create()) {
                    JsonStructure struct = ((JsonBinding) jsonb).toJsonStructure(v);
                    varBuilder.add(k, struct);
                } catch (Exception ignore) {
                }
            }
        });

        return varBuilder.build();
    }
```

I haven't tested it, but it might be as simple as adding a couple new branches. Here's the link to the code: https://github.com/smallrye/smallrye-graphql/blob/d274e03530f060820a1dddbc46ca5f166324be7c/client/implementation/src/main/java/io/smallrye/graphql/client/impl/RequestImpl.java#L54

Thanks in advance for your time and help!

**Comment by phillip-kruger** [comment]
@jmartisk ^^^

**Comment by akarle** [comment]
Hi @jmartisk -- thanks for the response! I'll put up a PR with a unit test!
