### ISSUE TITLE
io.smallrye.graphql.client.impl.typesafe.HeaderBuilder: throws RuntimeException when parameter name is not available even when a name is provided in @Header

### ISSUE THREAD

**Issue by ftrossbach** [smallrye/smallrye-graphql#1714]
We recently tried to instantiate a GraphQL Client in Wildfly 27.0.1 with the GraphQl Feature pack that looked like this:

```
@GraphQLClientApi(configKey = "my-api")
public interface MyApi {

	@Query
	MyObject object(@Header(name = "some-header") String someHeader, String someId);
}
```
This failed with a RuntimeException:

```"Missing name information for arg0. You can either annotate all parameters with @Name, or compile your source code with the -parameters options, so the parameter names are compiled into the class file and available at runtime."```

We actually compiled the app without the -parameters, so changing this worked around the error. But I think it should never have been thrown as the parameter name from the byte code is only required as a fallback when there is no name provided in @Header. 

Expected behaviour: missing parameter name in the byte code should not fail in HeaderBuilder when there is a name provided in @Header

**Comment by jmartisk** [comment]
It won't work without `-parameters` anyway, because it needs to know the `someId` parameter's name, no?
I'd say `-parameters` is required in 99% cases, so it doesn't make a lot of sense trying to make the 1% work.

**Comment by t1** [comment]
`-parameters` is definitively the better option. But if you need only header parameters or you can't (for whatever reason) compile with `-parameters`, you'd have to annotate the header parameter, even though it's never used as you already have the `@Header` annotation!

I'll take a look.

**Comment by jmartisk** [comment]
Thanks @t1 for resolving this. Note that in the future we want to switch from reflective calls to scanning the application's Jandex index, so  `-parameters` won't be necessary at all then. But it's not something that will be resolved very soon.
