### ISSUE TITLE
GraphQL Endpoint handling/parsing incoming HttpRequest headers on Wildfly

### ISSUE THREAD

**Issue by GAskefalk** [smallrye/smallrye-graphql#1723]
I am trying to add security to a new GraphQL app  based on Wf27 with the feature pack for SmallRye GraphQL

I am trying this

` @Inject
    RoutingContext routingContext;`
    
    But i am getting an error (I assume i lack a provider?)
    
    I can see this working with Quarkus but we are using custom WF.
    
    Any help would be deeply appreciated.

**Comment by GAskefalk** [comment]
The Error:

17:16:10,910 ERROR [controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "cms-graph-ql-1.1.0-SNAPSHOT.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"cms-graph-ql-1.1.0-SNAPSHOT.war\".WeldStartService" => "Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type RoutingContext with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject com.scanreco.cms.microprofile.graphql.FilmResource.routingContext
  at com.scanreco.cms.microprofile.graphql.FilmResource.routingContext(FilmResource.java:0)
"}}

**Comment by t1** [comment]
`RoutingContext` is from vert.x, while WF is based on RestEasy, so it doesn't know how to provide that. What do you want to get from the context?

**Comment by GAskefalk** [comment]
Well WF is not based on anything really you can build any layers you like, and so is done for this edition.

But what i want from the context is really the Headers, specifically the Auth Header. I want it both for Authentication and Authorization.

What i have done so far is to setup a @Webfilter and catch the "SmallRyeGraphQLExecutionServlet" and obtain the headers there but i would rather do it with a securityfilter and a Vertx Route.

**Comment by t1** [comment]
You don't have to do that on your own. You can simply use Jakarta Security, e.g. `@RolesAllowed` for RBAC. Just remember to create an EJB context by annotating, e.g., your `@GraphQLApi` classes as `@Stateless`. We do that for all of our services.

**Comment by jmartisk** [comment]
The HTTP layer in WildFly is based on Undertow, not on Vert.x. I don't think it provides any specific way to get the headers, so I'm afraid you might have to either really use the webfilter to capture the headers programmatically, or use annotation-based security.

**Comment by GAskefalk** [comment]
@jmartisk thanks, but the feature pack för GraphQL that i setup via Galleon do use Vert.x with reactive streams and Context-propagation.

**Comment by GAskefalk** [comment]
@t1 thanks, however the @Rolesallowed is not how we roll, the whole access per endpoint is dynamic (via DB) and there are then two layers of DLAC, so i really need to get hold of the bearer token.

**Comment by jmartisk** [comment]
> @jmartisk thanks, but the feature pack för GraphQL that i setup via Galleon do use Vert.x with reactive streams and Context-propagation.

Yes, Vert.x is used internally for some things that depend on it, but the underlying HTTP engine is not based on Vert.x. And that's what matters here. In Quarkus, the HTTP engine is based on Vert.x. In WildFly, Vert.x does not generally come into play when handling HTTP requests.

**Comment by GAskefalk** [comment]
@jmartisk i see, but then i wonder, why is the FP containing both vertx, mutiny and context-propagation?

The way i have solved it, for now is by creating a webfilter and examine the request header(s) there, but having the RoutingContext injected would have been way nicer.

Thanks for you patience.

**Comment by jmartisk** [comment]
Vert.x is necessary for GraphQL clients (the SmallRye GraphQL client-side library uses Vert.x HTTP client), the server side doesn't use it.
Here you see that 
- the module with the client depends on Vert.x http client: https://github.com/wildfly-extras/wildfly-graphql-feature-pack/blob/2.0.0.Final/feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/graphql/client/vertx/main/module.xml#L21
- but the module for the server-side GraphQL doesn't depend on anything from Vert.x: https://github.com/wildfly-extras/wildfly-graphql-feature-pack/blob/2.0.0.Final/feature-pack/src/main/resources/modules/system/layers/base/io/smallrye/graphql/main/module.xml

Mutiny is included in WildFly itself, that's not from the feature pack.
Context propagation is added by the feature pack because of some internal things that are needed by SmallRye GraphQL.

**Comment by GAskefalk** [comment]
@jmartisk ok thank You, this means i most probably can shrink my custom WF as it is server alone.

Thanks for the support!

**Comment by jmartisk** [comment]
Yeah unfortunately the GraphQL feature pack currently has only one layer, and that layer contains both server+client, so it won't be that easy to install only the server (I think you'd need to remove the client modules manually after installing the feature pack).. Perhaps this is something to improve in the future of the feature pack

**Comment by GAskefalk** [comment]
Yes that is the way i do it, it let Galleon build and then i pick the moduls (and/or) Layers/Modules i need.

There is a lot going on in the dockerbuild with the standalone.xml so this is actually the fastest way, for now.

At some point maybe i would extend the galleon to take a base provision and diff it to find out what needs to be added.

**Comment by GAskefalk** [comment]
.. as i run it on ACA (Azures scaled down K8S PaaS) i  am limited to 4GB so in some sense it is like doing embedded as RAM is tight.

**Comment by t1** [comment]
> i really need to get hold of the bearer token.

If that's a JWT, you can simply `@Inject` a `JsonWebToken`... or even only the claims you need. See the [MP JWT Spec](https://download.eclipse.org/microprofile/microprofile-jwt-auth-2.1/microprofile-jwt-auth-spec-2.1.html) for details.

**Comment by GAskefalk** [comment]
@t1  thanks.

**Comment by GAskefalk** [comment]
@jmartisk 

Another Question on Context.

So i am intercepting the call on the ExecutionServlet, what i would need then is to be able to convey some data (That i buld in the WebFilter) to the 

```
@GraphQLApi
@ApplicationScoped
public class ProductResource {
}

Is there som way to do that? The experimental Smallrye Context seems to be readonly, i would need to
Write some data to A context so that the GraphqlAPI class could get it.

Is there some way to do that on the Wildfly implemention?
```

**Comment by jmartisk** [comment]
Did you actually manage to inject the `io.smallrye.graphql.api.Context` into a WebFilter? I actually think that the webfilter runs too early and the Context object might not exist yet at that point.... Hmm...

**Comment by jmartisk** [comment]
If you manage to inject the Context somehow, then you should be fine because you could then use 
```
context.unwrap(graphql.GraphQLContext.class).put("foo", "bar");
```
to put whatever you want into the underlying `graphql.GraphQLContext`

But I'm not sure it will work, as I mentioned in the previous comment.
I have another idea though. You could create your own `@RequestScoped` bean that holds any of the data that you need to pass from the webfilter into the GraphQL API, and inject the instance in both places.

**Comment by t1** [comment]
The GraphQL Context is not the right container for your data. The last suggestion of @jmartisk is the way to go.

**Comment by GAskefalk** [comment]
Ok i see makes sense.
Even though i get the feeling like i am trying to get a pig in a smoking...
Maybe we would benefit from moving to Quarkus?

**Comment by jmartisk** [comment]
>  Maybe we would benefit from moving to Quarkus?

Well, what to say here. Yes. :) 
I can't resist the temptation to add a link to the book that I'm co-authoring now: https://www.manning.com/books/quarkus-in-action in case you're interested in learning Quarkus.

**Comment by jmartisk** [comment]
Ok I'm glad that we've found a solution, I'll close this issue now!
