### ISSUE TITLE
Add our own @Deprecated annotation + directive

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#1736]
Add a `@io.smallrye.graphql.api.Deprecated` annotation that has an optional `String reason` parameter and is transformed into the schema as a directive.
The directive should look the same as described in https://spec.graphql.org/draft/#sec--deprecated
This can be a task for @mskacelik

**Comment by michaelbird1155** [comment]
It would be cool to extend or implement java.lang.Deprecated as well so that IDEs see the field as deprecated. However, I understand the flexibility of having both options can be benefitial. On the other hand, if someone wants both do we really want the below? 

```
@Deprecated
@java.lang.Deprecated
private String myField
```

**Comment by t1** [comment]
I'd also rather reuse the existing `java.lang.Deprecated` or reading the code becomes messy. They both have the same semantics, so I think it would be okay. And in case you really need it, a custom `@Deprecated` annotation would be trivial to add.

**Comment by jmartisk** [comment]
`java.lang.Deprecated` has two params that we don't want (`since` and `forRemoval`) and doesn't have the one param that we do want (`reason`). Where would we read the reason from?

**Comment by jmartisk** [comment]
My main point is we want to have an annotation with an API that exactly matches the API of the directive mentioned in the GraphQL spec.
Maybe we could go with both - transform `java.lang.Deprecated` into a `@deprecated` directive without a reason, 
but also  have our own annotation that has a `reason` parameter, which would be added to the directive.

**Comment by t1** [comment]
Fair point. It's just ugly to have several annotations on your classpath triggering different behaviour. Supporting both would be the best compromise, I guess.
