### ISSUE TITLE
Using io.smallrye.graphql.api.Adapter is cause of memory leak 

### ISSUE THREAD

**Issue by aliaksei-dudko** [smallrye/smallrye-graphql#1739]
Using @AdaptWith with custom adapters leads to creating a huge amount of the same io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker objects.
Attempt to find an appropriate ReflectionInvoker in io.smallrye.graphql.execution.datafetcher.helper.AbstractHelper.invokerMap always fails and a new one is created due to the key calculation inside 
io.smallrye.graphql.execution.datafetcher.helper.AbstractHelper.getKey.

```
 private Integer getKey(String className, String methodName, List<String> parameterClasses)  {

        return Objects.hash(className, methodName, parameterClasses.toArray());
  }
```

Calling toArray on the List leads to creating a new array each time when the key is resolved and each time we get a new hash for the same ReflectionInvoker and put it in invokerMap instead of getting the old one:

```
 private ReflectionInvoker getReflectionInvoker(String className, String methodName, List<String> parameterClasses) {

        Integer key = getKey(className, methodName, parameterClasses);
        if (invokerMap.containsKey(key)) {
            return invokerMap.get(key);
        } else {
            ReflectionInvoker reflectionInvoker = new ReflectionInvoker(className, methodName, parameterClasses);
            invokerMap.put(key, reflectionInvoker);
            return reflectionInvoker;
        }
    }
```

I think that the right way to calculate hash for array is Arrays.hashCode(array)
And key calculation can be rewritten as:
`Objects.hash(className, methodName, Arrays.hashCode(parameterClasses.toArray()))`

in this case we get the same key for equal parameters.

To reproduce the issue:
1)Create custom adapter:

```
public class StringTestAdapter implements Adapter<String, String> {
	
	public String to(String to) throws Exception {
		return to;
	}

	
	public String from(String from) throws Exception {
		return from;
	}
}
```

2)Use it in retrieving Object:

```
public class TestInfo  {

	@AdaptWith(StringTestAdapter.class)
	private String description;
}
```

3) Get this object using smallray-graphql several times

Expected result:
One ReflectionInvoker was created.

Actual Result:
Several ReflectionInvokers are created for the same adapter
![Screenshot 2023-02-14 at 16 49 03](https://user-images.githubusercontent.com/67433428/218788745-09421f8d-dcd5-477f-ab0b-02b068e0bbac.png)

As these links are alive therefore GC can not clean memory :
<img width="1198" alt="Screenshot 2023-02-14 at 17 04 11" src="https://user-images.githubusercontent.com/67433428/218793643-5e8a14f9-18aa-4422-9c9d-43bd1fabd148.png">
<img width="1155" alt="Screenshot 2023-02-14 at 17 06 45" src="https://user-images.githubusercontent.com/67433428/218793647-43cede51-f9ca-4568-aab9-4e353ca2f3de.png">
<img width="1155" alt="Screenshot 2023-02-14 at 17 10 00" src="https://user-images.githubusercontent.com/67433428/218793658-b4d74591-371f-4038-a940-ea8e1fa327fe.png">

<img width="1166" alt="Screenshot 2023-02-14 at 17 13 21" src="https://user-images.githubusercontent.com/67433428/218794297-d6bd06cd-cbef-4a6e-9d11-63053f2560dd.png">

**Comment by jmartisk** [comment]
resolved via #1740

**Comment by jmartisk** [comment]
@aliaksei-dudko I'll do it right away then, it should be in Maven Central within a few hours

**Comment by aliaksei-dudko** [comment]
@jmartisk thank you
