### ISSUE TITLE
Unable to pass enum as argument in GraphQL client query

### ISSUE THREAD

**Issue by aliaksei-dudko** [smallrye/smallrye-graphql#1747]
Passing Enum as an argument to GraphQL client is the cause of throwing exception IllegalStateException("Could not format " + value.getClass() + ": Unsupported type.") as Enum is not included in UNQUOTED_VALUES array in io.smallrye.graphql.client.impl.core.utils.ValueFormatter.

Step to reproduce:
1) create enum: 
```
public enum Order {
    ASC,
    DESC
}
```
2) create Document with enum as an argument and pass it to GraphQL client:

    @Inject
    DynamicGraphQLClient client;
    .......
    Document query = document(operation(field("field", args(arg("order", Order.ASC)))));
    Response response = client.executeSync(query);
    ..........

Would be good to include Enum.class into UNQUOTED_VALUES array:

`    private final static Class<?>[] UNQUOTED_VALUES = new Class[] { Number.class, Boolean.class, Enum.class };`

PR with fix: https://github.com/smallrye/smallrye-graphql/pull/1748/files

**Comment by jmartisk** [comment]
fixed via #1748
