### ISSUE TITLE
Extensions Support

### ISSUE THREAD

**Issue by michaelbird1155** [smallrye/smallrye-graphql#1750]
Is there support for returning an extensions object? I see in the ExecutionResponse that there is already code to add errors, data, and extensions to the response but I haven't found a way to add extensions to the response. I have tried accessing the context object in the @query annotated method to add extensions through the ExecutionInput object but it is too far down the chain of events at that point. Having a way for developers to add to the extensions object is useful for returning metadata to the client about the data and fields that are returned. In my case, a warning that a field is deprecated is very useful. 

Graphql-java already has support for instrumentation so I think being able to hook into that functionality is a good route.

**Comment by jmartisk** [comment]
Could we perhaps offer a method on the `SmallRyeContext`, like `setExtension(String key, JsonObject value)` for this?

**Comment by t1** [comment]
Sounds good. Only that the value parameter should be a `JsonValue`, as it could also be primitive or an array. And maybe we should accept `Object` and convert it to json automatically.

We probably should also think about how to support extensions on the client side.

**Comment by phillip-kruger** [comment]
I would say the value should be any (Json serializable) object. We can make it json in the background. So `setExtension(String key, Object value)`
