### ISSUE TITLE
MicroProfileConfig can't parse config correctly

### ISSUE THREAD

**Issue by pfaul** [smallrye/smallrye-graphql#1756]
The MicroProfileConfig stores many fields as Optionals but checks against null. This makes custom exception handling impossible.

private Optional<List<String>> errorExtensionFields;

errorExtensionFields == null // is false, since Optional.empty() is not null!

All Optional fields in the MicroProfileConfig should be stored as the actual objects and not Optionals!

**Comment by phillip-kruger** [comment]
We use that to fall back to default. Or not set. So when a user does not provide that config, we do the default. What are you trying to achieve ?

**Comment by pfaul** [comment]
Maybe my description was not clear enough. The current implementation of MicroProfileConfig does not do, what it is supposed to do. The code under the if(errorExtensionField == null) is never executed, because the default value of errorExtensionFields = Optional.empty().

Optionals are not supposed to be stored as fields. Even IntelliJ is marking the code as errorprone/false.

**Comment by phillip-kruger** [comment]
Ok, maybe provide a reproducer of the issue, and a PR that fix it as you think.
