### ISSUE TITLE
Support adding operation directives with typesafe client

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#1763]
.. via some special annotations, maybe?

**Comment by t1** [comment]
See: https://graphql.org/learn/queries/#directives and http://spec.graphql.org/draft/#DirectiveDefinition

As we support directives already on the server side, we should use the same API as much as possible, so it should be possible to add annotations as directives by annotating them as `@Directive`.

Directives like `@include(if: Boolean)` and `@skip(if: Boolean)` can also have dynamic parameters set via `variables`. I'm not sure how to handle that. Now that I'm thinking about this, how can we access directives on the server side? And the spec says, we _should_ provide at least those two. It would be easy to add them as directives, but could we handle them directly in smallrye, i.e. not calling a resolver or so?

**Comment by jmartisk** [comment]
> As we support directives already on the server side, we should use the same API as much as possible, so it should be possible to add annotations as directives by annotating them as @Directive.

Yeah I agree. For directives with static (known at compile-time) values, annotations should be good.

With dynamic values, it will be more tricky, we can't just reuse the current annotation approach from the server side, because they aren't prepared for dynamic values. We would have to require the annotations to have a `method` parameter to point to a supplier method of the value (like we do it with the `@Header` annotation), but that would be useless on the server side, because the schema expects a static value.

> how can we access directives on the server side?-

They are available through the `DataFetchingEnvironment`
As for `include` and `skip`, I think they are handled automatically by graphql-java on the server side.

**Comment by t1** [comment]
Good point. The `@Header` annotation can also be placed on a method parameter, which makes it easy to call directly with a specific value. We could allow that also for directives... and maybe even on the server-side!

Thanks for pointing out the handling of `@include/skip(if)` by graphql-java! Didn't realise before.

**Comment by jmartisk** [comment]
> Good point. The @Header annotation can also be placed on a method parameter, which makes it easy to call directly with a specific value. We could allow that also for directives... and maybe even on the server-side!

My point is that on server side, the values have to be static (they are built into the schema once), so if a directive annotation has a `method` parameter pointing to a method, that will be usable by the client, but not if you use the same on the server side.

Also how would it work for directives that have multiple arguments? The user would have to declare something like

```
@Directive(on = { FIELD })
@Retention(RUNTIME)
public @interface MyDirective {
  String argument1();
  String argument1_method();
   String argument2();
  String argument2_method();
}
```

and then 
```
public class Customer {
  @MyDirective(argument1_method="arg1", argument2_method="arg2")
  String name;

  static String arg1() {
    // provide value for "arg1"
  }
   
   static String arg2() {
    // provide value for "arg2"
  }
}
```

Which is really ugly and not really typesafe.

The `arg1` and `arg2` methods probably have to be static, because when building a query, we don't have any usable instance of `Customer` existing on the client side where we could invoke them. I'm also not sure if this would be usable at all given the quite limited context information that the implementation code of `arg1` and `arg2` would be able access.

**Comment by jmartisk** [comment]
I think this would be way beyond the intended proper usage of Java annotations :/

**Comment by t1** [comment]
How about something like this:

```
/** no-arg directive */
@Directive(on = FIELD)
@interface Reverse {
}

/** two-arg directive */
@Directive(on = FIELD)
@interface Page {
    int offset() default 0;
    int size() default 100;
}

public List<Book> books(@Reverse boolean reverse, @Page int offset, @Page int size)
```

The no-arg directive turns into a boolean parameter where the name `reverse` is arbitrary.

The two-arg directive turns into two parameters where the names have to match the annotation methods.

This could work on the client as well as on the server. But on the server side, directives mostly make sense when they are not just a different syntax for parameters sprinkled everywhere, but some sort of meta-programming tool. This could become something like this:

```
@Inject Page page;

public List<Book> books() {
    int offset = page.offset();
}
```

What do you think?

**Comment by jmartisk** [comment]
I don't know, to my taste this still feels a bit like an abuse of annotations. Annotations just aren't good for anything that is dynamic. Besides, what if the query contains the same directive type in multiple places (multiple fields, arguments, the operation itself, fragments), then you wouldn't be able to specify different values for them.
Or, in your server-side example, which `@page` directive exactly the injection point it referring to, if the query contains more of them.

**Comment by jmartisk** [comment]
Support for directives with non-dynamic values has been added via https://github.com/smallrye/smallrye-graphql/pull/1990
