### ISSUE TITLE
Support unwrapping the raw Response (and more metadata) when using typesafe clients

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#1764]
Sometimes, when using a typesafe client, it might be necessary to obtain additional metadata besides just the data object created from a response:

- response HTTP headers
- contents of the `extensions` field sent by the client
- String with the raw response, maybe (for troubleshooting purposes?)
- and potentially more

I imagine we could accomplish by adding a class, say, `TypesafeClientResponse`, and allow this:

```
List<Customers> customers = client.getCustomers(); // the actual typesafe graphql client call
TypesafeClientResponse response = TypesafeClientResponse.unwrapFrom(customers);
Map<String, String> = response.getHttpHeaders();
JsonObject responseExtensions = response.getExtensions();
```

Question remains how to implement this `retrieveFrom` method. Options are:
- The typesafe client proxy will return a proxy object (in this example, instead of a plain `List<Customer>` it would return some special proxy that implements `List<Customer>` but also contains the necessary data to build the `TypesafeClientResponse`)
- Or, perhaps better, we could follow the path that `ErrorOr` follows, and allow declaring the client API to wrap the return type into a generic class `TypesafeClientResponse<List<Customer>>` instead of just `List<Customer>`. In this case, the generic `TypesafeClientResponse` could also contain all functionality of `ErrorOr`, so that one does not have to do something like `TypesafeClientResponse<ErrorOr<List<Customers>>>`.

**Comment by jmartisk** [comment]
@t1 I'd like to hear what you think :)

**Comment by t1** [comment]
The second options sounds good to me, while the first one smells like a lot of complexity.

**Comment by jmartisk** [comment]
Yeah I agree, given that we already have a kinda similar approach with ErrorOr, we should follow the same pattern.
