### ISSUE TITLE
Support for Jackson Objects in Smallrye Graphql

### ISSUE THREAD

**Issue by debu999** [smallrye/smallrye-graphql#1773]
https://github.com/leangen/graphql-spqr/blob/master/src/main/java/io/leangen/graphql/module/common/jackson/JacksonObjectScalars.java
Leangen have added the support for custom graphql scalars can this be added to smallrye-graphql out of the box ?

**Comment by t1** [comment]
I suppose that _if_ we do support JSON objects, it would be better to not use the Jackson APIs but [JSON-P](https://jakarta.ee/specifications/jsonp/2.1/), as the latter are a specification, while the former are not. If everybody agrees, we should close this issue and focus on #1776

**Comment by debu999** [comment]
Yes thats correct. Lets focus on #1776 instead. Closing this request.
