### ISSUE TITLE
How to use @Directive and @DataFetcher

### ISSUE THREAD

**Issue by ghost81** [smallrye/smallrye-graphql#1800]
Hi,  

I have an annotation annotated with `@Directive` metaanotation, that is allowed only on fields. Let's call it `@specialValue`
In my `Query` i have something like 
```
{  
...  
field1 @specialValue  
field2  
field3 @specialValue  
...  
}
```

How I can attach some server code to be executed when this directive is applied on a field. I tried to annotate a class with it, which extends `SchemaDirectiveWiring` from `graphql-java`, but nothing happens.   
Is there any not documented functionality that will help

**Comment by ghost81** [comment]
Another interesting question is how `@DataFetcher(forClass=....)` could be used. I can't find any processing for classes having this annotation.

**Comment by jmartisk** [comment]
I'm closing this as explained, please reach out if you have further questions
