### ISSUE TITLE
Make the MP Metrics support pluggable

### ISSUE THREAD

**Issue by andymc12** [smallrye/smallrye-graphql#182]
Ideally, the SmallRye GraphQL project would not depend on the SmallRye Metrics implementation - but instead would only depend on the MP Metrics APIs.  That would allow containers like Open Liberty to plug-in different Metrics implementations.

**Comment by jmartisk** [comment]
AFAIK there is just one case of using a class directly from SR Metrics: https://github.com/smallrye/smallrye-graphql/blob/master/implementation/src/main/java/io/smallrye/graphql/bootstrap/Bootstrap.java#L96 
if we removed that (and instead accessed the registry using `CDI.current()` or something similar), would that be fine?
I'm also thinking whether we can completely remove the SR Metrics dependency and expect the container to add it by itself. I think that could work.

**Comment by phillip-kruger** [comment]
I would expect the container to add it.

**Comment by jmartisk** [comment]
One problem is that without using SR-Metrics specific classes, there's no standard way to obtain a `MetricRegistry` without using CDI classes. So we could do this, but it will be quite ugly. I'll try to come up with something and send a PR, but I fear we won't be able to prevent it from looking a bit weird. Let's see.
Unfortunately Metrics in general do depend on CDI, there's no way to get them running without it at the moment.
