### ISSUE TITLE
The @Key Federation Directive should not be set on "Input" Object

### ISSUE THREAD

**Issue by vitomanu96** [smallrye/smallrye-graphql#1867]
```
@Key(fields = "codice")
public class Comune {

    @Id
    private String codice;
}
```

I use the Comune object for both querying and mutating data, and the @key annotation should not be set in the schema.graphql file within the ComuneInput definition

```
input ComuneInput @key(fields : "codice") {
  codice: ID
}
```

**Comment by francescopochi** [comment]
Same problem here.

**Comment by A1berto** [comment]
Having the same issue ^

**Comment by phillip-kruger** [comment]
Thanks for this ! @jmartisk @mskacelik can you have a look ? Maybe @t1 ?

**Comment by jmartisk** [comment]
@mskacelik is looking. Turns out this is not only a problem for `@Key`, we put directives all over the place regardless of element types on which a particular directive is allowed. So we're going to take a wider approach to the fix.

**Comment by vitomanu96** [comment]
> @mskacelik is looking. Turns out this is not only a problem for `@Key`, we put directives all over the place regardless of element types on which a particular directive is allowed. So we're going to take a wider approach to the fix.

@mskacelik if you need help, contact me.

**Comment by mskacelik** [comment]
@vitomanu96 can you please check PR if everything works as intended? Hopefully It should be fixed now.
https://github.com/smallrye/smallrye-graphql/pull/1878
