### ISSUE TITLE
Version compatible with Java 8

### ISSUE THREAD

**Issue by liorot** [smallrye/smallrye-graphql#1874]
It appears that the latest library version (of the client) compatible with Java 8 is 1.4.5. 
However, I noticed that MicroProfile supports JDK 8 in all its versions. Now, I'm wondering if there is a way to use the newer library versions with Java 8.

**Comment by jmartisk** [comment]
Hi, not really, we dropped Java 8 support together with Quarkus and WildFly, which are the two main runtimes that SmallRye GraphQL is integrated with. The MicroProfile spec, IIUC, allows implementations to support Java 8, but doesn't require them to do so.

If you really have to stay on 8 and need some particular fixes, I'm open to backporting some fixes into the 1.4.x branch and doing some releases of it, but you'll need to prepare the backport PRs. No new features are planned for such an old branch.

**Comment by jmartisk** [comment]
I'm closing this as I've explained the situation. Feel free to reach out if you have further questions
