### ISSUE TITLE
Best way to distinguish between null and undefined input value

### ISSUE THREAD

**Issue by va1erian** [smallrye/smallrye-graphql#1892]
Hello there, I'd like to implement a partial update mechanism for my mutation by distinguishing between an explicit null value for a given input parameter (we want to delete the field value in the persistence layer) and an undefined value (we want to leave the field as is).

I found a way to do this by wrapping the fields of my input object with @Nullable Optional<>, and now I get a null field if the field is undefined in the mutation invocation and Optional.Empty if the value has been explicitely set to null in the mutation invocation.

However I found this behavior to be a bit counter-intuitive and I'd like to ideally avoid having Optional<> as a field type. Is there a better way to do this? Could I bring my custom generic wrapper and set up a custom deserialization mechanism?

**Comment by jmartisk** [comment]
There's really no "official" way to do this AFAIK...

You can use your own custom deserializer if it helps. You have to create an `EventingService`, register it for the ServiceLoader (inside `META-INF/services/io.smallrye.graphql.spi.EventingService`)

```
public class Customizer implements EventingService {
    @Override
    public String getConfigKey() {
        return null;
    }

    @Override
    public Map<String, Jsonb> overrideJsonbConfig() {
        JsonbConfig config = new JsonbConfig().withDeserializers(new CustomDeserializer());
        Jsonb jsonb = JsonbBuilder.newBuilder().withConfig(config).build();
        return Map.of("CLASS_THAT_YOU_ARE_OVERRIDING", jsonb);
    }

    public class CustomDeserializer implements JsonbDeserializer<CLASS_THAT_YOU_ARE_OVERRIDING> {
        @Override
        public OrderItemInput deserialize(JsonParser parser, DeserializationContext ctx, Type rtType) {
            // deserialize here
        }
    }
}
```

**Comment by jmartisk** [comment]
Another way would be to `@Inject SmallRyeContext` and then call `context.getQuery()` or something that  allows you to inspect the raw query, and gather your information from that....

**Comment by va1erian** [comment]
Thanks for your replies, I think i'll just stay with the nullable optionals and silence the warning in intellij, it works well enought so far.
