### ISSUE TITLE
Support for batch loader in federation

### ISSUE THREAD

**Issue by robp94** [smallrye/smallrye-graphql#1903]
For better performance, batch loader should be supported. For this we should first check if there are any batch loaders which can resolve types in the current request and if so we need to group all requests. Later, we need to make sure we restore the old order of the request. The batch loader of users, although most respect the correct order.

**Comment by phillip-kruger** [comment]
Can you explain your use case a bit more? Batch loading is already supported when using source fields with List parameters, see https://www.youtube.com/live/PHWOzzusfrY?feature=shared around 45 mins into the video

**Comment by robp94** [comment]
Sure,
the federation implantation currently resolves every representation (one object to resolve in a federation request) on its own. https://github.com/smallrye/smallrye-graphql/blob/36883cd996c40a0163d64e6e686c1ddeae82e20a/server/implementation/src/main/java/io/smallrye/graphql/bootstrap/FederationDataFetcher.java#L38

Furthermore, it only checks for the exact type, which does not include batch resolvers. https://github.com/smallrye/smallrye-graphql/blob/36883cd996c40a0163d64e6e686c1ddeae82e20a/server/implementation/src/main/java/io/smallrye/graphql/bootstrap/FederationDataFetcher.java#L57

The use case is quite simply better performance, like with every batch loading.
