### ISSUE TITLE
2.4.0 fails quarkus federation test

### ISSUE THREAD

**Issue by robp94** [smallrye/smallrye-graphql#1906]
For me, 2.4.0 does fail with the federation test in quarkus.

```
GraphQLFederationTest.checkFederationDirectivesInSchema:39 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "name: String @extends"

```

Does this work for you @jmartisk?

I tried my local build of smallrye, there the test does work.

**Comment by jmartisk** [comment]
There have been some changes in smallrye that aren't applied in Quarkus yet: you need this PR to make the test suite pass https://github.com/quarkusio/quarkus/pull/35735

**Comment by robp94** [comment]
thx.
