### ISSUE TITLE
Maven plugin

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#191]
Request from Twitter: create a maven and gradle plugin that can generate and safe the graphql-schema on build.

**Comment by jmartisk** [comment]
Sounds like an opportunity to learn writing Maven plugins! If you don't mind I'd take this

**Comment by phillip-kruger** [comment]
Go for it ! We want to use the schemabuilder to build the schema from jandex, then bootstrap to get the actual graphql schema that then get stored in gen-src. Or something like that
