### ISSUE TITLE
typesafe client - support for @OidcClientFilter

### ISSUE THREAD

**Issue by rmanig** [smallrye/smallrye-graphql#1915]
Hi there!
I would like to use the typesafe client in combination with oidc tokens. The current static options to set and use an (authorization) header seem to be too limited for the temporary short-lived access tokens.

Are there any plans to support the io.quarkus.oidc.client.filter.OidcClientFilter for example? Which would handle token refreshing as well.
```java
@GraphQLClientApi (configKey = "foo")
@OidcClientFilter ("foo")
public interface FooApi {
   //...
}
``` 
I'm aware of the option to programmatically build an typesafe graphql client, but then I'm losing all the advantages of cdi and `@GraphQLClientApi`. Furthermore, one would need to initialize a new instance of the client for every request.
The other possibility to pass an header as argument with `@Header` on each method call doesn't feel like a clean approach either.

Maybe there is another workaround I'm not aware of? 
Thanks in advance!

**Comment by t1** [comment]
You could also annotate the interface as, e.g., `@Header(name = "Authorization", method = "my.package.MyAuthentication.bearerAuthHeader")` and implement that public no-args method to return the current `BEARER <token>` string.

The `@OidcClientFilter` annotation may be more elegant, though. But it would require some changes to add the support and would only work in Quarkus, IIUC.

**Comment by jmartisk** [comment]
Quarkus supports `@OidcClientFilter` on MP Rest clients, and they are indeed implemented as a filter using the REST client API. GraphQL clients don't make use of the REST client API, so this wouldn't really be a filter (the annotation name would get a bit confusing) and would need to have some different way to plug in the header. In any case, this would mostly be a Quarkus-side issue, could you file an issue in the Quarkus repo instead? We have some more people knowledgeable in Quarkus security mechanisms there.

**Comment by rmanig** [comment]
> You could also annotate the interface as, e.g., `@Header(name = "Authorization", method = "my.package.MyAuthentication.bearerAuthHeader")` and implement that public no-args method to return the current `BEARER <token>` string.

Sadly that method is expected to be static. Usually you want to inject the oidc client/token with CDI.
Some kind of callback method in a non-static context would be perfect.

@jmartisk Thanks, I will try that!

**Comment by jmartisk** [comment]
> Sadly that method is expected to be static. Usually you want to inject the oidc client/token with CDI.

I guess you can still inject it programmatically using `CDI.current().select()`

**Comment by jmartisk** [comment]
I'm closing this as we now have a Quarkus issue, to prevent spreading the discussion too wide
