### ISSUE TITLE
Support groups by typesafe client

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#1942]
It's not clear whether (or how) you can use a typesafe client to call operations that are part of a group (and thus wrapped in one extra GraphQL field). Find out what is the best way to achieve this, implement if it's not yet possible, and add it into the documentation as well.

**Comment by jmartisk** [comment]
@t1 are you perhaps aware of a way to do it with the current impl?

**Comment by t1** [comment]
I must admit that I'm not sure, what a group actually is.

**Comment by jmartisk** [comment]
Yeah we don't really have documentation for it, that's why I also reported https://github.com/smallrye/smallrye-graphql/issues/1941 :D the server side feature is about having multiple GraphQLApis ("groups") in an application and basically wrapping each of them into an additional graphql field to create a split between them on the schema level - rather than just flattening the lists of operations and exposing them normally.  So the client also needs to be able to tell that an operation is wrapped in an additional field

**Comment by phillip-kruger** [comment]
There was a reason we did not document it.... we don't thing it should be used .... it was added experimentally, but ended up being not a great idea....

**Comment by jmartisk** [comment]
Ah, ok that's good to know. So you think supporting it by the client isn't necessary?

**Comment by jmartisk** [comment]
(Talking typesafe here... Dynamic client obviously supports it, you just need to add the field in the request)

**Comment by t1** [comment]
Oh, now I remember. It would be easy to support that on the (typesafe) client side, too: Simply let your request return a wrapping type. As you then generally need to pass parameters to the queries within the group, you'll have to use `@NestedParameter`.
