### ISSUE TITLE
Updating Federation directives

### ISSUE THREAD

**Issue by RoKKim** [smallrye/smallrye-graphql#2009]
Since the last update to the Federation directives in SmallRye GraphQL, I have identified some changes that are not yet implemented (based on [definitions_fed2_5.graphqls](https://github.com/apollographql/federation-jvm/blob/main/graphql-java-support/src/main/resources/definitions_fed2_5.graphqls)):

1. The `@shareable` directive is now repeatable:
    ```graphql
    directive @shareable repeatable on FIELD_DEFINITION | OBJECT
    ```
2. The `@key` directive now has a `resolvable` argument, with a default value of true:
    ```graphql
    directive @key(fields: FieldSet!, resolvable: Boolean = true) repeatable on OBJECT | INTERFACE
    ```
3. New directives `@authenticated` and `@requiresScopes` have been added:
    ```graphql
    directive @authenticated on
        ENUM
      | FIELD_DEFINITION
      | INTERFACE
      | OBJECT
      | SCALAR
    
    directive @requiresScopes(scopes: [[Scope!]!]!) on
        ENUM
      | FIELD_DEFINITION
      | INTERFACE
      | OBJECT
      | SCALAR
    
    scalar Scope
    ```

I am also wondering if there is a specific reason for keeping the `federation-graphql-java-support` library at `2.1.1` version. I upgraded it to `4.3.0`, as the support for the above changes was added between these versions.

I have opened up a pull request #2010 with the changes so far. Here are my notes and questions:
1. `@authenticated`:
I have implemented the directive and tested it; the schema successfully generates:
    ```java
    @Authenticated
    public record Product(
    ...
    )
    ```
    ```graphql
    type Product @authenticated {
    ...
    }
    ```
2. `@key`:
I have added the `resolvable` argument to the directive.
Since the default value of argument `resolvable` is true, I modified the `io.smallrye.graphql.bootstrap.Bootstrap#createGraphQLDirectiveType` and `io.smallrye.graphql.bootstrap.Bootstrap#createGraphQLDirectiveFrom` methods to call `graphql.schema.GraphQLArgument.Builder#defaultValueProgrammatic` for each argument with the `@DefaultValue` annotation.
Currenty, the `createGraphQLDirectiveFrom` method will only adds arguments that are directly applied. For example, if we have:
    ```java
    @Key(fields = "id")
    public record Inventory(
    ```
    In the `createGraphQLDirectiveFrom` method, only `fields` argument will get added, while the directive definition contains `resolvable` as well. Should we also add all the argument defined in `directiveType.argumentNames()` if they have the default value?
    I handeled this with the following code:
    https://github.com/smallrye/smallrye-graphql/pull/2010/files#diff-3de1c8e86a52a96e30384e8fdc4cd85b3f0526c456ef2158c9220ff6b5ec2fdeR697

3. `@requiresScopes`
The directive is defined as follows:
    ```graphql
    directive @requiresScopes(scopes: [[Scope!]!]!) on
        ENUM
      | FIELD_DEFINITION
      | INTERFACE
      | OBJECT
      | SCALAR
    ```
    The challenge I'm facing is handling the argument `scopes: [[Scope!]!]!`, since we cannot have `String[][] scopes();` in Java interface.  Do you have any suggestions on how to address this?

**Comment by jmartisk** [comment]
Thanks so much for working on this! I'm adding some comments to your PRs, let's continue the discussion there

**Comment by RoKKim** [comment]
`@link` directive added in #2040.
