### ISSUE TITLE
Opt-in possibility to exclude nulls in responses

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#2042]
Add a configuration option so that, when it's enabled, `null` fields are excluded from the serialized responses. This is against the GraphQL spec, but it might be useful in some specific cases (minimizing network traffic when there's a lot of nulls in responses) and thus this has feature to be disabled by default.

We also need to make sure we only skip `null` fields when the respective field was successfully resolved to `null`, as opposed to when the field has an error - for fields with errors, the respective `null` in the `data` section of the response should still be there

**Comment by mbechto** [comment]
> This is against the GraphQL spec, but it might be useful in some specific cases

@jmartisk can you point me to the spec you are referring to? I had a look at section 7 in https://spec.graphql.org/October2021/ but didn't find any explicit information about null vs. omitted fields.

**Comment by jmartisk** [comment]
Anyway @mskacelik is looking into implementing this as an opt-in feature
