### ISSUE TITLE
Federation & schema: `FieldSet!` should be `_FieldSet!`

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#2065]
After updating to version 2.8.0, I get an error from (the admittedly old version of) Apollo:

`Invalid definition for directive "@key": argument "fields" should have type "_FieldSet!" but found type "FieldSet!"`

**Comment by jmartisk** [comment]
I don't know much about it, but the Apollo docs say it should be `FieldSet!`: https://www.apollographql.com/docs/federation/federated-types/federated-directives/#key
Maybe @RoKKim could comment :)

**Comment by RoKKim** [comment]
Could you point me to the full error log? Also, it seems that `_FieldSet!` was changed to `FieldSet!` with the version 2.0 of the Apollo Federation specification:

- https://github.com/apollographql/federation/commit/ce9f1e40758e9adf4ea62f11f6eda4b348a5deeb
- https://www.apollographql.com/docs/federation/v1/federation-spec/#scalar-_fieldset

Currently, we implement `FieldSet!`, which is according to the specification:
https://www.apollographql.com/docs/federation/federated-types/federated-directives/#key
And it can be seen in the generated schema definition:
```graphql
directive @key(fields: FieldSet!, resolvable: Boolean = true) repeatable on OBJECT | INTERFACE
scalar FieldSet
```

**Comment by t1** [comment]
> Could you point me to the full error log?

https://github.com/t1/smallrye-graphql-federation-demo/actions/runs/8293254696/job/22695999962#step:6:386

> it seems that _FieldSet! was changed to FieldSet! with the version 2.0 of the Apollo Federation specification

That sounds plausible, as I'm using an old version of Apollo for this demo. I need to find a good way to run a newer version that supports 2.0. I've been hesitating to make that move until now, because IIUC it means that the services have to register with the Gateway. How do you do that, @RoKKim?

**Comment by RoKKim** [comment]
The error is thrown from the `@apollo/gateway` library. If I had to guess, you would need to upgrade your [package.json](https://github.com/t1/smallrye-graphql-federation-demo/blob/main/gateway/package.json) according to the official documentation:
https://www.apollographql.com/docs/federation/federation-2/moving-to-federation-2/

I tested the SmallRye implementation in my demo project with the following versions:
```json
"@apollo/gateway": "^2.7.1",
"@apollo/server": "^4.10.0",
```

**Comment by t1** [comment]
I had assumed that I needed to go away from preregistering the subgraph endpoints, but that's obviously still possible and easier for the demo. So I've tried to update the Apollo Server and Gateway as good as I could. But it still fails with the same error:

[`Invalid definition for directive "@key": argument "fields" should have type "_FieldSet!" but found type "FieldSet!"`](https://github.com/t1/smallrye-graphql-federation-demo/actions/runs/8322500345/job/22770406948#step:6:391)

I understand that the newer Apollo stack is backward compatible with Federation v1. Then it shouldn't be complaining about the old directives and types, should it?

**Comment by vitomanu96** [comment]
Hi, same issue here.

Rover version: 0.23
Apollo Router: 1.48
Federation version (supergraph config): 2.7.8

If I change FieldSet! to _FieldSet! manually in my schema.graphql evetythings works fine (or if i disable federation)

How can I address this problem?

@t1 did you find a workaround?

**Comment by t1** [comment]
Actually, I switched to [wundergraph](https://wundergraph.com)...... not only because of this.

**Comment by kartomic8** [comment]
@vitomanu96 : probably way to late, but make sure your schema has a link directive to the appropriate federation version on your schema declaration.  Small rye doesn't add this in its generated schemas (at least I haven't been able to get it to do so with the gradle plugin)

[Source](https://www.apollographql.com/docs/graphos/reference/federation/directives)
