### ISSUE TITLE
 The graphql client no longer allows you to define the 'Input' name type on dto classes (Quarkus 3.9.1)

### ISSUE THREAD

**Issue by ITrium-Salah** [smallrye/smallrye-graphql#2071]
With quarkus 3.8 i was able to set the input type of dto object when using the graphql typesafe client.
```
@Input("MessageInput")
public class MessageDto{
 ...
}
```

Unfortunetly the latest version my code throw the exception:
`Index did not contain annotation definition input`

Is there a way to force the name of the input so as not to have to rename all of my DTOs?

**Comment by jmartisk** [comment]
I'm assigning this to @mskacelik , this is probably a bug because we need to add this annotation into the index, which we currently don't. 
As a temporary workaround until we fix it, you might use `quarkus.smallrye-graphql-client.enable-build-time-scanning=false`, that should fix it I think (but we're going to remove this property in the future)

**Comment by ITrium-Salah** [comment]
> I'm assigning this to @mskacelik , this is probably a bug because we need to add this annotation into the index, which we currently don't. As a temporary workaround until we fix it, you might use `quarkus.smallrye-graphql-client.enable-build-time-scanning=false`, that should fix it I think (but we're going to remove this property in the future)

Ok thank you i will try the configuration property and watch the status of this issue for a sustainable solution

**Comment by mskacelik** [comment]
Quarkus does not initialize `Input.class` into the index. That should be an easy fix, but I'd like to know why the other MP annotations are indexed.

**Comment by mskacelik** [comment]
https://github.com/quarkusio/quarkus/pull/39857

**Comment by jmartisk** [comment]
Fixed via https://github.com/quarkusio/quarkus/pull/39857, should be resolved in Quarkus 3.9.3 and 3.10.0 (after they are released)
