### ISSUE TITLE
Can't figure out how to use the graphql-java extended scalars Object and JSON

### ISSUE THREAD

**Issue by va1erian** [smallrye/smallrye-graphql#2091]
Hi,
We have some fields in our model that are key value mappings whose shape cannot be known in advance, which seems a perfect match for the "Object" and "JSON" scalar provided by the graphql-java extended scalar project https://github.com/graphql-java/graphql-java-extended-scalars

Unfortunately i can't figure out how to use them withh smallrye-graphql. I tried in an observer to register the object scalar on the schema builder  but I get an error saying an object type already exists. Registering the JSON scalar works but don't know how to tell smallrye-graphql to map an existing type to this scalar.

Any pointers?

**Comment by jmartisk** [comment]
No pointers, this is simply not implemented yet. We've had some unsuccessful attempts to do it as far as I remember, but never succeeded. If you want to try to be the one who can get it working, you're welcome :)

**Comment by jmartisk** [comment]
see also https://github.com/smallrye/smallrye-graphql/issues/1776

**Comment by t1** [comment]
duplicate
