### ISSUE TITLE
Extract metric naming strategy into a manageable piece

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#217]
At the moment we "duplicate" the metric naming strategy (logic that transforms an operation/field into its respective metric name) 
- in the `Bootstrap` class where it is used for eager registration of metrics during bootstrap
- in the `MetricDecorator` class where it is used to access and update metrics

It perhaps should be factored out into one place so it will be more manageable. Integration code that binds SmallRye GraphQL into runtimes could make use of it too, if it wants to access the metrics for some reason, it should not be forced to "guess" how to compute the metric names, but should have a reliable API to compute them.

**Comment by phillip-kruger** [comment]
Sounds good :) I am assigning you ;)
