### ISSUE TITLE
Custom experimental TCK tests (server side) do not execute

### ISSUE THREAD

**Issue by mskacelik** [smallrye/smallrye-graphql#2212]
The tests placed at https://github.com/smallrye/smallrye-graphql/tree/main/server/tck stopped being executed despite being once in the past.

**Comment by mskacelik** [comment]
gonna look into it

**Comment by mskacelik** [comment]
The commit 68ed192e4eb2ea73b16ba8f972bd64df8161f085 seems to be the cause of the problem.

**Comment by jmartisk** [comment]
fixed by https://github.com/smallrye/smallrye-graphql/pull/2220
