### ISSUE TITLE
Typed client: force sending null value

### ISSUE THREAD

**Issue by jmini** [smallrye/smallrye-graphql#2251]
It seem that the gitlab graphql server has a very specific way of treating null.

I looked at the query created by the js graphQL client when an action (removing the due-date of a workItem) is created in the UI. It's send:

```json
{
    "input": {
        "id": "gid://gitlab/WorkItem/18672",
        "rolledupDatesWidget": {
            "dueDateIsFixed": true,
            "startDateIsFixed": true,
            "dueDateFixed": null,
            "startDateFixed": null
        }
    }
}
```

I was able to reproduce it in graphiQL https://gitlab.com/-/graphql-explorer

<img width="657" alt="Screenshot 2024-12-20 at 09 39 14" src="https://github.com/user-attachments/assets/a8423710-891e-4a52-9619-a95b6a248146" />

Corresponding java code:

```java
WorkItemUpdateInput request = new WorkItemUpdateInput()
        .setId(workItem.getId())
        .setRolledupDatesWidget(new WorkItemWidgetRolledupDatesInput()
                .setDueDateFixed(null)
                .setDueDateIsFixed(true)
                .setStartDateFixed(null)
                .setStartDateIsFixed(true) //
        ) //
;
WorkItemUpdatePayload updateResponse = api.workItemUpdate(request);
```

Library is here: https://github.com/unblu/gitlab-workitem-graphql-client

But this is turned by the typed-client to this request:

```
{"arg0":{"id":"gid://gitlab/WorkItem/18672","rolledupDatesWidget":{"startDateIsFixed":true,"dueDateIsFixed":true}}}
```

The `null` values are not sent, and it seem that this is interpreted differently by the server.

If change graphiQL to:

```json
{
    "input": {
        "id": "gid://gitlab/WorkItem/18672",
        "rolledupDatesWidget": {
            "dueDateIsFixed": true,
            "startDateIsFixed": true
        }
    }
}
```

As with the java typed client, no change is performed by the server.

---

Is it a way to force the GraphQL client to set the `null` values?

**Comment by jmini** [comment]
I somehow need to set something like:

```java
JsonbConfig config = new JsonbConfig()
  .withNullValues(true)
```

**Comment by jmartisk** [comment]
Yeah could you try to register a custom `JsonbConfig` like we do for example in this test:

- https://github.com/smallrye/smallrye-graphql/blob/main/server/integration-tests/src/test/java/io/smallrye/graphql/tests/json/CustomJsonbService.java#L21
- https://github.com/smallrye/smallrye-graphql/blob/main/server/integration-tests/src/test/java/io/smallrye/graphql/tests/json/CustomJsonbConfigTestCase.java#L29

Also see the documentation: https://smallrye.io/smallrye-graphql/2.11.0/custom-json-serializers-deserializers/

And let me know if this works (I hope it will)

**Comment by jmini** [comment]
I was exactly looking at those, but they are server-side features.
So I am not sure (yet) how to do this at client side 🤔

**Comment by jmartisk** [comment]
Ah, sorry! I guess my brain was turned off.

I think we don't have explicit control over this on the client, but I vaguely remember we had a debate that when you use a `record` instead of a class, then its null fields will be included. Maybe you could  try that, but otherwise, this is something that we would have to implement (maybe a configuration property)

**Comment by jmini** [comment]
I have change the class [WorkItemWidgetRolledupDatesInput](https://github.com/unblu/gitlab-workitem-graphql-client/blob/b3f64ddcb8ddf789fcca6747445b991b9ed69e7d/src/main/java/graphql/gitlab/model/WorkItemWidgetRolledupDatesInput.java) to a record:

```java
package graphql.gitlab.model;

import org.eclipse.microprofile.graphql.Name;

@Name("WorkItemWidgetRolledupDatesInput")
public record WorkItemWidgetRolledupDatesInput(Date startDateFixed, Boolean startDateIsFixed, Date dueDateFixed, Boolean dueDateIsFixed) {
}
```

And the query to:

```java
WorkItemUpdateInput request = new WorkItemUpdateInput()
        .setId(workItem.getId())
        .setRolledupDatesWidget(
                new WorkItemWidgetRolledupDatesInput(null, true, null, true) //
        );
WorkItemUpdatePayload updateResponse = api.workItemUpdate(request);
```

And it does not seems to have any impact (which I think makes sense).

---

_Side not on the usage of records:_

The mutation query we formulate now with classes (using a builder pattern and chain-able setters) is quite convenient.

* It is close to the json that can be written in a tool like graphiQL
* Now we we have divided our code in multiple methods making some contributions to the builder

So I don't think I would like to use records for my graphQL queries.

**Comment by jmini** [comment]
I think I found it:
https://github.com/smallrye/smallrye-graphql/blob/c7908478342656cb47ff6f383917a9f158167fe6/client/implementation-vertx/src/main/java/io/smallrye/graphql/client/vertx/typesafe/VertxTypesafeGraphQLClientProxy.java#L448-L455

And:
https://github.com/smallrye/smallrye-graphql/blob/c7908478342656cb47ff6f383917a9f158167fe6/client/implementation/src/main/java/io/smallrye/graphql/client/impl/typesafe/reflection/FieldInfo.java#L29-L33

So the solution is:

```java
public class WorkItemWidgetRolledupDatesInput {

    /**
     * Fixed start date for the work item.
     */
    @JsonbProperty(value = "startDateFixed", nillable = true)
    private Date startDateFixed;
    /**
     * When start_date_fixed is not provided it defaults to `false`.
     */
    private Boolean startDateIsFixed;
    /**
     * Fixed due date for the work item.
     */
    @JsonbProperty(value = "dueDateFixed", nillable = true)
    private Date dueDateFixed;
    /**
     * When due_date_fixed is not provided it defaults to `false`.
     */
    private Boolean dueDateIsFixed;
    
    // ...
```

**Comment by jmini** [comment]
@jmartisk thank you very much for your help

**Comment by jmartisk** [comment]
Ah, good catch, I'd forgotten about that! Ok, glad that it's resolved.

**Comment by jmini** [comment]
I just saw that the `nillable = true` attribute is replaced by `@JsonbNillable`

See: https://jakarta.ee/specifications/jsonb/3.0/apidocs/jakarta.json.bind/jakarta/json/bind/annotation/jsonbproperty#nillable()

So I guess a follow up issue/PR to fix `FieldInfo` is needed.

**Comment by jmartisk** [comment]
Feel free to send a PR :)

**Comment by jmini** [comment]
See https://github.com/smallrye/smallrye-graphql/issues/2253 for support of `@JsonbNillable`
