### ISSUE TITLE
Config to enable/disable introspection

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#252]
See https://lab.wallarm.com/why-and-how-to-disable-introspection-query-for-graphql-apis/

We need to disable/enable the schema and introspection using config

**Comment by ybroeker** [comment]
Unlike `NoIntrospectionGraphqlFieldVisibility.NO_INTROSPECTION_FIELD_VISIBILITY` shown in the post, I would allow `__typename`. This doesn't expose much information, but is quite useful for interfaces/unions.

**Comment by phillip-kruger** [comment]
Maybe we can make our own levels, Off, typename_only, On.

Or something like that

W.d.y.t ?
