### ISSUE TITLE
Bug: API Objects with a Single Scalar Field Are Interpreted As Scalars

### ISSUE THREAD

**Issue by sherl0cks** [smallrye/smallrye-graphql#270]
This may be related to the use of Kotlin data classes in my code.

For the following API and model
```
@GraphQlClientApi(endpoint = "https://api.com/graphql")
interface Client {
    fun query(foo : String): Response
}

data class Project( var apiObject : ApiObject)

data class ApiObject(
    var id: String = "",
    var name: String = "" // This second field must be added or graphql client thinks that `Project` is a `String` due to its "scalar constructor"
) 

```

In this case, if `ApiObject` only has `id`, graphql request with be `apiObject`, instead of `apiObject{ id }`. Adding a second field will result in `apiObject{ id name }`

Seems caused by this chain: https://github.com/smallrye/smallrye-graphql/blob/a9f73137977d09ea325c762dc6899f1edf7d4bb8/client/implementation/src/main/java/io/smallrye/graphql/client/typesafe/impl/GraphQlClientProxy.java#L86

https://github.com/smallrye/smallrye-graphql/blob/a9f73137977d09ea325c762dc6899f1edf7d4bb8/client/implementation/src/main/java/io/smallrye/graphql/client/typesafe/impl/reflection/TypeInfo.java#L122

https://github.com/smallrye/smallrye-graphql/blob/a9f73137977d09ea325c762dc6899f1edf7d4bb8/client/implementation/src/main/java/io/smallrye/graphql/client/typesafe/impl/reflection/TypeInfo.java#L136

**Comment by phillip-kruger** [comment]
@t1 any thoughts ?

**Comment by t1** [comment]
I think this is exactly what we discussed in https://github.com/eclipse/microprofile-graphql/issues/251: a single-string constructor is currently considered as defining a custom wrapper class.

I will do a change for that case in the client.

**Comment by phillip-kruger** [comment]
Yea this was my worry in applying that by default. I think we need to apply this with some annotation so that it's a more explicit decision from the user.
