### ISSUE TITLE
smallrye-graphql-gradle-plugin not published on Gradle Plugin Portal

### ISSUE THREAD

**Issue by marceloverdijk** [smallrye/smallrye-graphql#278]
Hi @phillip-kruger 

It seems the `smallrye-graphql-gradle-plugin` jar is not published on maven central.
Do you know if the `exec-maven-plugin` inside the pom was executed? 
Maybe something else is needed as well... it's a bit complicated as to create a Gradle plugin jar you have to use Gradle ;-)

See: https://repo1.maven.org/maven2/io/smallrye/smallrye-graphql-gradle-plugin/1.0.3/
(it only contains the pom, not the jar)

Looking further we might also think about publishing the plugin to the Gradle Plugin Portal.

**Comment by marceloverdijk** [comment]
PS: I had locally a `smallrye-graphql-gradle-plugin` `1.0.2` in my m2 repo and that one works as expected. Also in combination with the Quarkus GraphQL integration part of Quarkus 1.5.0 👍

**Comment by jmartisk** [comment]
Hmm. Perhaps it is because the gradle plugin project declares its packaging to be `pom` and it should be `jar`?
https://github.com/smallrye/smallrye-graphql/blob/1.0.3/tools/gradle-plugin/pom.xml#L15

**Comment by jmartisk** [comment]
https://github.com/smallrye/smallrye-graphql/blob/1.0.3/tools/gradle-plugin/pom.xml#L122 This could also be part of the problem?

**Comment by marceloverdijk** [comment]
Yes that could be.

When setting it up I already some doubts this would work the first time ;-).
The pom setup is based on Quarkus as they also have Maven build with a Gradle plugin project.
Note they also skip deploying the project but a bit different: https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/pom.xml#L124-L133

Maybe we could ask @gsmet or @gastaldi  from the Quarkus team for advise?

**Comment by gastaldi** [comment]
@marceloverdijk right, that depends if you're using the `nexus-staging-plugin` in the release. The trick in Quarkus is that we run `gradle publishPlugin` after the release is performed (to deploy to the Gradle Plugin portal), so it makes little sense to deploy it to maven central. 

On a side note, I have a feeling that the `build-helper-maven-plugin` is useless here too (I'll look into removing it from the quarkus gradle plugin's pom.xml)

**Comment by marceloverdijk** [comment]
thx @gastaldi , maybe `smallrye-graphql` can take the same approach @jmartisk  @phillip-kruger? That way we would also have the plugin to the Gradle Plugin Portal.

**Comment by phillip-kruger** [comment]
Sounds good to me. Our CI build and release is in .github folder as we are using GitHub actions. So maybe see if you can fix it there ?

**Comment by marceloverdijk** [comment]
@phillip-kruger thx for merging the PR. what do you think about creating the Gradle Plugin Portal account?

**Comment by phillip-kruger** [comment]
Hi @marceloverdijk. Yes let me check with @kenfinnigan and/or @radcortez .

**Comment by phillip-kruger** [comment]
@marceloverdijk The gradle key and secret is now available in GH Secret:

GRADLE_PUBLISH_KEY
GRADLE_PUBLISH_SECRET

That should do it right ?

**Comment by marceloverdijk** [comment]
I think we need to do:

- Updating `gradle.properties` automatically after the `release:prepare` goal as @jmartisk mentioned: https://github.com/smallrye/smallrye-graphql/pull/279#issuecomment-638847917
- And the running `gradle publishPlugins -Pgradle.publish.key=<key> -Pgradle.publish.secret=<secret>` as build step

and then hope it works :-D

**Comment by phillip-kruger** [comment]
Hi @marceloverdijk - are you planning to make the changes above ?

**Comment by marceloverdijk** [comment]
Hi @phillip-kruger I’m leaving on holiday tomorrow so it will be at least after my holidays...

**Comment by phillip-kruger** [comment]
Cool ! Enjoy your time off :)

**Comment by zandaleph** [comment]
Is this plugin published?  I tried following the instructions in the README and the plugin wasn't found, ultimately trying to resolve my problem led to this still-open issue.  I don't see any release logic in the github actions, so it's hard to tell if the release logic got built somewhere else.

**Comment by bitkill** [comment]
I'm trying to use this plugin and not being successful importing it.
(gradle kts)
```kt
plugins {
    java
    id("io.quarkus")
    id("io.smallrye.graphql")
}
```

**Comment by bitkill** [comment]
@jmartisk opened a PR to fix this, there is still some work needed to to this in the GH Actions, but this should be a good start.
PR: https://github.com/smallrye/smallrye-graphql/pull/1351

**Comment by jmartisk** [comment]
This has been resolved for some time (see https://plugins.gradle.org/plugin/io.smallrye.graphql), so I'll close it
