### ISSUE TITLE
Add ability for users to add error code and other extensions

### ISSUE THREAD

**Issue by nandorholozsnyak** [smallrye/smallrye-graphql#282]
Hello there,

I'm a new person to GraphQL but in the last few days I was experimenting with it within the Quarkus framework, and I'm liking it so far. 
When it comes to writing code sometimes error can occur and I like to specify the error via error codes or with reasons which are straightforward and can be consumed easily by the caller. 
In the official GraphQL specification there are a few section about errors and one of them is specifying how the programmers could define "custom" error codes in their responses. Take a look at here:
https://spec.graphql.org/June2018/#example-fce18

So what I see there if the programmer would like to indicate any kind of custom behavior in the error response they just have to put this information into the `extension ` section in a key-value format. Easy. 
The problem with that in the SmallRye implementation this kind of stuff is not working properly (yet). 

An example:
I have a GraphQL API like the following:
```
@GraphQLApi
public class PackageResource {

    @Query("getPackages")
    @Description("Returns all available packages")
    public List<Package> getPackages() {
        throw GraphqlErrorException.newErrorException()
                .message("Something went wrong")
                .extensions(Map.of("code","CUSTOM_ERROR_CODE"))
                .build();
    }

}
```
I found the `GraphqlErrorException` class and it looks fine, because it has an `extensions` variable in it and it can be populated, so far so good, btw this class is coming from the `com.graphql-java:graphql-java:14.0` dependency right now.
So when this exception is being thrown it will be handled by the `io.smallrye.graphql.execution.error.ExceptionHandler` where it will be wrapped as a `io.smallrye.graphql.execution.error.GraphQLExceptionWhileDataFetching` exception which calls it's super class constructor `graphql.ExceptionWhileDataFetching` and it sets any kind of incoming extensions in it.
```
public ExceptionWhileDataFetching(ExecutionPath path, Throwable exception, SourceLocation sourceLocation) {
        this.path = assertNotNull(path).toList();
        this.exception = assertNotNull(exception);
        this.locations = Collections.singletonList(sourceLocation);
        this.extensions = mkExtensions(exception);
        this.message = mkMessage(path, exception);
    }
```
At this point if a newly created exception is containing extra extensions then it will be populated there. The problems comes when this exception is being serialized by the `io.smallrye.graphql.execution.error.ExecutionErrorsService#toJsonError` method.
It basically "replaces" or just simply ignores the content of the `extensions` field.
`io.smallrye.graphql.execution.error.ExecutionErrorsService#getDataFetchingExtensions`
```
    private Optional<JsonObject> getDataFetchingExtensions(ExceptionWhileDataFetching error) {
        Throwable exception = error.getException();

        JsonObjectBuilder objectBuilder = jsonBuilderFactory.createObjectBuilder();

        addKeyValue(objectBuilder, EXCEPTION, exception.getClass().getName());
        addKeyValue(objectBuilder, CLASSIFICATION, error.getErrorType().toString());

        return Optional.of(objectBuilder.build());
    }
```
So my question is the following, is there any way to populate the response with the values in the `extensions` field within the `ExceptionWhileDataFetching` exception?
If there is no specific reason for ignoring the custom values then I think a change could be made to the `getDataFetchingExtensions` method, if there is a specific reason for ignoring them, then please ignore this issue ticket :)

**Comment by phillip-kruger** [comment]
Hi @nandorholozsnyak . Thanks for the detailed issue ! 
So I think there is two issues here:
1) We should not ignore the extensions if it's already populated when using a graphql-java exception (or any other exception with that field maybe ?) is used. There is no reason for ignoring them.
2) We need a way to allow developers to add to the extension map (without having to use a exception class that contain an extension field.

Both of these issues should be handled in the spec, but we can fix it here in the mean time.

**Comment by nandorholozsnyak** [comment]
Hi @phillip-kruger, thanks for the fast reply :) 

> We should not ignore the extensions if it's already populated when using a graphql-java exception (or any other exception with that field maybe ?) is used. There is no reason for ignoring them.

I have already made some changes to the `io.smallrye.graphql.execution.error.ExecutionErrorsService` which handles all these extra, developer populated extensions. Right now it is working well, but still miss a few unit tests.
`ExceptionWhileDataFetching` class has an `exception` field with`Throwable` type which could be tested against the `GraphqlErrorException` class, because it stores the map of extensions.

> We need a way to allow developers to add to the extension map (without having to use a exception class that contain an extension field.

I think custom exceptions could be derived from `graphql.GraphqlErrorException` because it has the extensions field and it can be populated, but it is just a tip from me :D 

If I had time I would take a closer look on them the quick fix basically looks like this.

```
    private Optional<JsonObject> getDataFetchingExtensions(ExceptionWhileDataFetching error) {
        Throwable exception = error.getException();

        JsonObjectBuilder objectBuilder = jsonBuilderFactory.createObjectBuilder();

        addKeyValue(objectBuilder, EXCEPTION, exception.getClass().getName());
        addKeyValue(objectBuilder, CLASSIFICATION, error.getErrorType().toString());
        Map<String, Object> extensions = error.getExtensions();
        populateCustomExtensions(objectBuilder, extensions);

        return Optional.of(objectBuilder.build());
    }

    private void populateCustomExtensions(JsonObjectBuilder objectBuilder, Map<String, Object> extensions) {
        if (Objects.nonNull(extensions)) {
            for (Map.Entry<String, Object> entry : extensions.entrySet()) {
                addKeyValue(objectBuilder, entry.getKey(), entry.getValue().toString());
            }
        }
    }
```
and with that the extensions map in the response will be populated well.
![image](https://user-images.githubusercontent.com/11406183/83966681-dbe83380-a8bb-11ea-8ef0-c83ded4e8dea.png)
I will fork the repo and try to push it after I finished with some testing :)

**Comment by nandorholozsnyak** [comment]
Another question if it can be connected with this other issue https://github.com/smallrye/smallrye-graphql/issues/167?

**Comment by phillip-kruger** [comment]
> I think custom exceptions could be derived from graphql.GraphqlErrorException because it has the extensions field and it can be populated, but it is just a tip from me :D

We should not expose the implementation details to the boundary (that would mean our abstraction has failed) so the solution can not be use the underlying graphql-exception (as that is just the current implementation details).

We can however look at any exception and see if there is an extension field, and if so, use it. That would mean that the current graphql-java exception should work, but also a user's own exception class. 

We can also consider some annotation that can be placed on a method that throws an exception, something like: 

```
@ExceptionExtension(key="someKey", value="someValue")
public SuperHero getSuperHero(String name) throws SomeException{

}
```
That exception can maybe also allowed on the exception class level in the case that it's a custom exception.

**Comment by phillip-kruger** [comment]
If the case is that the data in the extension (like the code) needs to be dynamic (so an value in an annotation will not work) we can consider a RequestScoped Object that can be injected anywhere and be populated. This might be the easiest solution that can be done in SamllRye, and if it works we can propose it to the spec.

So we have an Object called lets say `@CustomExceptionExtensions` that you can add key-value pairs to.

If an exception happens the values from there are added to the exception. W.d.y.t ?

**Comment by nandorholozsnyak** [comment]
Hm good ideas.
I was wondering if we would be able to produce an annotation which can be put on the fields of a custom exception then with this annotation the key of the extension could be derived.
Like this (if you were talking about this one then it's fine :D)

```
@Target(ElementType.FIELD)
@interface ErrorExtension {
    String value();
}

enum ErrorCode {

    ENTITY_NOT_FOUND

}

class CustomException extends RuntimeException {

    @ErrorExtension("errorCode")
    private ErrorCode errorCode;

}
```

**Comment by t1** [comment]
Awesome idea! I would like to go even a step further: there would be a big benefit, if there was a standard extension field for error codes. If `code` is the name of that extension commonly used in the GraphQL community, we should make it as easy as by any means possible to set in MP GraphQL:

```java
class EntityNotFoundException extends RuntimeException {
}
```

The code could be derived directly from the simple class name!

If that is not what we want, we could specify the code explicitly:

```java
@GraphQlErrorCode("ENTITY_NOT_FOUND")
class CustomException extends RuntimeException {
}
```

... or on a method if it needs to be dynamic:

```java
class CustomException extends RuntimeException {
    @GraphQlErrorCode
    public String errorCode() {
        return "ENTITY_NOT_FOUND";
    }
}
```

... or on a field:

```java
class CustomException extends RuntimeException {
    @GraphQlErrorCode
    private final String errorCode;

    // constructor
}
```

Any type could be used (esp. an enum), and it would be mapped to a string. I think it would only be extra work for clients to sometimes have other types, e.g. a numeric 404 in some cases... let's stick to string.

On the client side, it would be ideal if the error code would be mapped back to an exception, but there are a number of open questions. We should discuss this in #167.

For REST services there's a standard [rfc-7807](https://tools.ietf.org/html/rfc7807) that uses `type` instead of `code`, but it means the same thing: a permanent code to identify the type of error. They suggest to use an URI for the error type, so we could use a URL to the documentation of the code. But that's RESTful thinking ;-) It's actually not easy to have absolutely stable URLs, so it may be better to have a separate URL extension field for the documentation URL; it's a separate concern after all.

There are other very useful things specified in rfc-7807 that we could use as well, but the `code` is by far the most important one. Let's start with that and continue from there.

**Comment by phillip-kruger** [comment]
Sounds good to me. I think we need both, code and a generic way to add any key-value.

**Comment by nandorholozsnyak-tis** [comment]
I started to make some changes based on @t1 wrote, it looks cool. I'm not sure what kind of "tool" is okay for that, is it okay to use Jandex for accessing the fields of the exception classes or pure reflection should be used?

**Comment by nandorholozsnyak** [comment]
I started to make some changes based on @t1  wrote, it looks cool. I'm not sure what kind of "tool" is okay for that, is it okay to use Jandex for accessing the fields of the exception classes or pure reflection should be used?

**Comment by phillip-kruger** [comment]
You should use Janex, but only in the Schema model, so you might need to update the model. Then you can use the model to get the info.

**Comment by t1** [comment]
> I started to make some changes

Cool. If you make a pull request, we can give some feedback :-)

**Comment by nandorholozsnyak** [comment]
I opened a little pull request, it is failing and this just populates the extension map in the response with the caught exceptions extension entries. More to come when I will have some time to finish it :) I will try to experiment with the changes we have talked earlier.

**Comment by t1** [comment]
I'll work on supporting `@GraphQlErrorCode` now.

**Comment by nandorholozsnyak** [comment]
Sounds cool @t1, I'm really curious in the solutions :)

**Comment by phillip-kruger** [comment]
This is now partially fix, I create another ticket for the outstanding (see #299)
