### ISSUE TITLE
Implement all "Serving over HTTP" POST use cases

### ISSUE THREAD

**Issue by marceloverdijk** [smallrye/smallrye-graphql#304]
As described on https://graphql.org/learn/serving-over-http/ there are multiple HTTP POST use cases:

### POST request 

A standard GraphQL POST request should use the `application/json` content type, and include a JSON-encoded body of the following form:

```
{
  "query": "...",
  "operationName": "...",
  "variables": { "myVariable": "someValue", ... }
}
```

`operationName` and `variables` are optional fields. `operationName` is only required if multiple operations are present in the query.

In addition to the above, we recommend supporting two additional cases:

- If the "query" query string parameter is present (as in the GET example above), it should be parsed and handled in the same way as the HTTP GET case.

- If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

SmallRye GraphQL already supports the standard HTTP POST use case, but not the 2 additional (recommended) use cases from the spec.
Note this was also mentioned in #69 but this issue was closed without a resolution for these additional HTTP POST use cases.

**Comment by phillip-kruger** [comment]
The spec has now moved to graphql: https://github.com/graphql/graphql-over-http

**Comment by phillip-kruger** [comment]
Also need to look at https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md for Subscriptions.

**Comment by phillip-kruger** [comment]
Also look at Apolo's `Sec-WebSocket-Protocol` /cc @ethan-gallant
