### ISSUE TITLE
Allow to set http headers for /graphql request in graphql-ui GUI

### ISSUE THREAD

**Issue by velias** [smallrye/smallrye-graphql#307]
Hi, integrated graphql-ui is great, but I need to access secured endpoint. So I need to set Authorization header to be used in /graphql request. graphql-ui provided from this implementation should allow to set at least one header (defined name and value).

**Comment by phillip-kruger** [comment]
Hi @velias - Thanks for this, I was thinking for something similar just yesterday. Not sure how to best do this. Do you have any suggestions ?

**Comment by jmartisk** [comment]
We could add a HTML field that specifies value of the `Authorization` header. It's not super easy to use, because you'll need to compute the value yourself manually, but it should work for most typical security configurations

**Comment by velias** [comment]
Agree, this field should be ok for normal developer who should know how to use it

**Comment by velias** [comment]
Thinking about it further, what is expected role/use of this GUI? Is it for developers only when developing API, or should it be used in final service also?
Because if it should be used in final service also, then it should seamlessly integrate with auth mechanism used for the service itself. But it may be tricky to achieve due to high variability in this area. So eg. if Quarkus OIDC module is configured to `web-app` type, then this GUI can directly use this auth mechanism, obtain token from it and use it. But if it is `service` mode, then GUI doesn't have enough info to call SSO server, so should allow to set token manually? Not talking about other auth modes/modules or running this impl in another AS

**Comment by t1** [comment]
We could switch to the GraphiQL-based [Playground](https://github.com/prisma-labs/graphql-playground).

**Comment by phillip-kruger** [comment]
Hi @t1 - I initially looked at Playground. But then I saw this : https://github.com/prisma-labs/graphql-playground/issues/1143, so I thought I would use graphiql as all the playground stuff should show up there. I might be wrong.

**Comment by t1** [comment]
Didn't know that. But that's cool! We'll have to wait and see what happens :-)

**Comment by t1** [comment]
There seems to be not much going on in the effort to merge GraphiQL and Playground. Maybe we should switch to Playground now; and back to GraphiQL once it's merged? Both steps should be easy to do.

**Comment by t1** [comment]
BTW: GraphiQL uses the same credentials provided to load the html. This doesn't seem to work with Playground. So we provide the credential headers manually.

**Comment by phillip-kruger** [comment]
THis is now done.
