### ISSUE TITLE
Enum introspection error if field is present, it shows as enum option in GraphQL schema

### ISSUE THREAD

**Issue by velias** [smallrye/smallrye-graphql#309]
Hi, I have Java enum which contains additional field:
```
public enum Category {

    AI_MACHINE_LEARNING("AI/Machine Learning"),
    APPLICATION_RUNTIME("Application Runtime");

    private SolutionCategory(String displayName) {
        this.displayName = displayName;
    }

    private final String displayName;

    public String getDisplayName() {
        return displayName;
    }
}
```

When I look at the generated GraphQL schema, I see `displayName` as other option/value for the enum!

```
{"5":{
    "kind":"ENUM",
    "name":"Category","description":null,"fields":null,"inputFields":null,"interfaces":null,
    "enumValues":[
      {"name":"AI_MACHINE_LEARNING","description":null,"isDeprecated":false,"deprecationReason":null},
      {"name":"APPLICATION_RUNTIME","description":null,"isDeprecated":false,"deprecationReason":null},
      {"name":"displayName","description":null,"isDeprecated":false,"deprecationReason":null}
    ],
    "possibleTypes":null
  }
}
```

I believe `displayName` should be completely omited, not added as option.

It happens in Quarkus 1.5.2

**Comment by phillip-kruger** [comment]
Hi @velias - thanks for this. This is a bug. As a workaround until we fix this you can try and add `@Ignore` on the displayName field.

**Comment by velias** [comment]
Thanks Phillip. I tried `@Ignore` immediately once I found this problem, but no luck. Anyway, this is minor bug for us for now as we are in implementation phase of our project. We will not go live soon, so if this bug will be patched in reasonable time then it is ok for us.

**Comment by phillip-kruger** [comment]
Ok great. I will make sire it's fixed in the next release.

**Comment by velias** [comment]
Thanks a lot @phillip-kruger

**Comment by phillip-kruger** [comment]
Pleasure. Should be in the next release and Quarkus 1.7
