### ISSUE TITLE
Context feature

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#310]
Implement an initial version of `@Context` from https://github.com/eclipse/microprofile-graphql/issues/127

**Comment by janknobloch** [comment]
Thanks for your efforts @phillip-kruger 
Looking forward to see this in quarkus-smallrye-graphql in the future as it seems this is the only option right know to avoid overfetching data from external resources. Any ETA on pushing this with 1.0.5 to your quarkus-extention?

**Comment by phillip-kruger** [comment]
Hi @janknobloch . This should be in the next major version by the end of the month. So 1.7. thanks :)
