### ISSUE TITLE
Allow List @Source

### ISSUE THREAD

**Issue by frieck** [smallrye/smallrye-graphql#327]
I have a feature request:

Have been working in projects with [GraphQL-SPQR](https://github.com/leangen/graphql-spqr) and have been using DataLoader in order to solve N+1 query fetches. 
Their approach is quite simple, you can register a DataLoader where you define the GraphQL Controller:
```java
this.loaders = new DataLoaderRegistry();
this.loaders.register("flagLoader", DataLoader.newMappedDataLoader(flagLoader, DataLoaderOptions.newOptions().setCachingEnabled(false)));

...

GraphQLSchema schema = new GraphQLSchemaGenerator().generate();
graphQL = GraphQL.newGraphQL(schema).instrumentation(new DataLoaderDispatcherInstrumentation(loaders)).build();

```

That adds DataLoaders to query context, so we can use them:
```java
@GraphQLQuery(name = "namePromo")
public CompletableFuture<String> getNamePromo(@GraphQLContext final ItemDTO item, @GraphQLRootContext finall DataLoaderRegistry loaders) {
    final DataLoader<Long, String> dataLoader = loaders.getDataLoader("flagLoader");
    return dataLoader.load(item.getIdApresentation());
}
```
In the case above even if my query returns several items, the "namePromo" field will be fetched only one time in the case of repeated items.

Can we do the same on Smallrye-GraphQL?
Thanks

**Comment by phillip-kruger** [comment]
Hi @frieck - Thanks for this. Can you share the dataloader as well ? (I just want to see what it's doing).

**Comment by phillip-kruger** [comment]
I also updated my example to use `@RequestScope` to do something similar (I think).

see https://github.com/phillip-kruger/graphql-example/commit/9d28d5c94fc7c6b5bef55a44cca7a018b1ed3028

The output will be: (per request)
```
Country: fetching [en-ZA] from database
Country: cache size [1]
Country: returning [en-ZA] from cache
Country: returning [en-ZA] from cache
Country: returning [en-ZA] from cache
Country: returning [en-ZA] from cache
Country: fetching [en-AU] from database
Country: cache size [2]
Country: fetching [en-UK] from database
Country: cache size [3]
Country: returning [en-ZA] from cache
Country: returning [en-UK] from cache
Country: returning [en-AU] from cache
```

**Comment by frieck** [comment]
Hi @phillip-kruger 
ItemDTO is just a simple DTO class annotated with io.leangen.graphql.annotations.types.GraphQLType
and here is the Loader code:
```java
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import org.dataloader.MappedBatchLoader;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class FlagLoader implements MappedBatchLoader<Long, Map<String, Object>> {

    @Autowired
    private FlagService flagService;

    @Override
    public CompletionStage<Map<Long, Map<String, Object>>> load(final Set<Long> ids) {
        return CompletableFuture.completedFuture(flagService.getFlags(ids));
    }
}
```

Every time a query is loaded some ids are passed to the data loader. When the query completes loading normal data the GraphQL instrumentation will perform a call to the data loader to complete all loading of pending data. Here we are using a MappedBatchLoader, so we can have a map that links the flag id to its result.

This is very useful: imagine if you have 100 items but only 3 flags, the batch loader will prevent the query to perform a database search for each item flag, in that case the total number of db queries will be 1 (for the 100 items) + 3 for each flag.

**Comment by phillip-kruger** [comment]
Thanks @frieck - I think that confirms that my example will do the same, plus minus. Can you look at that and comment ?

**Comment by frieck** [comment]
The idea is almost the same in your example, but I am concerned that DataLoaders should not be confused with caches, it is not a cache approach it is a form to "hold" data do be loaded at the end and in a more efficient way (to solve the N+1 problem).
Please take a look at this issue: https://github.com/graphql/dataloader/issues/62

We can use the Completion Future approach to do more complex things like implementing @defer directive (apollo server has it).

Thanks,

**Comment by phillip-kruger** [comment]
Ok let me think about this some more. I'll get back to you

**Comment by phillip-kruger** [comment]
Hi @frieck - we discussed this today in the MP meeting. The plan is to pilot this in SmallRye:

```
public List<String> getCountry(@Source List<Person> person){
// Gather everything and make one unique call to datastore.
// Populate list response (Response list match paramater list
}
```

So it's a list version of what we already have:

```
public String getCountry(@Source Person person){

}
```
This should solve the N + 1 issue.

**Comment by phillip-kruger** [comment]
Changing the title, to answer the original question, you can register your own by listening for the following CDI Event:

```
public GraphQLSchema.Builder addMyOwnStuff(@Observes GraphQLSchema.Builder builder) {
        // Add custom stuff
        // builder....
        return builder;
    }
```

**Comment by phillip-kruger** [comment]
Batch Source is now added. see #365. Closing.
