### ISSUE TITLE
Typesafe client: inherit `@Header`/`@AuthorizationHeader` annotations

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#332]
Annotations on the parent of a `@GraphQlClientApi` interface are not recognized.

**Comment by andymc12** [comment]
I think it is more than just the annotations on the parent, but also annotations on the child when the methods are in the parent.  In my example, I had:
```
public interface BaseInterface {
    String method1();
    String method2();
}
```

```
@GraphQlClientApi
@Header(name = "SomeHeader", constant = "SomeValue")
public interface SubInterface extends BaseInterface {
}
```

In these calling `method1()` or `method2` resulted in making the request, but without the "SomeHeader: SomeValue" header.

Thanks again for looking into this!

**Comment by t1** [comment]
It's (as always) more complex than one would expect. And I'm only 99% sure it's what we really want: normally, annotations are only inherited when they are annotated to be `@Inherited`, and only from super classes, not from interfaces. This is quite obscure, so I can see why you expected this to work; I expected it myself. While it could also come as a surprise to some in very strange usage scenarios, I can't think of any reasonable use case that would break.
