### ISSUE TITLE
UnauthorizedException is hidden behind DataFetcherException in Quarkus 1.6

### ISSUE THREAD

**Issue by velias** [smallrye/smallrye-graphql#334]
We have `@Mutation` method annotated with `@Authenticated` and JWT configured in our Quarkus app. 
In Quarkus 1.5 GraphQL response reported `io.quarkus.security.UnauthorizedException` if JWT token was missing in request. 
After update to Quarkus 1.6 it is changed to `io.smallrye.graphql.execution.datafetcher.DataFetcherException` and error message is "Server Error" and there is not any indication for caller what is really wrong. 
It makes GraphQL API harder to use I believe, error reporting should be clear in this case, this is definitely not a server error but caller's problem, so he should know what is wrong to be able to call API correctly.

**Comment by jmartisk** [comment]
It seems that between 1.0.3 and 1.0.4 `ReflectionDataFetcher` started wrapping `SecurityException` into a `DataFetcherException` which isn't a good thing to do. I'll see what we can do to fix it

**Comment by phillip-kruger** [comment]
Hi @velias 
Can you add the following property to your application.properties

`smallrye.graphql.printDataFetcherException=true`

This should give you a more detailed message in the log file. 

You can also try and add the exception to the show list:

`mp.graphql.showErrorMessage=io.quarkus.security.UnauthorizedException`

This should show the exception message rather than `Server Error`.

Let me know

**Comment by jmartisk** [comment]
I might just be confused, but it seems that because we wrap it into `DataFetcherException`, setting `mp.graphql.showErrorMessage=io.quarkus.security.UnauthorizedException` doesn't have any effect because it's no longer an `UnauthorizedException`, but rather a `DataFetcherException`

**Comment by phillip-kruger** [comment]
Could be. Maybe we should allow unwrapping of DataFetcherExceptions ?

**Comment by phillip-kruger** [comment]
Or at least when we set the property to show the error message, we assume it should unwrap.

**Comment by jmartisk** [comment]
Hmm. In that case I probably don't understand the point of having `DataFetcherException` if we're going to wrap something in it and then unwrap it back anyway if it should be shown to the client.

**Comment by phillip-kruger** [comment]
Yea you are right, maybe we should see why did it changed ... I am not sure / can not remember.

**Comment by velias** [comment]
I tried `mp.graphql.showErrorMessage=io.quarkus.security.UnauthorizedException` and no luck. I tried `mp.graphql.showErrorMessage=io.smallrye.graphql.execution.datafetcher.DataFetcherException` and error message was `null`

**Comment by velias** [comment]
BTW Spec should probably allow to configure error messages per exception class, as exceptions sometimes may not contain good messages (mainly when they come from some frameworks)

**Comment by phillip-kruger** [comment]
OK let's figure out why it changed and take it from there.

**Comment by jmartisk** [comment]
This is the commit after which the behavior changed https://github.com/smallrye/smallrye-graphql/commit/afb737742a3fbbce6789887607a2535d2c67ffc8

**Comment by phillip-kruger** [comment]
@velias - can you help with a test case, that replicate your scenario ? That should help a lot.

**Comment by velias** [comment]
For sure I can, but I'm out of keyboard till next Thursday. Do you want to implement it directly into your test suite, or into separate project?

**Comment by phillip-kruger** [comment]
I think we can just add it to our test suite. If you point me to your code I can maybe get to it sooner.

**Comment by velias** [comment]
@phillip-kruger my original code is dependent on Quarkus, which is not available in your TCK, so I can't exactly reproduce my code. I created test where API explicitly throws `java.security.AccessControlException` (which is another subclass of the `java.lang.SecurityException` parent, as `io.quarkus.security.UnauthorizedException` is not in TCK) and checks response. I believe this test covers exception mapping problem.
I'm not fully sure which value should be in `extensions.classification` and `extensions.code` fields, probably some extra values dedicated for security exceptions?

Please look at the PR and feel free to use it.
