### ISSUE TITLE
JWT Integration

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#363]
See if we can get JWT integrated with @GraphQLApi same as with JAX-RS

**Comment by t1** [comment]
That would be very cool!

**Comment by jmartisk** [comment]
I'm not sure if there's anything to do in this regard on SmallRye side. In Quarkus it already works after having fixed https://github.com/quarkusio/quarkus/issues/9986 - this is a matter of the runtime framework that needs to set the correct security context before invoking the GraphQL handler.

**Comment by phillip-kruger** [comment]
With JAX-RS we can just do 
`
@LoginConfig(authMethod = "MP-JWT")
@DeclareRoles({ "user" })
`

And then use `@RolesAllowed`

We need something similar for GraphQL.

**Comment by phillip-kruger** [comment]
This works in Quarkus. Closing
