### ISSUE TITLE
Add getMetadata() method ( or overwrite toString() ) in io.smallrye.graphql.api.Context class

### ISSUE THREAD

**Issue by emecas** [smallrye/smallrye-graphql#366]
Currently in order to describe the injected context I am using a block like this on different places:

        log.log(Level.SEVERE,"CONTEXT -> "+ context.toString());
        log.log(Level.SEVERE,"getExecutionId -> "+ context.getExecutionId());
        log.log(Level.SEVERE,"getRequest -> "+ context.getRequest());
        log.log(Level.SEVERE,"getSelectedFields -> "+ context.getSelectedFields());
        log.log(Level.SEVERE,"getSource -> "+ context.getSource());
        log.log(Level.SEVERE,"getVariables -> "+ context.getVariables());
        log.log(Level.SEVERE,"getFieldName -> "+ context.getFieldName());
        log.log(Level.SEVERE,"getPath -> "+ context.getPath());
        log.log(Level.SEVERE,"getQuery -> "+ context.getQuery());

By adding a `getMetadata()` method directly to Context class, it would give the option for calling in a single place all methods providing information about the context, for debugging purposes it could be accomplished as well by overwriting` toString()`

**Comment by phillip-kruger** [comment]
Let implement toString() - I think that would be easy enough
