### ISSUE TITLE
Static fields in SourceOperationHelper prevent correctly parsing source operations with multiple deployments

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#375]
https://github.com/smallrye/smallrye-graphql/blob/40f57f228665b21a363ed36027f381212c120c30/common/schema-builder/src/main/java/io/smallrye/graphql/schema/helper/SourceOperationHelper.java#L29

In WildFly, the result of this is that `sourceAnnotations` and `sourceListAnnotations` fields will always be set to values from the first deployment, so subsequent deployments will receive an inconsistent schema.

**Comment by phillip-kruger** [comment]
Thanks @jmartisk . Do you have a fix ready ?
