### ISSUE TITLE
Interceptors / Filters for Graphql Clients 

### ISSUE THREAD

**Issue by sherl0cks** [smallrye/smallrye-graphql#386]
Is there anything like the microprofile rest client client request filters / interceptors? If not, this would be a great feature to add, and I'd love your suggestion for a workaround in quarkus until that feature is available. https://download.eclipse.org/microprofile/microprofile-rest-client-1.3/microprofile-rest-client-1.3.html#_clientrequestfilter

**Comment by phillip-kruger** [comment]
Hi @sherl0cks 
Thanks for this suggestion. We will look at this a.s.a.p.

**Comment by phillip-kruger** [comment]
@t1 - any thoughts ?

**Comment by andymc12** [comment]
Could the filtering/intercepting be deferred to the underlying transport implementation?  For example, if the GraphQL Client implementation uses the JAX-RS Client or MP Rest Client as a transport, then you could use JAX-RS's `ClientRequestFilter` or `ClientResponseFilter` - and other JAX-RS provider classes.  Other transport implementations, like Apache HTTP Client have other mechanisms.  That makes the client code less portable, but also avoids re-inventing the wheel.  Wdyt?

**Comment by sherl0cks** [comment]
Certainly works for me as a first pass and I can provide feedback on it.
How would that work with the current Small rye implementation?

**Comment by t1** [comment]
@andymc12 : I'm very much in favor on depending on JAX-RS, but there's a motion to actually get completely rid of JAX-RS #436. I assume this is for the implementation to be portable to Spring or other non-JAX-RS environments.

Maybe we can still combine the requirements: JAX-RS has a `register` method that takes an object, or even just a class for the implementation to instantiate (and inject, etc.). We could also provide a `register` method to just forward to JAX-RS, without limiting the portability of the APIs. Only the portability of the application itself would be limited.

For filters that should be registered generally for all calls, the JAX-RS `@Provider` annotation should already work.

**Comment by t1** [comment]
@sherl0cks: there are many register methods, configuration properties, etc.; I added only two that I considered to be the core: registering a class and an instance. Is this sufficient for your use-case?
OTOH, if you must really fully configure the JAX-RS client, you can also downcast the `GraphQlClientBuilder` to `GraphQlClientBuilderImpl` and set the client there; this is used for the tests, but may prove helpful here, too.

**Comment by andymc12** [comment]
@t1 - yes, I like this approach.  I have no issue with SmallRye's implementation using JAX-RS.  What it uses under the hood is implementation detail.  My preference would be for the MP GraphQL spec to not require JAX-RS (or really any other HTTP client).

**Comment by sherl0cks** [comment]
Works for me!
