### ISSUE TITLE
NPE: some validation errors don't provide a query path

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#387]
Some validation errors don't provide a query path, e.g. `LoneAnonymousOperation`. This results in a NPE in the call to `toJsonArray` in line 75 of the `ExecutionErrorsService`.

Would it be better to provide an empty path or null?

**Comment by phillip-kruger** [comment]
@t1 - are you working on this ? If not I can have a quick look / or move to 1.0.10
