### ISSUE TITLE
Access to DataFetchingEnvironment

### ISSUE THREAD

**Issue by marceloverdijk** [smallrye/smallrye-graphql#39]
Is it possible to retrieve the `DataFetchingEnvironment` in a query method?

**Comment by phillip-kruger** [comment]
Hi @marceloverdijk.
`DataFetchingEnvironment` is part of graphql-java lib, that will not be available and should be hidden behind the impl. However, as part of version 1.1 (from the spec) we want to introduce a context element that can be injected anywhere that gives you access to the original query or mutation. 

(see https://github.com/eclipse/microprofile-graphql/issues/127)

If I might ask (as this will help defining this above mentioned context) - what is your use-case / needs ?

Thanks

**Comment by marceloverdijk** [comment]
Hi @phillip-kruger 

Mainly to retrieve the selection set via `DataFetchingFieldSelectionSet getSelectionSet();`.

**Comment by phillip-kruger** [comment]
Hi @marceloverdijk 
Ok cool. So for now until we get this into the spec, I can maybe see if there is a way that smallrye can allow this. How urgent is this for you, or are you just playing ?

**Comment by marceloverdijk** [comment]
It is not urgent; I'm "playing". Looking forward to the Quarkus integration and experiment with the code first approach.

**Comment by phillip-kruger** [comment]
Ok thanks, that allows me to do it property in the spec. 

Closing this for now.

Thanks

**Comment by mnguetsa** [comment]
@phillip-kruger Just checking whether there has been some progress on this matter.
DataFetchingEnvironent access could be interesting ti differentiate between omitted parameters Vs actual null parameters.
Also I am open to alternative approaches to achieve this with Smallrye GraphQL
Thank you

**Comment by phillip-kruger** [comment]
@mnguetsa You can get access to the DataFetchingEnvironment by injecting the `import io.smallrye.graphql.api.Context;` and then use the `unwrap(DataFetchingEnvironment.class)` method to get the DataFetchingEnvironment. Hope this helps

**Comment by mnguetsa** [comment]
@phillip-kruger Thanks a lot. That worked
