### ISSUE TITLE
Async Batch Source not working

### ISSUE THREAD

**Issue by eamelink** [smallrye/smallrye-graphql#396]
I have a `Person` with an a nullable attribute `client`, which is a `Client`, which I'm batching. This works:

    public List<Optional<Client>> client(@Source List<Person> people)

and it gives this schema fragment:

    type Person {
       client: Client
    }

Making this async, breaks it though. The following:

    public CompletableFuture<List<Optional<Client>>> client(@Source List<Person> people)

gives the following schema fragment:

      type Person {
          client: [Client]
      }

Now, client is unexpectedly a list. It also breaks at runtime. It appears that `ArrayCreator.createArray` incorrectly marks the Operation as an array type.

**Comment by phillip-kruger** [comment]
Thanks for this @eamelink ! Just f.y.i, batch is already called as a CompletableFuture (see https://github.com/smallrye/smallrye-graphql/blob/1980895f8d10f6a94ebbb24a641b19f6998631c4/server/implementation/src/main/java/io/smallrye/graphql/execution/batchloader/SourceBatchLoader.java#L43) so you might not want to do this. 

But in any case this is a bug, and we need to fix this. Are you looking at fixing it ? Else I'll have a look a.s.a.p.
