### ISSUE TITLE
Union Types

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#400]
We had a discussion on the weekly live stream about supporting Union Types (see GraphQL [tutorial](https://graphql.org/learn/schema/#union-types) and [spec](http://spec.graphql.org/draft/#sec-Unions)). Before we bring the discussion into MP GraphQL (see https://github.com/eclipse/microprofile-graphql/issues/32), we'd like to start an open discussion here:

# use cases

The idiomatic use-case in the tutorial is search results, i.e. I search for a string an get a list of objects that can be, e.g. a `Hero`, a `Starship`, or anything else. And the result list should render the matched items using a component with the appropriate data for the actual type.

I'm not sure, if this is possible in other GraphQL servers, but another use case could be when you evolve an API: you may start off with a simple `String` field for, e.g., an `email` address. But then you want to add more details, maybe the verification status. If it's only one field, you may add a `emailVerificationStatus`, but when there are many fields, it may be better to structure these fields into an `Email` type with `address`, `verificationStatus`, and other fields. To remain backwards compatible, clients requesting the `email` field without subfields will still get the `String`, while clients requesting sub fields will get those.

# thoughts about the API

A query could return a wrapper type with two or more type parameters (similar to the [`Either` type from vavr](https://www.vavr.io/vavr-docs/#_either)).

```java
@Query List<Union<Hero, Starship>> search(String queryString) { ... }
```

We would also need `Union3<T1, T2, T3>` up to some number of possible alternatives... maybe 10?

**Comment by t1** [comment]
Another use-case I found at vavr is validation: instead of throwing an exception, a value may either be a valid value or a list of error descriptions. There's even a special `Validation` type for that in vavr. This could be used to display the login status: either the user is logged in and, e.g., we render her name; or she is logged out and we render the reason: not signed up, logged out, session expired, etc.

**Comment by t1** [comment]
I actually have this situation: I have a list where some items may legally be missing and I need to report details about the reason. These are not errors, so throwing an exception is inappropriate. I wrote an `Either` class and it's turned into a List itself, i.e. in the schema it's `details(): [[Details]]` and I don't have any type information about the alternative. A Union `Details | NoDetails` would be really helpful!

**Comment by t1** [comment]
We have another use-case in a project, polymorphism: e.g. an order has a list of different types of order items, i.e. `List<OrderItem>` where `OrderItem` is an abstract super class with some fields, and the sub types `ProductOrderItem` and `DiscountOrderItem` with both having their specific fields. The schema of the order should be `type Order { <other fields> orderItems: [ProductOrderItem | DiscountOrderItem] }`.

The order item could also become an [`interface`](https://graphql.org/learn/schema/#interfaces) in the schema, but this is probably a different issue.

**Comment by sgift** [comment]
I wanted to ask if something is planned for this issue. I have a related problem to the one t1 mentioned in the last comment: I have a base class which can hold various optional data in addition to some common data. I've introduced an empty interface for the optional data and three classes implementing it in the hope that smallrye-graphql would build an union type for them, but instead only get the error that my interface has to define fields (which it doesn't, since it's just a marker for my data classes).

**Comment by phillip-kruger** [comment]
We want to support this yes. We also accept PRs :)

**Comment by t1** [comment]
I think GraphQL interfaces are a separate issue, so I opened #1399.

**Comment by t1** [comment]
IIUC, GraphQL Unions are just like Interfaces, just that they don't have to have a common set of base fields. The schema syntax is different, but queries are exactly the same (as long as you don't select those common fields outside of the inline-fragments). I.e. you can simulate Unions by defining a common interface with only a dummy field (too bad that SmallRye GraphQL doesn't support `default` methods on interfaces).

The query could look something like this, for an Interface exactly as for a Union:
```graphql
{
  order(id: "1") {
    __typename
    ... on Order {
      id
      orderDate
      customer {
        name
      }
    }
    ... on LockedOrder {
      reason
      start
    }
  }
}
```

With an interface, this can already be implemented like this:

```java
public interface OrderResponse {
    @Description("this is a dummy field, so we can use an Interface instead of a Union")
    Instant getResponseTimestamp();
}

public class Order implements OrderResponse {
    @Id String id;
    LocalDate orderDate;
    Customer customer;
    ...
}

public class LockedOrder implements OrderResponse {
    Instant start;
    LockReason reason;
    ...
}
```

And I think that we should not define `Union2...n` classes, but a `@Union` annotation, as union classes could need to contain some application logic, e.g. deriving the exact response type from an exception. So an implementation could look like this:

```java
@Query OrderResult order(String id) { ... }

@Union
public class OrderResult {
    private final Order order;
    private final Throwable throwable;

    /* these two constructors guarantee that only one field can be set */
    public OrderResult(Order order) {
        this.order = order;
        this.throwable = null;
    }

    public OrderResult(Throwable throwable) {
        this.order = null;
        this.throwable = throwable;
    }

    public Order getOrder() {
        return order;
    }

    public LockedOrder getLockedOrder() {
        return (throwable instanceof OrderLockedException) ? deriveLockedOrderFrom(throwable) : null;
    }
}
```

The `@Union` annotation would create the Union in the schema, failing if the return types of all getters are not distinct. On execution, SmallRye would call all getters and validate that exactly one value is non-null. The wrapper type would not appear in the result.

What do you think?
