### ISSUE TITLE
Add BeanValidation Annotations as `@constraint` Directives

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#402]
Many BeanValidation annotations could be mapped to `@constraint` directives that are specified, e.g., by [graphql-constraint-directive](https://github.com/confuser/graphql-constraint-directive). This would allow clients to validate user input directly in the frontend... even while typing... without repeating the constraints already defined in the backend model.

**Comment by jmartisk** [comment]
This has been already implemented for some time (see https://smallrye.io/smallrye-graphql/2.0.1/directives/ for documentation), so we can close it
