### ISSUE TITLE
Request to compile with -parameters when using GraphQlClientBuilder API

### ISSUE THREAD

**Issue by fmarchioni** [smallrye/smallrye-graphql#427]
When running a Mutation using the fluent GraphQlClientBuilder, an exception is raised:
```
09:55:38,760 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /mp-graphql/demo: io.smallrye.graphql.client.typesafe.api.GraphQlClientException: compile with -parameters to add the parameter names to the class file
at deployment.mp-graphql.war//io.smallrye.graphql.client.typesafe.impl.reflection.ParameterInfo.getName(ParameterInfo.java:40)
at deployment.mp-graphql.war//io.smallrye.graphql.client.typesafe.impl.RequestBuilder.appendParam(RequestBuilder.java:38)
at deployment.mp-graphql.war//io.smallrye.graphql.client.typesafe.impl.RequestBuilder.build(RequestBuilder.java:30)
at deployment.mp-graphql.war//io.smallrye.graphql.client.typesafe.impl.GraphQlClientProxy.request(GraphQlClientProxy.java:60)
at deployment.mp-graphql.war//io.smallrye.graphql.client.typesafe.impl.GraphQlClientProxy.invoke(GraphQlClientProxy.java:46)
at deployment.mp-graphql.war//io.smallrye.graphql.client.typesafe.impl.GraphQlClientBuilderImpl.lambda$build$0(GraphQlClientBuilderImpl.java:47)
at deployment.mp-graphql.war//com.sun.proxy.$Proxy77.createItem(Unknown Source)
at deployment.mp-graphql.war//com.mastertheboss.graphql.sample.client.GraphQLServlet.doGet(GraphQLServlet.java:26)
```

Source code:

```
protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        ItemApi api = GraphQlClientBuilder.newBuilder().endpoint("http://localhost:8080/"+ request.getContextPath()+"/graphql").build(ItemApi.class);

        Item item = new Item();
        item.setId(2);
        item.setType("car");
        item.setModel("ferrari");
        item.setPrice(500);

        // Insert Item  --- Fails!
        api.createItem(item);

        // Iterate
        List<Item> list = api.getAllItems();
        for (Item i:list) {
            response.getWriter().append(i.toString());
        }
    }

}
```
Full source code: https://github.com/fmarchioni/mastertheboss/tree/master/micro-services/mp-graphql

**Comment by phillip-kruger** [comment]
@t1 - any thoughts ?

**Comment by jmartisk** [comment]
I'm not sure, but this could have something to do with the fact that the application is in a WAR file deployed in WildFly. The class is compiled with `-parameters` but the client code isn't able to access the parameter names.
Shouldn't we be using Jandex rather than Java reflection here?

**Comment by jmartisk** [comment]
So I reproduced it outside WildFly too. Looks like JVM does not pass parameter metadata when invoking a proxy's `InvocationHandler` (https://github.com/smallrye/smallrye-graphql/blob/1.0.11/client/implementation/src/main/java/io/smallrye/graphql/client/typesafe/impl/GraphQlClientBuilderImpl.java#L47)

**Comment by t1** [comment]
I reproduced it. Just add:

```xml
                  <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-compiler-plugin</artifactId>
                      <version>3.8.1</version>
                      <configuration>
                          <parameters>true</parameters>
                      </configuration>
                  </plugin>
```

and annotate the `@Mutation` and it works.

**Comment by t1** [comment]
Oh, I forgot to mention the alternative: you can also annotate all parameters with `@Name`, like you have to do for JAX-RS and many other frameworks.

Off-Topic: I always wondered why the parameters are not enabled by default. Yes they take up space in the class files and at runtime. But probably 99% of Java developers don't work with so memory-constrained devices and would prefer it over having to repeat parameter names in annotations. This is premature optimization. Sorry I couldn't resist bringing this up here.

I guess this alternative should also be mentioned in the exception message. I'll do a PR.

**Comment by t1** [comment]
One more thing: looking at a build-time-generated Jandex file could be added as a third option. The client doesn't use Jandex, yet.
