### ISSUE TITLE
Upgrade to use jakarta 9

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#435]
with the namespace changes.

**Comment by parsharma** [comment]
@phillip-kruger are you working on this? 

Thanks

**Comment by phillip-kruger** [comment]
No, but I am not to sure how to proceed here. Maybe @radcortez can help with how smallrye projects should proceed.

**Comment by radcortez** [comment]
I was working on the SR Config prototype but had to move for other stuff. I'll need to pick that up again.

**Comment by jmartisk** [comment]
The main branch has been on the Jakarta namespace for some time
