### ISSUE TITLE
Resolvers are not executed async

### ISSUE THREAD

**Issue by michaelsonnleitner** [smallrye/smallrye-graphql#445]
I am using smallrye-graphql-cdi 1.0.12 inside quarkus 1.8.1

I have following query:

```
query{
  p1: person(id: 1) {
    fristname
  }
  p2: person(id: 2) {
    lastname
  }
}
```

I have following Resource:

```
@GraphQLApi
public class PersonResource {

    @Query
    public Person getPerson(@Name("id") long id) throws ApiException, InterruptedException {
       Thread.sleep(2000);
        return personRestApi.load(id);
    }
}
```

I have following Person Object:

```
public class Person
{
   private long id;;
   private String lastname;
   private String firstname;
   //getter + setter;
}
```

Also resolvers like the following are called in serial order...
```
public List<Adress> getAdresses(@Source Person p)
{ 
   return adressApiCall.getAdresses(p.getId());
}
public List<Phonenumber> getPhonenumbers(@Source Person p)
{ 
   return phonenumberApiCall.getPhonenumbers(p.getId());
}
```

Why is PersonResource.getPerson(1) and  PersonResource.getPerson(2) executed each after each and not parallel?
What am I doing wrong?
How can I make it async? Do I have to use AsyncDataFetcher (but this  is not microprofile standard)

**Comment by phillip-kruger** [comment]
Hi @michaelsonnleitner . Thanks for this issue.

The idea would be to use `CompletableFuture` for both `Queries` and `Source` methods. See https://github.com/smallrye/smallrye-graphql/blob/master/server/tck/src/test/java/io/smallrye/graphql/test/apps/async/api/AsyncApi.java

However, even though they execute Asynchronously, they do not know about each other. This still need some work, I'll look at this a.s.a.p.

**Comment by phillip-kruger** [comment]
@michaelsonnleitner - on a separate note. When using Quarkus, you should be using the SmallRye GraphQL Extension, and not include the SmallRye library on your own. Quarkus 1.8.1 is using 1.0.9 of SmallRye GraphQL. 1.9.0 will be using 1.0.12.

If you use the extension you get some build time optimization (the annotation scanning and schema creation happens on build)

**Comment by michaelsonnleitner** [comment]
@phillip-kruger: Thanks for your response. I wanted to test against the latest version of SmallRye GraphQL (because it is common for me) and I did not know that this could run into problems with quarkus

I tried that stuff with ``CompletableFuture`` for root query person). good hint! this works

do you mean that async & source behaivor is not working yet, if they are related to each other? I did not understand completely,

**Comment by phillip-kruger** [comment]
@michaelsonnleitner - I think it might be working, there was just an issue with my example. Give me a few mins then I'll send you an example.

**Comment by phillip-kruger** [comment]
@michaelsonnleitner - Ok good news. It seems to be working ok. (I just coded a bad example initially)

See https://github.com/phillip-kruger/graphql-async-example as a example that works.

The important parts:

```
@GraphQLApi
public class PersonResource {

    @Inject 
    BackendService backendService;
    
    @Query
    public CompletableFuture<Person> getPerson(long id) throws InterruptedException {
        return CompletableFuture.supplyAsync(() -> backendService.getPerson(id));
    }
    
    
    public CompletableFuture<List<Adress>> getAdresses(@Source Person p) throws InterruptedException{ 
        return CompletableFuture.supplyAsync(() -> backendService.getAdressesForPerson(p.id));
    }
    
    public CompletableFuture<List<Phonenumber>> getPhonenumbers(@Source Person p) throws InterruptedException{ 
        return CompletableFuture.supplyAsync(() -> backendService.getPhonenumbersForPerson(p.id));
    }
}
```

Make sure to do a `supplyAsync` in your `CompletableFuture`.

Also make sure to sleep in the backend service (else you sleep before the thread kicks off - that was my bad example)

This query:

```
query{
  person1:person(id:1){
    firstname
    lastname
    phonenumbers{
      number
      countycode
    }
    adresses{
      lines
      code
    }
  }
  person2:person(id:2){
    firstname
    lastname
    phonenumbers{
      number
      countycode
    }
    adresses{
      lines
      code
    }
  } 
}
```

Will return this:

```
{
  "data": {
    "person1": {
      "firstname": "Kruger",
      "lastname": "Kruger",
      "phonenumbers": [
        {
          "number": 833906859,
          "countycode": 27
        }
      ],
      "adresses": [
        {
          "lines": [
            "1 Kerk straat",
            "Groenkloof",
            "Pretoria",
            "Suid Afrika"
          ],
          "code": "1967"
        }
      ]
    },
    "person2": {
      "firstname": "Michael",
      "lastname": "Sonnleitner",
      "phonenumbers": [
        {
          "number": 956321449,
          "countycode": 43
        }
      ],
      "adresses": [
        {
          "lines": [
            "5 Falkestraße",
            "Wien",
            "Austria"
          ],
          "code": "1234"
        }
      ]
    }
  }
}
```

in the log file, you can not see the execution is concurrent for both the queries and the source methods:
```
>>>>>>>>> Getting person 1
>>>>>>>>> Getting person 2
<<<<<<<<< Got person 1
<<<<<<<<< Got person 2
>>>>>>>>> Getting phonenumbers 2
>>>>>>>>> Getting adresses 2
>>>>>>>>> Getting adresses 1
>>>>>>>>> Getting phonenumbers 1
<<<<<<<<< Got phonenumbers 2
<<<<<<<<< Got person 2
<<<<<<<<< Got person 1
<<<<<<<<< Got phonenumbers 1
```

Hope this helps. If you are happy with this you can close the issue.

**Comment by phillip-kruger** [comment]
Also, the only thing you are missing between 1.0.9 and 1.0.12 will be that async batch was not working. The example above did not use batch, but if you want to do batch, you will need to wait for Quarkus 1.9.0.

**Comment by michaelsonnleitner** [comment]
thank you very much! I had also that batch problem (with a nullpointer) good to know that this will work with 1.9.0.

I like your graphql implementation very much. Its easy and great!

**Comment by phillip-kruger** [comment]
Thanks :) 
Yes, see this PR that fixed async batch.

Once 1.9.0 is out we can test an example against that
