### ISSUE TITLE
Possible improvements to Quarkus extension

### ISSUE THREAD

**Issue by wtrocki** [smallrye/smallrye-graphql#447]
Creating an issue to seed discussion about possible improvements in Quarkus extension to 
`smallrye-graphql` 

1. Prerequisites:

Review https://quarkus.io/guides/microprofile-graphql 

2. Post possible improvements and seed discussion on how to improve it.

**Comment by wtrocki** [comment]
It looks like batching section is unfinished:
https://quarkus.io/guides/microprofile-graphql

Maybe that is issue. Best to remove it if it's empty.

**Comment by phillip-kruger** [comment]
@wtrocki - Yes we should add more details in the guide. Async is also missing.

**Comment by wtrocki** [comment]
I forgot to create PR. Looks like problems were fixed already (got conflict today when creating PR)

https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/microprofile-graphql.adoc

Guide seems complete now. Closing
