### ISSUE TITLE
Graphql client throws exception when errors array is empty.

### ISSUE THREAD

**Issue by erikhh** [smallrye/smallrye-graphql#448]
I'm using smallrye-graphql-client-all version 1.0.12.

The API I'm working with returns results like this:
```
{
  "errors": [],
  "data": {
    "field": {
      "foo": "some value"
    }
  },
  "extensions": null,
  "dataPresent": true
}
```

And even tough there are no errors in the error list, the client throws a `GraphQlClientException`, with the message `errors from service: []`

Apart from this issue. It would be useful to have a more fine grained error handling mechanism than a 'all or nothing exception'. So you can deal with situations where some fields of the request give errors but others still return results.

**Comment by phillip-kruger** [comment]
@t1 - should be an easy fix. I think we can assume no errors if the error field is not there OR empty.

**Comment by erikhh** [comment]
Proposed fix got accepted.
