### ISSUE TITLE
Migrate our WildFly-based tests to use the GraphQL feature pack

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#462]
Currently, our integration tests module works in the way that it deploys all necessary GraphQL things within its deployments. Perhaps we could make use of the new WildFly feature pack (https://github.com/wildfly-extras/wildfly-graphql-feature-pack) and provision a WildFly instance with it installed, and slim down the testing deployments - they won't need to carry all GraphQL dependencies and will look more like the real-world deployments (how users in production do it).

**Comment by t1** [comment]
We should do that as soon as possible. In my current project, we will still package GraphQL with our applications until. We still wait for https://github.com/wildfly-extras/wildfly-graphql-feature-pack/issues/6 to be completed. https://github.com/wildfly-extras/wildfly-graphql-feature-pack/issues/10 would help us, too.

**Comment by jmartisk** [comment]
https://github.com/wildfly-extras/wildfly-graphql-feature-pack/issues/6 might actually become a problem for this task, because if we move to using static modules in WildFly, we can run into it. Right now we package GraphQL in the deployment, which coincidentally acts as a workaround for the problem.
However, fixing it will need a release and upgrade to Graphql-java 16.0, which I'm not really sure when will happen

**Comment by jmartisk** [comment]
Damn, I just realized a serious problem with this that should have struck me immediately.
Right now, the test suite deploys the currently built snapshot of SR-GQL. If we depend on a released version of the feature pack, that feature pack will necessarily contain an older already released version of GraphQL, and we would basically test that one instead of the current snapshot. So this would be of no use as CI testing.

To do this properly, we would need a way to run a custom build of the feature pack that would include the correct GraphQL snapshot under test, and use that feature pack for testing. That sounds... probably possible, but really complicated.

**Comment by t1** [comment]
I didn't see that, either. :-) But there's not so much magic about it. I've done that several times, e.g. while building a Docker image by using cli-embedded WildFly.

**Comment by jmartisk** [comment]
It's also kind of a circular dependency, because the feature pack (obviously) depends on SmallRye, and we would basically make SmallRye depend on the feature pack too. Not that it wouldn't work (one direction of the dependency would be test-only) but it's a little worrying from the perspective of good practices :)

**Comment by t1** [comment]
Yeah. Maybe we should close this?

**Comment by jmartisk** [comment]
Yeah... I'm afraid I don't have any clear idea how to do this nicely. 
One more reason to drop this is that we run the WF feature pack test suite as part of SmallRye GraphQL CI (it runs with GraphQL snapshots with each pull request), so that helps with regression testing quite a bit too. If we need more tests that deploy the "thin" JAR, we can use that test suite for it.
