### ISSUE TITLE
Client: Non-Null variables

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#463]
E.g. when calling a method with a non-null parameter, the parameter in the client interface has to be annotated as `@NonNull`, too. The current implementation doesn't recognize that and still produces a request with, e.g., `String` instead of `String!`. The same will probably be true for collections.

**Comment by Flame239** [comment]
@t1 Could you explain reason behind adding "Input" to all input parameters?

**Comment by t1** [comment]
@Flame239: This is how the server works. I agree that this is not always perfect (see #360). Do you face any specific problem? Should we open another issue?

**Comment by Flame239** [comment]
@t1 We are trying this client for our server and, although we have most of our inputs ends with "...Input" some of them are not, so we can't use this client as is.

**Comment by Flame239** [comment]
@t1 Not adding "Input" to the name if it was taken from @Named annotation is the simplest way to go. Afterall, we expect to have full control of type name if we use this annotation.

**Comment by t1** [comment]
I just created #484
