### ISSUE TITLE
With the client, how do I pass variables to child nodes?

### ISSUE THREAD

**Issue by erikhh** [smallrye/smallrye-graphql#465]
I can't really work out how I can make a client that allows me to perform queries with parameters that are below the root node of the graph.

For example; how would I generate queries like this?
```
query {
  people(lastName: "Smith") {
    friends (type: Relatives) {
      firstName
      lastName
    } 
  }
}
```
Where I would like to provide the values for for both `lastName` as `type` from my buisinesslogic. Is that possible at the moment?

**Comment by phillip-kruger** [comment]
`@Source` methods can have parameters (other that the actual source). That should do it.

**Comment by phillip-kruger** [comment]
So something like:

```
@Query
public List<Person> getPeople(String lastName){
  // return people with surname == lastName
}

public List<Person> getFriends(@Source Person person, Type type){
    // return all the friends for person that is of type type
}
```

**Comment by erikhh** [comment]
Not sure that I can follow you, or maybe we're not quite on the same page.

I mean like I want to perform a query against this API like so:
```java
class Person {
  List<People> friends;
}

@GraphQlClientApi
interface AwesomeApi {
  List<Person> people(String lastName);
}

private AwesomeApi api;

public void findPeople(String lastName, Type friendType) {
  // How do I get friendType in my query to the server here?
  List<Person> smithes = api.people(lastName);
}
```
Let's assume the list of friends is millions long, I can't retrieve them all to filter them client side.

**Comment by phillip-kruger** [comment]
OK apologies, I assumed you mean server site, I see now you want a client query. 
@t1 ? You want to take this ?

**Comment by t1** [comment]
@erikhh: this is not supported, yet. Do you have any suggestion how the syntax could work?

**Comment by erikhh** [comment]
Using query variables it could be something like this maybe?

```java
class Person {
  @Variable(id="$friendType", name="type", type=Type.class, optional=true, default=Type.Aquiantances)
  List<People> friends;
}

@GraphQlClientApi
interface AwesomeApi {
  List<Person> people(String lastName, @Variables Map<String, Object> variables);
}

private AwesomeApi api;

public void findPeople(String lastName, Type friendType) {
  Map<String, Object> vars = new Hashmap<>();
 vars.put("friendType", friendType);
  List<Person> smithses = api.people(lastName, vars);
}
```

**Comment by t1** [comment]
Thanks for the input. Some parts reminds me of the dynamic API planned for MP GraphQL. The typesafe client api would loose some of it's elegance, wouldn't it?

**Comment by erikhh** [comment]
Yes, yes it would :-)

But I had another idea the other day. Spring Data MongoDB has a feature in the API called query by example. There you can pass a partially filled entity as argument. The framework uses that value construct a query, it's mostly simple filters I think, but that's not the point. You can read more about it here: https://docs.spring.io/spring-data/mongodb/docs/3.0.4.RELEASE/reference/html/#query-by-example

It got me thinking (and this is only a very rough and broad idea), because in a way the type safe client currently uses the return type of a function to construct most of the request. Maybe there could be a way to take the same type as argument? So you can put together your desired response entity structure, and somehow fill it with the additional filters you need in various places.

The argument and response types of a `GraphQlClientApi` function would be the same, with maybe the addition that the return type is plural (e.g a List) and the argument would be singular. Maybe you could use annotated interfaces maybe with default methods, or some kind of call back construction. To provide values to various filter arguments on various fields in the request tree?

Like I said is a really rough idea. And I'm not any kind of masterful API designer, but maybe there's inspiration in this somewhere.

**Comment by t1** [comment]
[Query By Example](https://en.wikipedia.org/wiki/Query_by_Example) is an older concept, and I guess it would be useful only in a subset of cases.

Maybe we could instead stick more to the concept in GraphQL and chain calls somehow? E.g. to get the acquaintances of all relatives of the Smith family:

```java
Set<Person> result = people("Smith").friends(Relatives).friends(Acquaintances);
```

The only question is: how can the client understand that the call should only be created and executed after the second call to `friends`? One option would be to wrap the return type of `people` in a new `Chain` type, e.g. `Chain<Set<Person>>`; and this class has a `execute` method, e.g. `Set<Person> result = people("Smith").friends(Relatives).friends(Acquaintances).execute();`.

WDYT?

**Comment by erikhh** [comment]
Oh yeah. That could work! 
Kind of reminds me of how you work with Mockito. But there you have a static method to get you started.

That might be something like this:
```java
private AwesomeApi api;

public void findPeople(String lastName, Type friendType) {
  request(api).people(lastName).friends(friendType).submit();
}
```
Then maybe you wouldn't need any nested generics in the `@GraphQlClientApi` interface.

**Comment by t1** [comment]
Mockito is a good role model. But we would have to do something like `chain(api.people(lastName).friends(friendType)).submit()`, as the `friends` method wouldn't have a return type with a `submit` method, would it?

But calling just `api.people(lastName)` wouldn't work anymore ;-(

**Comment by erikhh** [comment]
I thought the static call at the beginning would let you introduce a proxy object by wrapping the argument. That proxy object can be used to also wrap all the return value from all the relevant methods the child nodes as well.

That way the `Chain` class can be kept out of the public API. Wouldn't that result in a cleaner overall public API?

**Comment by t1** [comment]
Just to summarize: real question, I guess it's: how can we make both `api.people(lastName)` as well as `api.people(lastName).friends(friendType)` work? Or more generally: how can we know that the request is complete and can be executed?

My first thought was to change the API, so it doesn't return just a `Set<Person>` but a `Chain<Set<Person>>`, so we can call `submit` (or so) when the request is fully built. This is an invasive change to the API.

Your Mockito-inspired suggestion was to keep these technical details out of the API and use a static wrapper method instead. Then we have to ask: where do we place the `submit`? We can't call it on the return value of the `friends` method, i.e. `Set<People>`, so we need to wrap the full request, i.e. like Mockito `chain(api.people(lastName).friends(friendType)).submit()` or even shorter: `submit(api.people(lastName).friends(friendType))`.

The downside of this approach is that it's not obvious from the syntax that the call chain needs to be wrapped in a `submit` call. At runtime we could throw an exception as soon as the proxy `Set<People>` is accessed in any way other than being passed to the `submit` method. Mockito does that and throws an `UnfinishedStubbingException` if necessary. This would work most of the time for us, too, but a client could call a mutation and not be interested in the result other than it doesn't throw an exception, e.g. `api.cancelReservation()`. This would only build the request and never execute it.

I assume method chaining to be a rather exotic use-case. Maybe the `Chain` wrapper class wouldn't be too bad after all.

**Comment by t1** [comment]
We've have exactly this issue in a project and talked about possible solutions. My current favorite is to use an annotation on another parameter, i.e.:

```java
@GraphQlClientApi
interface AwesomeApi {
  List<Person> people(String lastName, @NestedParameter("friends") FriendType friendType);
}
```

This would create a query like this:

```graphql
query people($lastName: String, $friendType: FriendType) {
    people(lastName: $lastName) {
        firstName lastName
        friends(friendType: $friendType) {
            firstName lastName
        }
    }
}
```

The `@NestedParameter` takes an expression to locate the position of the parameter within the query.

What do you think?

**Comment by t1** [comment]
@erikhh:  I created a PR. Maybe you can try it out if it suits your use case?
