### ISSUE TITLE
Typesafe Client: Don't add `Input` when the name is specified with `@Name` or `@Input`

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#484]

**Comment by t1** [comment]
As a class can be used as `Type` as well as as `Input`, I think the name given by `Name` should still be suffixed with `Input`. If you want to specify the full input name, the `Input` annotation is a better match, I guess.

**Comment by phillip-kruger** [comment]
the server does not do that. I think we need to keep it consistent. We only add Input when we derive this from the classname.
