### ISSUE TITLE
Add support for subscriptions

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#490]

**Comment by thomas-ferchau** [comment]
@phillip-kruger: I would really appreciate support for subscriptions! 

We would like to provide a reactive interface to push events to a Smartphone App. We are currently evaluating Smallrye GraphQL for doing that. 

Is there currently any workaround to create an asynchronous GraphQL server (e.g. _subscriptions_ or _live queries_) in Smallrye GraphQL / Quarkus? 


The blog entry [Experimental GraphQL](https://quarkus.io/blog/experimental_graphql/#events-and-custom-execution) states that it is possible with `@Observes GraphQLSchema.Builder`. But I have no idea how to implement a subscription with a `GraphQLSchema.Builder` in my hand, and I cannot match it to the examples on the GraphQL-Java site.

Can you hint me a direction for adding a subscription implementation?

**Comment by phillip-kruger** [comment]
I am busy with the implementation and it should be available soon. You should be able to just build it in graphql-java as well, as the library is available

**Comment by thomas-ferchau** [comment]
@phillip-kruger, thank you, that sounds like good news - looking forward to it :-)

Meanwhile I adapted an example from graphql-java and created a simple subscription servlet that is unrelated to the rest of the GraphQL implementation.

**Comment by phillip-kruger** [comment]
Awesome !

**Comment by phillip-kruger** [comment]
Initial support added in #777
