### ISSUE TITLE
Test DataFetcherService (SPI) with Wildfly and OpenLiberty

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#497]
Make sure app servers that hosts multiple apps works correctly with the new DataFetcherService

**Comment by jmartisk** [comment]
Tested running multiple applications with async operations in WildFly, it seems to work well, except we need to improve the typesafe client to properly support async operations (I filed https://github.com/smallrye/smallrye-graphql/issues/501)
