### ISSUE TITLE
Async support in the typesafe client

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#501]
When calling an operation that returns a `CompletionStage<X>`, the client doesn't extract the set of fields of `X`, so it requests an empty set of fields, like for example
```
  {"query":"query foo { foo {} }","variables":{},"operationName":"foo"}
```

where the `foo {}` is a syntax error

**Comment by jmartisk** [comment]
@t1 would you be able to have a look at this?

**Comment by t1** [comment]
I assume that building the right request is the easy part ;-)

I mainly work in enterprise projects and we don't have use much async there; developer productivity is more important than top notch performance. I'd personally rather wait for Project Loom to solve all problems of the world ;-) But feel free to add async support.

**Comment by jmartisk** [comment]
I will look into it and ask for your help if I need it for understanding the client code ;)

**Comment by t1** [comment]
I'd be happy to support you and hear where my code is difficult to understand.
