### ISSUE TITLE
@Input not working on model object

### ISSUE THREAD

**Issue by michaelsonnleitner** [smallrye/smallrye-graphql#504]
I have follow model class

```
@org.eclipse.microprofile.graphql.Input("PersonType")
public class Person {
    public long id;
}
```

my graphql.schema looks like:
```
type Person {
  id: BigInteger!
}
```

Why is following not generated?
```
type PersonType {
  id: BigInteger!
}
```

**Comment by phillip-kruger** [comment]
Hi @michaelsonnleitner :
`@Input` is used for generating Input Types, so if you pass Person in a method as an argument, the schema will have:
```
input Person {
  id: BigInteger!
}
```
To name a Type (output) you can use the `@Type` annotation.

**Comment by michaelsonnleitner** [comment]
oh thank you. so I close this issue.
