### ISSUE TITLE
CompletableFuture with Wrapped GraphQLException does not show message to client

### ISSUE THREAD

**Issue by michaelsonnleitner** [smallrye/smallrye-graphql#515]
I have the following Resolver which calles a backendService which throws an Exception. 
```
@Query
    public CompletableFuture<Person> getPerson(long id) throws InterruptedException {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return backendService.getPerson(id);
            } catch (Exception e) {
                throw new CompletionException(new GraphQLException(e.getMessage(), e, GraphQLException.ExceptionType.DataFetchingException))
            }
        });
    }
```

```
{
	"message": "Server Error",
	"locations": [
		{
			"line": 13,
			"column": 9
		}
	],
	"path": [
		"person"
	],
	"extensions": {
		"exception": "java.util.concurrent.CompletionException",
		"classification": "DataFetchingException",
		"code": "completion"
	}
}
```

I want to add more information to the error object (eg. the Message of my Exception) How can I do that?

**Comment by phillip-kruger** [comment]
Thanks for this @michaelsonnleitner - We will need to add some code to unwrap CompletionException. I will add that as part of the code that I am busy changing. Thanks

**Comment by michaelsonnleitner** [comment]
is it somehow possible to turn partital responses off?

**Comment by phillip-kruger** [comment]
You mean do not add any data in the response, only error ?

**Comment by michaelsonnleitner** [comment]
I mean if at least one path of the complete graphql req. can not be resolved because of a problem....

**Comment by phillip-kruger** [comment]
Yes, as per the graphql spec: https://spec.graphql.org/draft/#sec-Response-Format. The response will contain errors id there was any errors....

**Comment by michaelsonnleitner** [comment]
hello!

i testet with 1.0.16 but it does not work because of following Exception hierachie which my container is doing. any suggestions?

![image](https://user-images.githubusercontent.com/65229544/99940900-60951400-2d6d-11eb-8857-b97fb40f6d98.png)

**Comment by phillip-kruger** [comment]
Maybe because it's also wrapped in a EJBException ? Try adding this property and see:

`smallrye.graphql.unwrapExceptions=javax.ejb.EJBException`

Let me know if that work. We can add the to the default too (to auto unwrap EJBException)

**Comment by michaelsonnleitner** [comment]
the problem is following structure:

```
CompletionException
---EJBExcption
------CompletionException
---------GraphQLException
```

which gets handeled here

![Uploading image.png…]()

**Comment by phillip-kruger** [comment]
So it unwraps as a EJBException in your case ? What response are you getting ? Seems like we need to recursively apply this logic.

**Comment by michaelsonnleitner** [comment]
yes it does.
recursivly would fix my problem ;)

**Comment by phillip-kruger** [comment]
Reopening issue to add recursive.

**Comment by t1** [comment]
`if` → `while` should do the trick ;-)
