### ISSUE TITLE
`mp.graphql.showErrorMessage` - wildcard

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#519]
For larger projects it would be very convenient to configure a wildcard like `mp.graphql.showErrorMessage=com.superheroes.*` to match all exceptions in a package and sub-packages.

Analogous for `mp.graphql.hideErrorMessage`.

**Comment by noon2a** [comment]
.

**Comment by parsharma** [comment]
Hi @t1,
Are you working on this issue? Could I give it a try?

Thanks

**Comment by t1** [comment]
No, I don't... just go ahead!

**Comment by parsharma** [comment]
Thanks, Could you please give me some more details about it?

**Comment by phillip-kruger** [comment]
So a.f.a.i.k, at the moment, to add exceptions on the hide or show list, you need the full package class name(s).
This feature will allow you to use wildcards. Possibly we should just support regex and use pattern matching ? @t1 - does that some this up ?

**Comment by t1** [comment]
I hadn't considered regex. It's definitively more powerful and could come in handy, but it could also lead to confusion, e.g. that `foo.*` also matches classes in a package `foobar`. Do you see regex often in config strings? We also could start simple and add some form of expressions only when we really need it; something like `foo.${regex:.*}`. What do you think?

**Comment by phillip-kruger** [comment]
I am easy, agree we can add regex later. @parsharma - Is this enough so you can work on this ?
