### ISSUE TITLE
`Integer` parameter

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#528]
I have a `@Query public String foo(Integer i) { ... }`. I can call it with `query foo { foo(i: 23)}`, but when I request it with `query foo($i: Int) { foo(i: $i)}` with `variables` set to `{"i": 123}`, I get a `IllegalArgumentException` because the argument is a `BigDecimal`.

BTW: everything works fine if the service takes a primitive `int` (you only have to use `Int!` for the parameter type).

**Comment by phillip-kruger** [comment]
mmm. That is a bug. I wonder if only String work ? All Scalars must work and complex types....
I think we need some more tests around variables....

**Comment by phillip-kruger** [comment]
@t1 - Are you working on this ?

**Comment by t1** [comment]
I took a short peek, but I'm not deep enough into this code base to see it quickly. There should also be a test in the tck, shouldn't it? I will have to take a deeper dive there, too... but not now, sorry.

**Comment by t1** [comment]
...and the problem is the `Integer` not the `String`

**Comment by phillip-kruger** [comment]
No problem, I am moving it to 1.0.17....

**Comment by phillip-kruger** [comment]
@t1 what are you using to test here ? GraphiQL ? And running on ? Wildfly ? Quarkus ?

**Comment by t1** [comment]
The service is running in WildFly 20. For the client I've tried the typesafe client, GraphiQL, and the IntelliJ GraphQL plugin.
