### ISSUE TITLE
Using FederatedTracingInstrumentation  on Quarkus / Smallrye environment

### ISSUE THREAD

**Issue by giuseppeparello** [smallrye/smallrye-graphql#532]
I' m working within a federation environment with an Apollo Gateway and Quarkus microservice. What i'm tryng to do is to use the FederatedTracingInstrumentation from the federation-graphql-java-support library inside the quarkus microservice. This instrumentation is used to send metric to the apollo gateway.

Is it possible to use com.apollographql.federation.graphqljava.tracing.FederatedTracingInstrumentation inside the metod:

public void beforeExecute(@Observes @BeforeExecute  Context context) {

}

Using the smallrye-graphql annotation (@Query) i cannot found a way to customize instrumentation using FederatedTracingInstrumentation

**Comment by phillip-kruger** [comment]
I added an event that allows you to take part in the building of GraphQL Object:

```
public GraphQL.Builder leakyAbstraction(@Observes GraphQL.Builder builder) {
        System.err.println(">>>>>>> Here we leak while building graphQL");
        // Do what you have to do
        return builder;
    }
```
