### ISSUE TITLE
Support JsonP objects

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#550]
Allow users to use JsonP objects as Types ?

```
@Query
public JsonObject myquery(String id){
///....
}
```
possibly just returning as `String`

**Comment by t1** [comment]
What schema would that produce?

**Comment by phillip-kruger** [comment]
String ?

**Comment by t1** [comment]
Okay, now I get your point! But does this add real value?

**Comment by phillip-kruger** [comment]
I wanted it in a small person project. Might not be enough value, but, when using JAX-RS, you can return a JsonObject, so I think we might as well also support it.

**Comment by t1** [comment]
Yeah, but JAX-RS doesn't provide a Schema. You'll need OpenAPI for that. And I think that's not only a big difference, it's also a big benefit of GraphQL over REST. I'd rather have #400 :-)

**Comment by phillip-kruger** [comment]
You mean in terms of priority ?

**Comment by t1** [comment]
I was rather thinking about feature bloat: I think the benefits of type safety should not be ignored too easily. You should ask yourself: why do you need generic types? Unions often are a perfect solution to cases where you might spontaneously think that you need to return something generic.

To put it differently: whenever you think you need it, you can go down the JSON-String path, but if you have to encode it manually, it may trigger you to wonder if this is really the best way you can go... if this is really GraphQL-like.

**Comment by phillip-kruger** [comment]
I my case it was more a case that I need to get json (JWT token) and writing everything using GraphQL, however, for that I need JAX-RS. I could create a JWT Object that should create the same effect I guess. Let's discuss in the next meeting.

**Comment by phillip-kruger** [comment]
So, seems like this is already working.... I added some test cases for this. closing the issue.
