### ISSUE TITLE
Request with the client returns 500: VariableTypeMismatch

### ISSUE THREAD

**Issue by Nillkki** [smallrye/smallrye-graphql#583]
Hi!

I am trying to use the GraphQL client but when making request I get an 500 error about `VariableTypeMismatch`. Can not tell if this is due to the client or the service I'm trying to query.

Client sends the following data: `{ "query": "query pattern($id: String) { pattern(id: $id) {name} }", "variables": {"id":"HSL:1059:0:01"}, "operationName": "pattern" }` but if I manually modify and send the request as `{ "query": "query pattern($id: String!) { pattern(id: $id) { name } }", "variables": {"id":"HSL:1059:0:01"}, "operationName": "pattern" }`

Looking at the schema, there is an exclamation mark for the pattern query. Any help would be appreciated!

**To Reproduce**
I made an example about the issue: https://github.com/Nillkki/quarkus-smallrye-graphql-example

Can be ran with `./mvnw verify`

**Comment by t1** [comment]
hmm..... the schema requires `pattern(id: String!): Pattern`, but the `@GraphqlQuery` annotation requests `query pattern($id: String) {...}`. Simply add the `!` to your query, and it should work... or do I get something wrong?

**Comment by Nillkki** [comment]
That works! Thank you very much!
