### ISSUE TITLE
NoClassDefFoundError in DefaultDataFetcher

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#587]
When I don't have MP Context Propagation on the classpath, I get a `NoClassDefFoundError` from the `DefaultDataFetcher`, which has a hard dependency.

**Comment by jmartisk** [comment]
Context Propagation is now a required dependency. We talked about this in https://github.com/smallrye/smallrye-graphql/issues/567 so I think this will not be fixed.

**Comment by t1** [comment]
so this is a duplicate... closing
