### ISSUE TITLE
power-annotations Mixin example doesn't work

### ISSUE THREAD

**Issue by vargadan** [smallrye/smallrye-graphql#588]
Hello

I'm trying to get power-annotations working and figured that the provided Mixin example (which would be a killer feature by the way) fails with "annotation type not applicable to this kind of declaration" because @org.eclipse.microprofile.graphql.Id cannot be applied to classes.
```
@MixinFor(javax.persistence.Id.class)
@org.eclipse.microprofile.graphql.Id
public class PersistenceIdMixin {}
```
However, based on the examples in the TCK I tried with:
```
@MixinFor(javax.persistence.Id.class)
public class IdMixin {
    @org.eclipse.microprofile.graphql.Id String id;
}
```
Yet, this also fails:
Caused by: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.FieldInfo.declaringClass()" because "targetField" is null
    at com.github.t1.powerannotations.common.MixinResolver.resolveFieldMixin (MixinResolver.java:74)
    at com.github.t1.powerannotations.common.MixinResolver.resolveMixinAnnotations (MixinResolver.java:56)

Seems to me that there is either a bug in the MixinResolver or it's just not clearly explained how to use annotation mixins.

**Comment by phillip-kruger** [comment]
@t1

**Comment by t1** [comment]
I'm going to take a look into this as soon as I can. I'm really glad for the first feedback, so I definitely will.

> which would be a killer feature by the way

It would be a super-killer feature if all JEE+MP standards would require implementations to support it ;-)
