### ISSUE TITLE
Batch: CompletionException can not be unpacked

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#590]
I have a batch resolver that throws an exception. The response then contains for every entry the same error (which is okay), but it's only a `java.util.concurrent.CompletionException` with error code `completion`, but I need access to the exception that caused the failure. It doesn't help to add the `CompletionException` to the `smallrye.graphql.unwrapExceptions` config.

**Comment by phillip-kruger** [comment]
Are you fixing this ?

**Comment by phillip-kruger** [comment]
@t1 - do you have a reproducer, I want to look at fixing this

**Comment by t1** [comment]
I have it only nested in our application, but it would be something like this:

```java
public List<Location> location(@Source List<SuperHero> heroes) {
    throw new RuntimeException();
}
```

I think unwrapping the `CompletionException` should be okay for everybody: I can't think of any use case for seeing this technical detail. If someone objects, using the `smallrye.graphql.unwrapException` would be a fallback.

**Comment by phillip-kruger** [comment]
@t1 - Thanks, yes we do unwrap when not batch, so this is a batch specific issue. I'll have a look
Thanks :)

**Comment by phillip-kruger** [comment]
@t1 - I am battling to fix this. Have tried multiple approaches, but get stuck .... need to think about this a bit more....I am moving this to 1.0.22 (I need to do a release, and I am not going to be in time to get this in).

If you have any ideas, please let me know...
