### ISSUE TITLE
Batched queries are always cached by underlying implementation

### ISSUE THREAD

**Issue by snuxoll** [smallrye/smallrye-graphql#592]
graphql-java caches queries resolved by a BatchLoader by default, which caused me much confusion working on a prototype using smallrye until I started digging through the call stack when debugging to figure out why my queries were only getting execution once. Smallrye should either disable the caching entirely when creating the BatchLoader or make it configurable.

Some personal input: I think having the GraphQL implementation handle caching at all puts this logic at completely the wrong level, outside of developer control, so I believe disabling caching entirely and making this non-configurable is the ideal solution.

**Comment by snuxoll** [comment]
@phillip-kruger it caches the results of the query. I can write a minimal sample, but any query that takes a `@Source` annotated list reproduces this behavior - just set a breakpoint in your debugger, it will hit the first time and then won’t again until you manage to get the results evicted from graphql-java’s internal cache.

**Comment by phillip-kruger** [comment]
Yea that does not sound right at all. Result caching should be done by the developer, typically with `@Cache` for example in Quarkus. I'll investigate. Thanks.

**Comment by snuxoll** [comment]
https://github.com/smallrye/smallrye-graphql/blob/4484cc6de6634fab8466875b3171f8a671f927d9/server/implementation/src/main/java/io/smallrye/graphql/bootstrap/Bootstrap.java#L727

The issue is here I’m guessing, batches queries are the only place smallrye uses DataLoader’s and caching is enabled by default - calling setCaching(false) on the DataLoaderOptions should be sufficient.

**Comment by snuxoll** [comment]
Actually, I'm totally wrong with where the problem lies. The DataLoader cache is doing exactly what we'd want it to do, if a source object was retrieved by multiple different parent queries the internal cache would prevent re-fetching of the same data within the request. Or at least, it would - but smallrye only constructs a single global GraphQL instance in the `@ApplicationScope`d ExecutionService bean here https://github.com/smallrye/smallrye-graphql/blob/4484cc6de6634fab8466875b3171f8a671f927d9/server/implementation/src/main/java/io/smallrye/graphql/execution/ExecutionService.java#L192 - meaning the cache gets shared between all requests.

**Comment by phillip-kruger** [comment]
Hi @snuxoll - thatnks for the investigation and details ! 
You are welcome to fix and do a PR ? Else I will do this a.s.a.p.

**Comment by snuxoll** [comment]
<img width="2605" alt="Screen Shot 2021-01-14 at 10 24 19 AM" src="https://user-images.githubusercontent.com/36403/104626226-dffae180-5652-11eb-82c0-6aab56ccc284.png">

Okay, well - that only got us part way there after doing some more debugging. I cherry-picked this commit onto the 1.0.20 tag and reproduced the issue still. Upon further inspection, it seems the hole goes deeper and the DataLoaderRegistry itself seems to be what's caching DataLoaders and their results (see the screenshot from my debug session above, this is at the start of execution for a second query - notice how the DataLoaderRegistry already has future's cached before execution has even begun).

**Comment by phillip-kruger** [comment]
Hi @snuxoll ! Thanks for the feedback, this is awesome. Ok, let's see what we can do there ....

**Comment by phillip-kruger** [comment]
Again - you are welcome to propose a fix in a PR :)

**Comment by snuxoll** [comment]
@phillip-kruger I'd be happy to take a stab at it, but given the ExecutionService is currently built around having the DataLoaderRegistry passed into it, and Bootstrap is responsible for configuring it there would need to be some rethinking of how and where these components connect to each other.

**Comment by phillip-kruger** [comment]
@snuxoll - no worries I can also have a look. Maybe you can share the reproducer ?

**Comment by snuxoll** [comment]
Here's a reproducable example: https://github.com/snuxoll/smallrye-graphql-cache-example

**Comment by phillip-kruger** [comment]
Thanks @snuxoll - I'll have a look a.s.a.p.
