### ISSUE TITLE
Support custom directive

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#628]
see https://github.com/eclipse/microprofile-graphql/issues/344

**Comment by t1** [comment]
@KSmigielski : I need this for #521. Have you already started? Otherwise I will start working on this now.

**Comment by t1** [comment]
We don't have full support, yet; just type directives. We at least need also field directives. I haven't considered the other possible locations and if they make sense in MP GraphQL. Reopening.

**Comment by t1** [comment]
I think we can close this when #810 has been merged. If locations other than type and field become necessary in the future, we can open a new issue.
