### ISSUE TITLE
Bean validation does not seem to work

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#636]
While playing with an API, I noticed that `@Email` does not seem to work.
Seems like top level works ok, eg:

```
@Mutation
    public String email(@Email String email){
        return email;
    }
```

But as soon as an POJO contain bean validation fields, validation is not applied.

Also maybe `javax.validation.ValidationException` should be on the default accept (show) error list even though it's a Runtime Exception

**Comment by t1** [comment]
IIRC you have to put `@Valid` on the POJO param, at least that's what you have to do in JAX-RS.

I'm very much in favor of showing the validation message. I'd even like to have the full details in the extensions, so a GUI client could properly display validation errors.

**Comment by phillip-kruger** [comment]
Yes !! I forgot that. Great ! Thanks. It is actually working :) Sorry about the false alarm :) Closing....
