### ISSUE TITLE
Issue with GraphQLClientApi Mutation

### ISSUE THREAD

**Issue by skallio** [smallrye/smallrye-graphql#654]
I have a simple GraphQL server and a Kotlin client as follows:

```
@ApplicationScoped
class PeopleService(
    @ConfigProperty(name = "people.graphql.url")
    private val peopleApiUrl: String
) {

    var peopleApi: PeopleApi = GraphQlClientBuilder.newBuilder()
        .endpoint(peopleApiUrl)
        .build(PeopleApi::class.java)

    fun getPerson(ssn: String): Person = peopleApi.person(ssn)
    fun createPerson(person: PeopleApi.PersonData): PeopleApi.PersonData = peopleApi.createPerson(person)
}

@GraphQlClientApi
interface PeopleApi {
    @Query
    fun person(
        @Name("id") id: String,
    ): Person

    @Mutation(value = "createPerson")
    fun createPerson(
        @Name("personDetails")
        personDetails: PersonData
    ): PersonData

    @Input
    data class PersonData(
        var firstNames: String,
        var lastName: String,
    )
}
```
The server works when using the graphql-ui with the mutation:
```
mutation addKalle {
  createPerson(personDetails: {
    firstNames: "Kalervo", 
    lastName: "Jankko"
  }) {
    firstNames
    lastName
  }
}
```
But my Kotlin client does not send the same mutation. This is what comes to the server log:

```
2021-02-24 20:12:36,859 DEBUG [not.gra.GraphQL] (vert.x-worker-thread-15) Executing request. operation name: 'createPerson'. query: 'mutation createPerson($personDetails: ) { createPerson(personDetails: $personDetails) {firstNames lastName} }'. variables '{personDetails={lastName=Jankko, firstNames=Kalervo}}'
2021-02-24 20:12:36,859 DEBUG [not.gra.GraphQL] (vert.x-worker-thread-15) Parsing query: 'mutation createPerson($personDetails: ) { createPerson(personDetails: $personDetails) {firstNames lastName} }'...
2021-02-24 20:12:36,860 WARN  [not.gra.GraphQL] (vert.x-worker-thread-15) Query failed to parse : 'mutation createPerson($personDetails: ) { createPerson(personDetails: $personDetails) {firstNames lastName} }'

```
Why the name createPerson is there twice?

When debugging the client I also noticed that in io.smallrye.graphql.client.typesafe.impl.QueryBuilder

```
   private String declare(ParameterInfo parameter) {
        return "$" + parameter.getName() + ": " + parameter.graphQlInputTypeName();
    }
```

graphQlInputTypeName is an empty string..

The query of my Kotlin client works fine against the server. How to make the mutation work?

**Comment by phillip-kruger** [comment]
@t1 @jmartisk

**Comment by t1** [comment]
I remember that Kotlin handles annotations a little bit different from Java (e.g. [here](https://stackoverflow.com/questions/52079539/junit-5-test-with-a-field-annotated-as-registerextension-doesnt-work-in-kotl/52079540)). Maybe you need to add a `@JvmField` annotation somewhere or something like that. The strange thing is that the type turns out to be an empty string without throwing an exception. If you find out what you have to do, I could add a hint to an exception message.

> Why the name createPerson is there twice?

The first one is the alias, i.e. `addKalle` in your hand written request. The second is the actual method being invoked.

Note that the personDetails will be different on every request, so it's better to put them into the `variables`, as the typesafe client does. Otherwise the server won't be able to cache the query and will have to parse it every time.

**Comment by skallio** [comment]
Thanks. I couldn't figure out where to add `@JvmField` but I tried to convert my GraphQlClientApi interface to Java. I have exactly the same problem with the following Java interface. The query works but the mutation generates the same invalid graphql as above.
```
@GraphQlClientApi
public interface PeopleApi {
    @Query
    Person getPerson(@Name("ssn")String ssn);

    @Mutation
    Person createPerson(@Name("personDetails") PersonData personDetails);


```

**Comment by t1** [comment]
I've tried to reproduce it, even with Kotlin, but everything worked as expected. Could you provide a little demo showing only the client side problem? We don't need the service, as the query is logged before the call is actually done.

**Comment by skallio** [comment]
Thank you. I was able to isolate the issue in a small example:
https://github.com/skallio/graphql-person-client

The issue seems to appear when using the @Input annotation in the input data class. See the two commits https://github.com/skallio/graphql-person-client/commit/a883d05199d19f52ad10f23f4160c43aece39f0b. The first one generates valid graphql, the second one does not.

**Comment by t1** [comment]
Okay, I see. So this is a bug. I will fix it. As a workaround, you can simply omit the `@Input`; it's not needed here. It's only required if you want to explicitly specify the input name.
