### ISSUE TITLE
Enrich schema at runtime dynamically

### ISSUE THREAD

**Issue by benlammel** [smallrye/smallrye-graphql#661]
I was wondering if it is possible to enrich the schema at runtime dynamically.

Scenario: 
multi-tenancy environment.
Tenant is identified by path param (uri) or value/variable in query.

Every tenant has the same basic "hard coded" schema artefacts but can create/model more types (therefore also query and mutation ops) dynamically, which are saved in a dedicated data storage.

So, the schema needs to be rebuilt dynamically (without restarting) for every tenant at the time of querying.
Of corse, just rebuilding if something has changed (timestamp) otherwise take the cached one.

As what I have seen in the code so far, the schema is built at boot time and does not have a hook for extending it at run/query time.
I also checked the experimental events, but they're also just covering schema manipulation at boot time.

Any chance that this scenario could be picked up?

Thanks & cheers!

**Comment by t1** [comment]
I guess adding a fully dynamic schema would be very difficult to build in, as smallrye-graphql binds to Java classes; so also the execution would need to be routed differently. This is a completely different concept.

Maybe it would be better to write something based directly on graphql-java or so.

OTOH it might be possible that your use-case could be served with GraphQL Federation, which we plan to support as downstream services (#521).

**Comment by benlammel** [comment]
thanks for your reply. I totally understand that this follows a different concept.
I'll definitely subscribe to the federation enhancement.

**Comment by phillip-kruger** [comment]
You can get hold of the underlying graphql-java and try and do it there. Or if everything is dynamic, just use that.
