### ISSUE TITLE
Unspecific error message when `beans.xml` is missing

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#679]
When I query a simple GraphQL war without a `beans.xml` on WildFly, I get an exception `SRGQL012000: Data Fetching Error: org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001334: Unsatisfied dependencies for type Boundary with qualifiers`.

It would be nicer to get an exception that indicates the cause of the problem or even better: to check this at deploy time.

**Comment by jmartisk** [comment]
Good point, I suppose it should be possible to detect that a GraphQL deployment does not have `beans.xml`  - I tend to think the best would be to log a warning in this case, because without it, it's almost certain that GraphQL queries will not work.

**Comment by t1** [comment]
I'd prefer the deployment to fail early if it won't work anyway. A warning is not strong enough indicator that something is broken.

**Comment by jmartisk** [comment]
I have an idea how we can do this, basically we can collect all owning classes of all GraphQL operations and verify that each such class is injectable. This can be done during bootstrap.

In Quarkus, beans.xml is not necessary in the application, but we can still verify that the owning classes are injectable (they might be `@Vetoed` for example).

I'll send a PR in a bit
