### ISSUE TITLE
Implement all "Serving over HTTP" use cases (e.g. HTTP GET, HTTP POST application/graphql)

### ISSUE THREAD

**Issue by marceloverdijk** [smallrye/smallrye-graphql#69]
Looking at the source code `smallrye-graphql` currently only supports the basic `POST` use case.

As described on https://graphql.org/learn/serving-over-http/ there are more use cases:

- When receiving an HTTP GET request, the GraphQL query should be specified in the "query" query string.
- For HTTP POST requests, if the "query" query string parameter is present (as in the GET example above), it should be parsed and handled in the same way as the HTTP GET case.
- For HTTP POST requets, if the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

E.g. in the `micronaut-graphql` implementation we support all these use cases: https://github.com/micronaut-projects/micronaut-graphql/blob/master/graphql/src/main/java/io/micronaut/configuration/graphql/GraphQLController.java

If you are interested I could help out implementing these use cases.

Let me know.

**Comment by phillip-kruger** [comment]
Hi @marceloverdijk .
This is already added to master (or maybe just my fork) and will be in the next release. We Also discussed this in the last meeting (https://docs.google.com/document/d/1gb3jirFGrJwDZSbrtnFPVTNjPNe3Y0dUYfm-HkU1c3U/edit?usp=sharing) and will add more info on this in the specification and add some test cases for this. We will also allow disabling GET using config.

Thanks !

**Comment by phillip-kruger** [comment]
I am keeping this open, will close one this is released

**Comment by marceloverdijk** [comment]
Ah good to hear. I was on holiday last week, and looking at the code from my mobile and then it wasn't there yet :-) But indeed I see GET was added 4 days ago to `master` 👍 

I don't see the POST variants in `master` btw.

**Comment by phillip-kruger** [comment]
Yea, I'll discuss the POST Options in the next spec meeting. At the moment we only expect a body in the POST. That is also why the GET is configurable, as having the info in the query might be a security concern. (Caching proxies etc) We might change the configuration from allowGet to allowQueryParam or something ?

**Comment by marceloverdijk** [comment]
or both `allowGet` and `allowPostQueryParam`?
But good to hear it will be discussed.

**Comment by phillip-kruger** [comment]
Cool. Good idea. Thanks :)

**Comment by marceloverdijk** [comment]
I think I will add this configuration option to the `micronaut-graphql` integration as well :-)

**Comment by phillip-kruger** [comment]
Cool !

**Comment by phillip-kruger** [comment]
Also see https://github.com/APIs-guru/graphql-over-http

**Comment by t1** [comment]
I would like to configure to allow queries only via GET and mutations over POST. I know this is not standard GraphQL and tools like GraphiQL IIUC only use POST. But I currently need it to assign different roles to reading and writing requests.

**Comment by phillip-kruger** [comment]
Maybe we need a Annotation (Protocol Specific) that you can add on a method ? Something like:

```
@Query @HTTP(GET)
public SuperHero getSuperHero()....
```

That will only allow this on GET ?

And vice-versa for POST. And we allow both as well ? And then one day other protocols can have their own annotations ?

**Comment by t1** [comment]
Adding it to every `Query` and `Mutation` seems to be the wrong level of abstraction. I'd rather en/disable it for all. I don't yet have a good solution, though. Needs more thought, I guess.

**Comment by phillip-kruger** [comment]
Closing this. We can open other tickets if we still want fine grain control on what Queries can be exposed over get.

**Comment by marceloverdijk** [comment]
I believe below scenarios are not yet [implemented](https://github.com/smallrye/smallrye-graphql/blob/master/server/implementation-servlet/src/main/java/io/smallrye/graphql/servlet/ExecutionServlet.java#L76-L83):

- For HTTP POST requests, if the "query" query string parameter is present (as in the GET example above), it should be parsed and handled in the same way as the HTTP GET case.
- For HTTP POST requets, if the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

Should I create a new issue for that?

**Comment by phillip-kruger** [comment]
Yes please :)
