### ISSUE TITLE
Getters aren't recognised correctly

### ISSUE THREAD

**Issue by ybroeker** [smallrye/smallrye-graphql#702]
Currently, all methods that start with `get` and a following capital letter are recognised as getters, regardless of parameters. Something like, for example, (Map's) `getOrDefault(K key, V value)` is added to the schema as `orDefault`, but at runtime it is (correctly) ignored.
Such methods shouldn't be added to the schema.

**Comment by ybroeker** [comment]
Similarly for setters. `setX()` causes an exception while building the schema, `setX(Y y, Z z)` is added to the schema as `Y: y` but ignored at runtime.

**Comment by phillip-kruger** [comment]
mmm, good point. Not sure how to fix this ? Do you have any ideas ?

**Comment by ybroeker** [comment]
Submitted an PR with #715 :)
