### ISSUE TITLE
Support for Java 16 records

### ISSUE THREAD

**Issue by ybroeker** [smallrye/smallrye-graphql#704]
Records would be super useful for Types (and maybe also inputs).

Currently, a (actually superfluous) explicit getter has to be added for each record component. It would be better if records were supported "out of the box".

Only the schema builder would have to be adapted, the Java version would not have to be adapted and could remain at 8.

----

An alternative (or an additional possibility) would be to be able to mark methods with annotations as fields, e.g. with `@Query`. A method `@Query public field()` (in a non-`@GraphQLApi` class) would then add the field `field`. This could be used together with records, but would also offer the possibility to be used in "normal" classes.

**Comment by phillip-kruger** [comment]
Agree. The alternative has been discussed before (I know SPQR works like that).

**Comment by t1** [comment]
I just had a second thought about this: is `@Query` the right annotation for this? Why not also `@Mutation`? Or shouldn't those two be reserved for the root `Query`/`Mutation` types? We could add a new `@Field` annotation. I think this could be more clear for users.

**Comment by phillip-kruger** [comment]
I think we can close this one. If I am wrong please re-open

**Comment by robp94** [comment]
The support for records is only for the server types, inputs and on the client side they seem not to be supported. Could this be added?

**Comment by t1** [comment]
Yeah, that makes sense. Could you open a new issue?
