### ISSUE TITLE
Support for @JsonbCreator (or similar mechanisms)

### ISSUE THREAD

**Issue by ybroeker** [smallrye/smallrye-graphql#705]
Currently, a public field/setter must exist for each field of inputs.

It would be nice if `JsonbCreator` or a similar mechanism was supported. Instead of explicit setters, a constructor or a factory method would then suffice.

Also, until explicit support is available, it would allow to use records as inputs.

**Comment by phillip-kruger** [comment]
public fields also work. But I agress JsonbCreator would be a good addition :) PR ?

**Comment by ybroeker** [comment]
Currently @JsonbCreator is even already supported (by accident) in some cases.

I'll have a look at that :)
