### ISSUE TITLE
Build Schema at Build-Time

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#709]
Maybe this is just a crazy idea that means a complete rewrite, but wouldn't it be possible to build the full GraphQL Schema in, say, a Maven Plugin? I think this would reduce startup time and memory footprint.

**Comment by phillip-kruger** [comment]
You mean on the server-side ? Or client ? Server side already has a maven plugin and in Quarkus most of the work is done on build time

**Comment by t1** [comment]
Sorry, I forgot completely about the build tools. Stupid me.

**Comment by t1** [comment]
Hmmm... but at least for a `war` it's not being added to the `war` nor is there a mechanism to load an existing schema file instead of scanning again, is there?

**Comment by phillip-kruger** [comment]
Why do you want to add it to the war ? You might be able to add it to the war yourself as part of the build.

**Comment by t1** [comment]
I'd add it to the war only so that the scanning at startup was faster, but I understand that this is currently not possible.

**Comment by phillip-kruger** [comment]
Is it slow at the moment ? Problem is that you need to tie the dataloaders to the schema, and that happens at startup.

**Comment by t1** [comment]
Yeah, the startup time is not optimal, but acceptable. I think we have more important things to work on 😄
