### ISSUE TITLE
Application without any `@Query` fails

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#717]
Edge case: if there are no queries but only mutations in an applications, the schema validation fails:

`graphql.schema.validation.InvalidSchemaException: invalid schema: "Query" must define one or more fields.`

**Comment by phillip-kruger** [comment]
This is correct spec behavior (and the error comes from graphql-java) see 
https://spec.graphql.org/June2018/#sec-Root-Operation-Types

> The query root operation type must be provided and must be an Object type.
> 
> The mutation root operation type is optional; if it is not provided, the service does not support mutations. If it is provided, it must be an Object type.

Closing :)
