### ISSUE TITLE
Schema doesn't include parent class fields

### ISSUE THREAD

**Issue by bpalermo** [smallrye/smallrye-graphql#72]
I have the following JPA classes:

```java
@XmlTransient
@XmlAccessorType(XmlAccessType.FIELD)
@MappedSuperclass
public abstract class AbstractEntity {

    @Getter
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    public Long id;

}
```
This class extends the abstract parent class.

```java
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@Table(name = "person")
public class Person extends AbstractEntity {

    @Getter @Setter
    private String name;

    @Getter @Setter
    @Column(name = "last_name")
    private String lastName;

    @Getter
    @OneToMany(mappedBy = "person", fetch = FetchType.EAGER)
    private Set<Book> books = new HashSet<>();

}
```

Generated `schema.graphql` bellow doen't include the `id` field:

```graphql
"Directs the executor to include this field or fragment only when the `if` argument is true"
directive @include(
    "Included when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Directs the executor to skip this field or fragment when the `if`'argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Marks the field or enum value as deprecated"
directive @deprecated(
    "The reason for the deprecation"
    reason: String! = "No longer supported"
  ) on FIELD_DEFINITION | ENUM_VALUE

type Book {
  name: String
}

"Mutation root"
type Mutation {
}

type Person {
  books: [Book]
  lastName: String
  name: String
}

"Query root"
type Query {
  people(limit: Int, offset: Int): [Person]
  "Get a person using the person's Id"
  person(id: BigInteger): Person
}
```

Thanks,
Bruno

**Comment by phillip-kruger** [comment]
Thanks for this @bpalermo . I'll look at this a.s.a.p.

**Comment by bpalermo** [comment]
@phillip-kruge, I would be glad to help!

**Comment by phillip-kruger** [comment]
Awesome ! Please go ahead !

**Comment by bpalermo** [comment]
Could you point me which class builds the schema?

**Comment by phillip-kruger** [comment]
It starts with [SmallRyeGraphQLBootstrap](https://github.com/smallrye/smallrye-graphql/blob/master/implementation/src/main/java/io/smallrye/graphql/bootstrap/SmallRyeGraphQLBootstrap.java) that get's (or creates) an Jandex index. The [GraphQLSchemaInitializer.java](https://github.com/smallrye/smallrye-graphql/blob/fa467f7b2763ee011ac8a5e55dcd7ffcb9f38ce0/implementation/src/main/java/io/smallrye/graphql/bootstrap/schema/GraphQLSchemaInitializer.java#L80) then kick of the process. 

I would think that smewhere in the OutputTypeCreator (https://github.com/smallrye/smallrye-graphql/blob/fa467f7b2763ee011ac8a5e55dcd7ffcb9f38ce0/implementation/src/main/java/io/smallrye/graphql/bootstrap/type/OutputTypeCreator.java#L99) we need to also check for super class, same way we check for interface.

Hope that helps. Please shout if you have any questions :)

**Comment by bpalermo** [comment]
Partial fix completed. PR available.

**Comment by t1** [comment]
PR #77 was merged. Can this issue be closed, then?

**Comment by bpalermo** [comment]
Yes, it can!

**Comment by phillip-kruger** [comment]
Cool
