### ISSUE TITLE
Rebase typesafe client on the dynamic client

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#725]
We talked about doing so, but I think we don't have an issue for it, yet.

**Comment by jmartisk** [comment]
Not sure how much reusable stuff there will be in the dynamic client, but I suppose we can at least
- unify error-related exceptions
- use `io.smallrye.graphql.client.core.Document` for building JSON requests in the typesafe client

and perhaps something more

**Comment by jmartisk** [comment]
I think we can consider this pretty much done for now, in the context of what we want to achieve for the 1.4 release

- error handling is unified between typesafe and dynamic
- logic for parsing of entities from JSON is shared 
- we use the same HTTP transport library (vert.x)
- Typesafe client does not yet use the core API classes (`Document` etc), I experimented with it but it didn't feel very practical (typesafe client performs quite low-level JSON operations), we might revisit that later
