### ISSUE TITLE
Double should be mapped as BigDecimal

### ISSUE THREAD

**Issue by Andro999b** [smallrye/smallrye-graphql#727]
In current implementation double fields loose precision because of `.floatValue()` conversion in [FloatScalar](https://github.com/smallrye/smallrye-graphql/blob/b69fe8649f880147b5bb7619d0157f1aa204e0bc/server/implementation/src/main/java/io/smallrye/graphql/scalar/number/FloatScalar.java#L32)

As example 49.9902794 rounded to 49.99028.

Double should be mapped as BigDecimal to avoid precision lost. As workaround for current impl `ToScalar` annotation can be used.

**Comment by phillip-kruger** [comment]
Thanks :) First I will suggest we fix the rounding, else we need to change the spec.

**Comment by netdragonboberb** [comment]
@phillip-kruger You can't fix the rounding. It's an inherent well-known limitation with floating point processors. You either have to use fuzzy comparisons or decimal. Usually it's no big deal, but for money, etc, it's a deal-breaker.

**Comment by phillip-kruger** [comment]
I was thinking to not use `.floatValue()` and use another mapping under the covers to map floats and doubles. So in GraphQL it will still be a float, but when you use Double in Java it should not map it to float, but rather a double. I'll look at this a.s.a.p

**Comment by Andro999b** [comment]
I think you should consider to switch float to double instead. Because GraphQL Float is corresponding to JS Number that size is 8bytes same as Java double.

**Comment by phillip-kruger** [comment]
That sounds like a plan.
