### ISSUE TITLE
Named injectable client instances

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#743]
I imagine having an injectable client like
```
@Inject
@NamedClient("my-named-client")
DynamicGraphQLClient client;
```

Where the client configuration (URL and other settings) would be configured by whatever configuration mechanisms (MP Config + `application.properties` for Quarkus, the management model (or just MP Config) for WildFly,...)

This definitely makes sense for the dynamic client, I'm not completely sure about the typesafe client, but maybe too (the thing is that the typesafe client's configuration is mostly derived from annotations, so we would need to find a reasonable way to  "merge" configuration from annotations with the configuration from the MP Config side).

**Comment by jmartisk** [comment]
I'm planning to start a prototype working with WildFly this week and then we will see :)

**Comment by phillip-kruger** [comment]
Nice! Thanks @jmartisk !

**Comment by jmartisk** [comment]
I didn't realize that pure MP Config doesn't have ConfigGroups like Quarkus does. And they would be very useful for creating the configuration model for clients, where you can have multiple named clients, and each of them contains a set of configuration values.

Of course we can use ConfigGroups for this in Quarkus, but most of the logic will then have to be directly in Quarkus, not SmallRye, unfortunately.
WildFly does not have anything like this, that will have to use the WF management model, which I was hoping to avoid at first, but it seems inevitable.

So my current thinking is that:
- SmallRye GraphQL will have a class named `NamedClientConfiguration` which contains all the config relevant to one client. This will be part of the public-facing API, so users can also use it programmatically if they want.
- SmallRye's client builder interfaces (`io.smallrye.graphql.client.typesafe.api.GraphQlClientBuilder` and `io.smallrye.graphql.client.dynamic.api.DynamicGraphQLClientBuilder`) will be enhanced to accept a `NamedClientConfiguration` for building a client
- Quarkus will use a ConfigGroup as an equivalent of this to allow the user to specify the config values, and, at build time, the ConfigGroup object will be converted to a `NamedClientConfiguration` instance.
- WildFly will, instead of ConfigGroups, use the WF management model, and the `NamedClientConfiguration` instance will be created at deployment time, from the information supplied in the management model. This will be the tough part for me, because I've never done something like this before :)
- In both Quarkus and WildFly, CDI producers will be created at deployment time, along with the client instances, and will allow them to be injected into the application.

Does this make sense?

**Comment by jmartisk** [comment]
Or maybe the `NamedClientConfiguration` class is not really needed (would unnecessarily complicate it) and we can convert the configured values straight into a client by using existing methods of the client builder classes.

**Comment by jmartisk** [comment]
Just for the record, in the end we decided to have a configuration strategy very similar to MP Rest Client (see https://github.com/eclipse/microprofile-rest-client/blob/microprofile-rest-client-1.1/spec/src/main/asciidoc/cdi.asciidoc#support-for-microprofile-config)

So, properties like
```
smallrye.graphql.client.client1/url=http://example.com/graphql
smallrye.graphql.client.client1/header/Authorization=Bearer abcd1234
```

**Comment by jmartisk** [comment]
done via https://github.com/smallrye/smallrye-graphql/pull/749
