### ISSUE TITLE
Unify configuration of clients

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#750]
Currently, the typesafe client's URL can be configured (unless you're doing it with annotations) using
`CLIENT_NAME/mp-graphql/url` 

The dynamic client is configured using
`smallrye.graphql.client.CLIENT_NAME/url`

I suppose this should be unified somehow

**Comment by jmartisk** [comment]
My opinion before opening this to discussion
- I rather prefer `smallrye.graphql` prefix (or `mp.graphql` if we want to make it seamlessly migrate to the spec later?)
- If there's a prefix like that, it seems redundant to add the `/mp-graphql` suffix
- Even though the sets of valid properties for dynamic and typesafe clients will possibly be different, I still think we can unify the config - meaning that it will not matter (from the config perspective) whether the client is typesafe or dynamic, the config prefix will be the same. Whether the client definition will actually be used for a dynamic or typesafe client would depend purely on the injection points in the application:

```
// this means the client named "example" is dynamic
@Inject
@NamedClient("example")
DynamicGraphQLClient client;

// this means the client named "example" is typesafe
@Inject
ExampleClient client;
```

**Comment by t1** [comment]
Just my 2 cent: the typesafe config options where aligned with the config options for the MP Rest Client.
I completely agree that they should be unified between typesafe and dynamic. Even more so as we plan to rebase the typesafe ontop of the dynamic client. And of course we plan to move both into the spec.
