### ISSUE TITLE
Clarify the role and name of the 'client/all' module after recent changes

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#751]
Right now, the `smallrye-graphql-client-all` module brings in the typesafe client, along with RESTEasy client used under the hood. Depending just on `smallrye-graphql-client-implementation-jaxrs` does not suffice to get *all* the dependencies, because RESTEasy client is not included. The reason for that is that we want to support plugging in different JAX-RS client implementations, like Jersey.

On the other hand, to get the dynamic client working, all the one needs is the `smallrye-graphql-client-implementation-jaxrs` module. The vert.x dependency is included, because Vert.x is the *only* supported library for the dynamic client, so there's no reason to do any such splitting.

So, to avoid confusion, the `smallrye-graphql-client-all` module somehow might need a different name - it's no longer "all" because it only contains the typesafe client. So, maybe `smallrye-graphql-client-jaxrs-all`, or `smallrye-graphql-client-typesafe-all`? We might later add support for dynamic client running through JAX-RS, so perhaps `jaxrs-all` would be better.

Another option would be to include the dynamic client (including Vert.x) into `smallrye-graphql-client-all` to really turn it into "all" again, but then it might get quite bloated...

So, options:
- Rename `smallrye-graphql-client-all` to `smallrye-graphql-client-typesafe-all` (probably not)
- Rename `smallrye-graphql-client-all` to `smallrye-graphql-client-jaxrs-all`
- Include `smallrye-graphql-client-implementation-vertx` as a dependency of  `smallrye-graphql-client-all`

**Comment by phillip-kruger** [comment]
Maybe a 4th option: Remove all module ? @t1 ?

**Comment by t1** [comment]
The `all` module is very handy, when you don't have a runtime that already brings all the dependencies, e.g. for testing. So I'd rather not remove it.

I think maybe we should postpone the decision until the typesafe client is rebased onto the dynamic client. If this runs with Vert.x, that's okay for me. E.g. in WildFly there's already a `smallrye-mutiny-vertx` module, so that should be used, I guess.

The merge may stir some things up and we may see our options more clearly.

**Comment by jmartisk** [comment]
If we changed the typesafe client to run with Vert.x rather than JAX-RS Client, then we wouldn't need the `all` module anymore, everything would be provided by `implementation-vertx`.
That is, unless we decide to keep the old JAX-RS variant too, in which case the JAX-RS variant could still be supplemented by a module that provides the actual JAX-RS client impl.

**Comment by t1** [comment]
If we only have one implementation, shouldn't we name it just `implementation`? The `-vertx` suffix would be irrelevant.

I think we have three scenarios:
1. A JEE container with built-in support for the client as well as Vert.x ⇒ the `war` only has a `provided` dependency on the `api`; the `api`, as well as the `implementation`, are implicitly added at runtime.
2. A JEE container with build-in support for Vert.x but not the client ⇒ the `war` has a `compile` dependency on the `api`, a `runtime` dependency on `implementation`, and a `provided` dependency on Vert.x, i.e. `api` and `implementation` are built into the `war`, while Vert.x is implicitly added at runtime.
3. Other runtimes or packaging formats, where dependencies are either packaged into a fat-jar, or managed by adding jars to some `lib` folder ⇒ the application has a `compile` dependency on the `api`, and a `runtime` dependency on the `implementation` as well as Vert.x; everything is added in the same way at runtime.

Is this classification helpful? Does it mean we need to provide three different modules?

**Comment by jmartisk** [comment]
The point of having separate `implementation-*` is that we might have multiple implementations in the future, which might not even be based on HTTP.
If we switch the typesafe client to using Vert.x and merge the `implementation` and `implementation-vertx` modules into just `implementation`, we run into a danger of having to split it again in the future...
I would say separating the "common" functionality from the transport protocol is a good thing.
Maybe we could consider renaming `implementation` module to `common`, or `core`.
