### ISSUE TITLE
Allow defining of default transformation via config, maybe per (Java) type

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#752]
```java
@GraphQLApi
public class Boundary {
	public @Query Instant now() {
		return Instant.now();
	}
}
```

returns (in smallrye-graphql-servlet 1.1.2)

```json
{
    "data": {
        "now": "2021-04-22T15:33:15.075929"
    }
}
```

In 1.1.0 it returned the correct format including the time zone `Z`.

**Comment by phillip-kruger** [comment]
Instant was never supported and worked because of toString. This is the change: https://github.com/smallrye/smallrye-graphql/pull/691

**Comment by phillip-kruger** [comment]
Closing as this is not a bug. This is how instant now works.

**Comment by t1** [comment]
But this is _wrong_! ;-) An instant should be parseable by `Instant.parse`, shouldn't it?

**Comment by phillip-kruger** [comment]
It maps to a DateTime in GraphQL, so no, not really.

**Comment by phillip-kruger** [comment]
As per normal DateTime, you can try to format (using @DateFormat) to the output you want, that will allow parsing from instant

**Comment by t1** [comment]
I didn't find a `DateTime` in the GraphQL spec; only in the section about [Serialization Format](https://spec.graphql.org/draft/#sec-Serialization-Format), it says that 'custom scalars representing a Date, Time, ... may be represented in whichever relevant format a given serialization format may support.' So we are left to our own concepts.

I know that time is a terribly complex issue. In Java it was absolutely horrible! Until the Java Time API was introduced. Do you refer to that? Then you'd have to decide if you want a `ZonedDateTime` or `LocalDateTime`. They have different semantics and shouldn't be interchanged easily. I can understand that an Instant can be seen as a subset of `ZonedDateTime` with the time zone `Z`. But dropping the time zone is just loosing an important detail.

**Comment by t1** [comment]
BTW: annotating the `@DateFormat` for every `Instant` is way to cumbersome.

**Comment by phillip-kruger** [comment]
DateTime is defined in the MP Spec. (Does not exist in GraphQL spec). Maybe we then need a way to, via config, define the global default DateFormat in for Dates ?

**Comment by t1** [comment]
That could help. Maybe even a separate one for the different Java Time types?

**Comment by phillip-kruger** [comment]
Cool. Let's add that to the TODO list :)

**Comment by t1** [comment]
I just found out that there's only a test for `LocalDate` in the TCK, not for the other date types mentioned in the MP spec: `(Local)DateTime`, `OffsetDateTime`, `ZonedDateTime`, `(Local)Time`, and `OffsetTime`.

`Instant` isn't mentioned in the MP spec, so I still consider it to be a bug to return a format without a fixed time zone `Z`! Even worse: annotating a direct query response type with `@DateFormat` throws: `SRGQL014000: Unable to transform data: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: YearOfEra`, so I can't fix it in this case. Only when I return a type containing an Instant can be annotated.

**Comment by t1** [comment]
I don't need this issue any more, but IIRC @phillip-kruger wanted to keep it open in case someone wants to configure date formats globally. Maybe we should mark such issues as `Ideas-for-the-future` or so?
