### ISSUE TITLE
Typesafe Client in Quarkus with `@Inject`

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#755]
In the [Supersonic Subatomic GraphQL](https://quarkus.io/blog/supersonic-subatomic-graphql/) quickstart, there's this snipptet:

```java
    //@Inject
    //PersonGraphQLClient personClient; or
    PersonGraphQLClient personClient = GraphQlClientBuilder.newBuilder().build(PersonGraphQLClient.class);
```

But `@Inject` doesn't work in Quarkus, does it? It works on Weld, but I have no idea about if/how this works in arc.

**Comment by phillip-kruger** [comment]
It will work in Quarkus once we create the extension. @jmartisk is working on that...

**Comment by t1** [comment]
Thanks! So I'm closing this, right?

**Comment by t1** [comment]
I didn't find a ticket for this that I could watch. Is there one?

**Comment by phillip-kruger** [comment]
You mean on Quarkus ?

**Comment by t1** [comment]
Yes

**Comment by phillip-kruger** [comment]
Yes there is none, @jmartisk maybe you can create one ?

**Comment by jmartisk** [comment]
I'm a bit busy with doing the very same thing for WildFly at the same time, but yeah :) 
I filed https://github.com/quarkusio/quarkus/issues/16792

**Comment by jmartisk** [comment]
It would also be good to finalize the discussion on https://github.com/smallrye/smallrye-graphql/issues/751 so we won't have to change the WF and Quarkus integration layers later.
