### ISSUE TITLE
Private getters are exposed unless @Ignore

### ISSUE THREAD

**Issue by piotrblasiak** [smallrye/smallrye-graphql#771]
Private fields are not, but getter - even static ones, are exposed. @Ignore fixes it.

**Comment by phillip-kruger** [comment]
This might already be fixed in main, see #719

Just needs to be released

**Comment by piotrblasiak** [comment]
Looks like it. Ok thanks and good work!

**Comment by phillip-kruger** [comment]
Closing as this is fix. Will be in 1.2.0
