### ISSUE TITLE
Error message logged in CollectionHelper

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#79]
I see a lot of `ERROR [io.smallrye.graphql.bootstrap.schema.helper.CollectionHelper] (default task-1) Can not create new collection of [java.util.Collections$SingletonList]` and `[java.util.Collections$UnmodifiableRandomAccessList]` messages in my logs. That's because the `CollectionHelper` has a leaky logic for determining what type to create.

A fix should not be very hard. I don't see any tests except for the TCK, so there's nothing to update there, is it? Should I go for a PR?

**Comment by phillip-kruger** [comment]
Yes please! You are also welcome to add tests, but yes so far all tests was in the TCK.
