### ISSUE TITLE
Exposing SmallRyeContext.documentSupplier 

### ISSUE THREAD

**Issue by computerlove** [smallrye/smallrye-graphql#790]
Is there any reasons `documentSupplier` is not exposed through the leaky abstraction? 
We are doing some custom logging of the incoming query that needs the parsed query.

Is there any reasons why the already parsed Document, or its supplier, should not be available through `SmallRyeContext.unwrap(Document/Supplier)`?

**Comment by phillip-kruger** [comment]
No real reason. We can definitely add that.

**Comment by computerlove** [comment]
That would be great :)
Should I make a PR?

Would the best approach be supporting `unwrap(Document.class)`? 
`unwrap(Document.class)` feels a little bit wrong because of type erasure and `Supplier` could be anything.

**Comment by phillip-kruger** [comment]
Yea Let's add Document to the classes we support ....

**Comment by phillip-kruger** [comment]
PR very welcome !

**Comment by computerlove** [comment]
PR #800 pushed. 
Not really sure if the access to the supplier needs to be thread safe, but it's not that complex.
Any ideas for other tests that should be added?
