### ISSUE TITLE
Provide more fluent APIs in ErrorOr

### ISSUE THREAD

**Issue by hantsy** [smallrye/smallrye-graphql#821]
Discussed in https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Exception.20handling.20in.20GraphQL/near/240804862

Hope to add some methods like `Optional.elseXXX` to handle the result in a *stream* like approach.

eg.

```java
.getOr(
data->{}, 
errors->{}
)
```

```java
.map( data -> {} )
.elseIfErrors(errors -> {} )
````

**Comment by t1** [comment]
There's a list of TODOs in the class already:

```
public void ifPresent(Consumer<? super T> action)
public void ifPresentOrElse(Consumer<? super T> action, Runnable emptyAction)
public Optional<T> filter(Predicate<? super T> predicate)
public <U> Optional<U> map(Function<? super T, ? extends U> mapper)
public <U> Optional<U> flatMap(Function<? super T, ? extends Optional<? extends U>> mapper)
public Optional<T> or(Supplier<? extends Optional<? extends T>> supplier)
public Stream<T> stream()
public T orElse(T other)
public T orElseGet(Supplier<? extends T> supplier)
public T orElseThrow()
public <X extends Throwable> T orElseThrow(Supplier<? extends X> exceptionSupplier) throws X
```

@hantsy : would those be sufficient for your use-case?

**Comment by hantsy** [comment]
@t1  Noticed it(I think this is `Optional` APIs.).  It is great.

**Comment by t1** [comment]
@hantsy: Yes, some methods where from `Optional`, but some didn't actually make any sense or would have been rather obscure. I prefer to wait for real use-cases. I just created a PR. Does that cover everything you need?

**Comment by t1** [comment]
I think the PR mentioned above has covered this... closing
