### ISSUE TITLE
GraphQLApi containing only subscriptions does not work

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#825]
You need at least one `@Query` or `@Mutation`, otherwise you will get
```
WARN: SRGQL010001: No GraphQL methods found. Try annotating your methods with @Query or @Mutation
```

**Comment by phillip-kruger** [comment]
See #717 

This is correct spec behavior (and the error comes from graphql-java) see 
https://spec.graphql.org/June2018/#sec-Root-Operation-Types

> The query root operation type must be provided and must be an Object type.
> 
> The mutation root operation type is optional; if it is not provided, the service does not support mutations. If it is provided, it must be an Object type.

**Comment by jmartisk** [comment]
Argh! 
Somewhat annoying, but ok then. I will have to add dummy queries in a lot of testing code.

**Comment by phillip-kruger** [comment]
Yea. It sucks
