### ISSUE TITLE
BeanValidation Directives

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#830]
Expose the BeanValidation annotations as GraphQL custom directives, e.g.:

```java
class Person {
    @Email String email;
}
```

```graphql
input Person {
    email: String @email
}
```

As the BeanValidation annotations are not under our control, we could use mixins (#316).

In addition to being documentation for client developers, e.g., a web app may use the directives to render the correct input type and validate it while the user is typing. I don't know if something like this is already being used in existing frontend frameworks.

**Comment by jmartisk** [comment]
This has been already implemented for some time (see https://smallrye.io/smallrye-graphql/2.0.1/directives/ for documentation), so we can close it
