### ISSUE TITLE
Clients should support `@DateFormat` and `@NumberFormat`

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#839]
Currently you can change the property name of a field when using JsonB annotations, but not when using the built-in GraphQL `@Name`. 

I *think* this works in the TypeSafe client. This issue is to add support for `@Name` (and for that matter also other annotations like `@DateFormat` and `@NumberFormat` and `@ToScalar`)

**Comment by jmartisk** [comment]
You mean these annotations should be taken into account when parsing objects using `io.smallrye.graphql.client.Response.getObject()` and `getList()` right? Yeah, that doesn't work right now

**Comment by phillip-kruger** [comment]
Exactly ! This would be good to do before the rebase of TypeSafe as I can imagine TypeSafe can use this ?

**Comment by jmartisk** [comment]
I haven't really played with it, but from looking at the tests, typesafe client does take these annotations into account. And that logic resides in the shared `implementation` module, so we could probably make the dynamic client use that somehow. Not sure if it will be easy, but it should be doable.

**Comment by phillip-kruger** [comment]
Using Jandex you might not even need a dependency...

**Comment by t1** [comment]
The typesafe client uses reflection. I'm not sure how this works in Quarkus, but it does.

**Comment by jmartisk** [comment]
Hm yeah that reminds me of a little problem that we're gonna face here. With the typesafe client, we know up front which classes are used for this, and so the extension can automatically register them for reflection. With the dynamic client, it's more difficult to know which classes the client will attempt to parse. 
But perhaps we could 'guess' by registering all classes where we find any of these annotations.

**Comment by phillip-kruger** [comment]
I changed the title, as Name is now fixed. We now need to look at the format annotation.
