### ISSUE TITLE
Support for multiple apps

### ISSUE THREAD

**Issue by andymc12** [smallrye/smallrye-graphql#84]
When I use this implementation, I find I can only make it work when I package the impl JARs in the same web app as the rest of the application.  If I try to package it as an OpenLiberty feature, then it fails due to (1) classloading issues and (2) lack of separation between the apps (i.e. the same types end up in the schema for multiple apps).  I haven't tried it, but I assume that the same issues might occur if the SmallRye impl JARs are in a shared library referenced by multiple applications.

**Comment by phillip-kruger** [comment]
@andymc12 - Would it be possible to add some sort of test to test this ? I am worried I am going to break this....
