### ISSUE TITLE
Unify security (and headers in general) config of typesafe and dynamic clients

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-graphql#854]
currently the dynamic client's security is configured by `CLIENT_NAME/mp-graphql/HEADER_NAME=HEADER_VALUE` (set `HEADER_NAME` to `Authorization`, for example)

while typesafe offers more fine-grained `CLIENT_NAME/mp-graphql/username` and `CLIENT_NAME/mp-graphql/password` for BASIC auth and `CLIENT_NAME/mp-graphql/bearer` if Bearer is used (and the auth type must be specified in an annotation, IIUC? which is not possible to extend to dynamic, because there are no annotations)

**Comment by phillip-kruger** [comment]
How is this done in RESTClient ?

**Comment by jmartisk** [comment]
It seems that REST client has a `ClientHeaderParam` annotation that can either contain a particular value, or refer to a system property:
```
@ClientHeaderParam(name="CustomHeader", value="value1")
@ClientHeaderParam(name="CustomHeader", value="{generateCustomHeader}")
```

but I don't see a way to add a header without annotations at all.
Also REST client doesn't seem to have a notion of different auth types, it just expects you to provide the raw Authorization header. Which I think it a good thing  - basically  there's no separate security config at all, just HTTP headers config, which makes things easier.

**Comment by phillip-kruger** [comment]
Ok, I think we should then define our own via config, but potentially add something similar to the RESTClient solution as well ?

**Comment by jmartisk** [comment]
Agreed. It will just be quite convoluted, because I suppose we want to keep the `*/mp-graphql/*` properties alongside (quite different) `quarkus.*` properties in Quarkus (and have a 1:1 mapping between them), keep support for annotations in the typesafe client, while offering the equivalent using purely config properties, and the same config properties should apply to the dynamic client too.

Add the feature of "shortcuts" where a short name can be used instead of a fully qualified class name, that makes it even juicier.

Agree that we should prefer the "raw header" approach rather than auth-type-specific security config? (We could keep the typesafe client's `@AuthorizationHeader` for backward compatibility, it will just make it even juicier). Geez.

**Comment by jmartisk** [comment]
A suggestion how to do this. 

I assume we want to have a set of Quarkus-specific properties, but keep the old `*/mp-graphql/*` properties understood by SmallRye directly, these can be used by WildFly too (and any other runtime).
For Quarkus, they will be usable too, but the `quarkus.*` properties will be preferred, because they will be integrated with the standard Quarkus mechanisms. They will be RUNTIME so that they can be overridden at boot.
This also opens up the possibility for WildFly to allow configuring clients via the WildFly management API (DMR).

To be able to unify the approach across client types and also runtimes, we will introduce a separate class, `GraphQLClientConfig`, which will act as an application-scoped bean, similar to `GraphQLConfig`, and will store all the relevant configuration in it. It will basically contain a Map of all configured clients, mapping between the name and a configuration object. The configuration object should ideally be the same for dynamic and typesafe clients. CDI producers of client instances will look into this map to find the relevant configuration before building and injecting the instance.

SmallRye GraphQL will automatically populate the contents of `GraphQLClientConfig` with stuff decoded from the `*/mp-graphql/*` properties plus annotations. It will be responsibility of the runtime to optionally enhance (override) this config. For example, Quarkus will enhance this with the configuration decoded from `quarkus.*` properties.

And now the set of properties:

|SmallRye property |Quarkus property |Meaning |
--- | --- | ---
|`CLIENT_NAME/mp-graphql/url` |`quarkus.smallrye-graphql-client.CLIENT_NAME.url` |URL to connect to|
|`CLIENT_NAME/mp-graphql/header/HEADER_NAME` |`quarkus.smallrye-graphql-client.CLIENT_NAME.header.HEADER_NAME` |HTTP header to append to all invocations|

The current `@AuthorizationHeader` annotation from the typesafe client can probably be preserved, if we want to - it will simply be translated into a relevant HTTP header entry within the `GraphQLClientConfig` object. 
I'm just not quite sure yet how exactly this will work with all the scenarios currently supported for `@AuthorizationHeader` (method-scoped, inheritance,..). We might have to end up dropping some minor stuff if we want to unify things properly.

WDYT? @phillip-kruger @t1 Did I miss something?

**Comment by t1** [comment]
Sounds good. What exactly do you mean with 'some minor stuff'? I know that there's a lot of things built into `@AuthorizationHeader`, e.g. the special handling of `*`, but we need it to access the credentials store we have in use (which we currently can't change).

**Comment by phillip-kruger** [comment]
Sounds good to me. Did we not decide on a more generic header annotation ? To be able to add any header property ?

**Comment by t1** [comment]
The generic `Header` annotation can be used also for the `Authorization` header. But if I only have a config source with the username/password in plain text, I need some logic to do the base64 etc. We had an extension mechanism in the beginning, but that was a little bit too much magic, so we replaced it with the current mechanism. Maybe we should go back to that?

**Comment by jmartisk** [comment]
I'm thinking whether this can be closed now, and I think that yes.
I performed the property unification across typesafe/dynamic, added the global `GraphQLClientConfig` object and kept the  typesafe-client-specific annotations as they were, so they can still be used.
The next step should be to scan the annotations just once at boot and append the discovered information into the global configuration object (so we don't have to use reflection to re-scan on each invocation), that will be handled through #873
