### ISSUE TITLE
Returning a SortedSet will return unsorted values

### ISSUE THREAD

**Issue by sacnoth** [smallrye/smallrye-graphql#855]
From an `@GraphQLApi` endpoint I want to return a `SortedSet` of comparable data.  
(Reason for choosing a `SortedSet` over a `List`: Wanting to prevent duplicates in the result, but still having an order in the result)

Unfortunately the originally sorted set will end up being unsorted once it's queried via GraphQL.

```Java
    @Query
    public SortedSet<@NonNull MySortableType> sortedValues() {
        return new TreeSet<>(List.of(
                new MySortableType(1, 999),
                new MySortableType(2, 666),
                new MySortableType(3, 333),
                new MySortableType(4, 999),
                new MySortableType(5, 666),
                new MySortableType(6, 333),
                new MySortableType(7, 999),
                new MySortableType(8, 666),
                new MySortableType(9, 333)
        ));
    }
```

Query:
```GraphQL
query{
  sortedValues {value}
}
```

Expected result:
```JSON
{
  "data": {
    "sortedValues": [
      {
        "value": 1
      },
      {
        "value": 2
      },
      {
        "value": 3
      },
      {
        "value": 4
      },
      {
        "value": 5
      },
      {
        "value": 6
      },
      {
        "value": 7
      },
      {
        "value": 8
      },
      {
        "value": 9
      }
    ]
  }
}
```

Actual result:
```JSON
{
  "data": {
    "sortedValues": [
      {
        "value": 1
      },
      {
        "value": 4
      },
      {
        "value": 7
      },
      {
        "value": 2
      },
      {
        "value": 5
      },
      {
        "value": 8
      },
      {
        "value": 3
      },
      {
        "value": 6
      },
      {
        "value": 9
      }
    ]
  }
}
```

As far as I can tell the culprit lies in the `io.smallrye.graphql.execution.datafetcher.CollectionCreator` where:
```Java
    private static Collection<?> newCollection(Class<?> type) {
        try {
            return (Collection<?>) type.getDeclaredConstructor().newInstance();
        } catch (Exception ex) {
            log.noArgConstructorMissing(type == null ? "null" : type.getName());
        }
        if (Set.class.isAssignableFrom(type)) {
            return new HashSet<>();
        }
        return new ArrayList<>();
    }
```
it will return a `new HashSet<>()` if no constructor was found.

As the `SortedSet` is an interface no constructor will be found.

Workaound:
```Java
    @Query
    public TreeSet<@NonNull MySortableType> sortedValues() {
```
When directly specifying a `TreeSet` as the return type the `sortedValues` query will lead to the expected result of having a sorted list of values.

I'd still expect a return type of `SortedSet` to be sorted after querying it via GraphQL though.

Reproducer (can be started with `mvn quarkus:dev`): 
[SmallRye-GraphQL-SortedSetUnsorted.zip](https://github.com/smallrye/smallrye-graphql/files/6655920/SmallRye-GraphQL-SortedSetUnsorted.zip)

**Comment by phillip-kruger** [comment]
Thanks for this. Looking at it now.

**Comment by phillip-kruger** [comment]
This still works for me. (Waiting to see of CI passes all tests) 
Only change is I had to make the private class public. See https://github.com/smallrye/smallrye-graphql/pull/945

@sacnoth - can you share more details on your environment, as this seems to be specific to your environment.

**Comment by phillip-kruger** [comment]
![image](https://user-images.githubusercontent.com/6836179/127974630-dce4c194-7b99-471a-b78e-a9aad86b3ffe.png)

**Comment by phillip-kruger** [comment]
All CI tests passes. Closing the issue, but you can reopen if you can share more info that allows us to recreate the problem

**Comment by sacnoth** [comment]
I just redownloaded my reproducer that was attached to the ticket.

The reproducer can still reproduce the issue, but is using an older version of smallrye graphql (that was up to date when creating the issue).

With the current version of smallrye graphql I can, in fact, no longer recreate the issue.

I guess it was fixed somewhere along the way. Thank you for your time :)

**Comment by phillip-kruger** [comment]
Great !! Thanks for confirming.
