### ISSUE TITLE
Add graphql variables logging (like smallrye.graphql.logPayload)

### ISSUE THREAD

**Issue by LeoKeogh** [smallrye/smallrye-graphql#868]
Hello,

When `smallrye.graphql.logPayload=true` smallrye only logs the query/mutation part of the payload.

Could it also log the variables when present?

Thanks,
Leo Keogh.

**Comment by phillip-kruger** [comment]
Good idea. Maybe we can keep then separate ? So we introduce `smallrye.graphql.logVariables` ?
w.d.y.t ?

**Comment by t1** [comment]
I'm very much in favor of keeping that separate, as the variables often contain personal data.

**Comment by LeoKeogh** [comment]
Yes, that would be good

**Comment by phillip-kruger** [comment]
@LeoKeogh are you keen to do a PR ?

**Comment by LeoKeogh** [comment]
@phillip-kruger sorry, no, I don't currently have the time

**Comment by parsharma** [comment]
@phillip-kruger could I give it a try?
Thanks,
Parul Sharma

**Comment by phillip-kruger** [comment]
Hi @parsharma please go for it ! Thanks :)

**Comment by parsharma** [comment]
Thanks, @phillip-kruger. How I can test my changes, could you please let me know?

**Comment by phillip-kruger** [comment]
This one is a bit tricky to test in a test case, as it just prints in the logfile. You can do a manual test by setting the property that will control this in the `runner` app, then start the runner and test a query in the graphql-ui.

see https://github.com/smallrye/smallrye-graphql/tree/main/server/runner

The runner deploy the whole TCK app (from MicroProfile) and the tests we add in SmallRye as an app to do manual testing.

Let me know if you need more help.
