### ISSUE TITLE
GraphQL Tracing on Quarkus doesn't work properly

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#875]
I'm not sure if this issue should be opened here or in Quarkus.

I wrote a simple Quarkus 2.0.0.Final [demo app](https://github.com/t1/graphql-jpa) that accesses a PostgreSQL db and exposes it as REST as well as GraphQL endpoints. Jaeger nicely reports all my REST requests as separate traces with one or two spans (depending on whether the requests needs to hit the db or gets the data from the 2nd level cache). But for GraphQL requests, it only reports a single trace containing all the requests as spans. The total time of this trace is the time between the start of the first query and the end of the last. This is not helpful :-)

Could be related: It also reports a warning: invalid parent span IDs=e02fdac1c62a5b3a; skipping clock skew adjustment.

**Comment by jmartisk** [comment]
I didn't write the `TracingService` so I'm not quite sure what's going on, but as far as I remember we used to have a span for each data fetcher separately. Maybe there's some issue with losing the span context over time (because we're using more asynchronous/reactive stuff than before?), so we can't properly create child spans or something...

**Comment by jmartisk** [comment]
I can look into it but need to finish some stuff on clients first, so probably not this week

**Comment by t1** [comment]
This is about MP Tracing, not the [GraphQL tracing extension](https://github.com/apollographql/apollo-tracing), right?

**Comment by jmartisk** [comment]
Right, this is MP OpenTracing with Jaeger. We don't support any other tracing for GraphQL.

**Comment by jmartisk** [comment]
Got something ready to improve the tracing (plus a lot of ideas how to improve further, but I'm not yet sure how to do that). I want to add some test coverage first, so I will probably send a PR within a few days
