### ISSUE TITLE
Optional<Set<String>> not work

### ISSUE THREAD

**Issue by pipinet** [smallrye/smallrye-graphql#876]
![image](https://user-images.githubusercontent.com/6096680/123537675-49832e00-d763-11eb-8d0b-750a1397a977.png)
![image](https://user-images.githubusercontent.com/6096680/123537692-57d14a00-d763-11eb-8f69-e4d3a2bb07a7.png)

**Comment by phillip-kruger** [comment]
Hi @pipinet . Do you have a small reproducer  ?

**Comment by pipinet** [comment]
@phillip-kruger My fault.  
The correct usage should be  Set<String> with out @Notnull
