### ISSUE TITLE
`smallrye.graphql.errorExtensionFields` doesn't work properly on Quarkus 2.0.0.Final

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#877]
I configure `quarkus.smallrye-graphql.error-extension-fields` (the Quarkus equivalent of `smallrye.graphql.errorExtensionFields`) to be `code,exception,classification,description,validationErrorType,queryPath` (no spaces!), but it only recognizes the first entry. I found out that the other values get a leading space character so the comparison doesn't work. I tried to debug it, but I just don't understand all the mechanics of Quarkus config.

**Comment by phillip-kruger** [comment]
This rings a bell... see https://github.com/quarkusio/quarkus/issues/17712
Do you have a reproducer ?

**Comment by t1** [comment]
I found this in https://github.com/t1/graphql-jpa. I use yaml there, but saw the same behavior with a plain properties file, too. Must be something else, then.

**Comment by phillip-kruger** [comment]
Thanks @t1, I'll have a look a.s.a.p

**Comment by Andro999b** [comment]
Dont know if it related. But in 2.0.0.Final smallrey-graphql stops return 401 for `io.quarkus.security.UnauthorizedException`  or any quarkus security exceptions.

**Comment by phillip-kruger** [comment]
@Andro999b that is not good. Do you have a reproducer ?

**Comment by Andro999b** [comment]
@phillip-kruger i have created an issue with sample reproducer attached https://github.com/smallrye/smallrye-graphql/issues/890

**Comment by t1** [comment]
So the status code issue is unrelated.

**Comment by phillip-kruger** [comment]
@t1 this is fix in Quarkus main. Closing here. Please reopen if quarkus 2.0.1 does not solve this for you
