### ISSUE TITLE
Quarkus 2.0.0.Final security erros does not map to correct status code

### ISSUE THREAD

**Issue by Andro999b** [smallrye/smallrye-graphql#890]
In Quarkus 2.0.0.Final security exception s like `io.quarkus.security.UnauthorizedException` or `io.quarkus.security.ForbiddenException` does not map to 401 and 403 status codes.  It works fine in 1.13.6.Final version.
Please take a look this reproducer for more details: https://drive.google.com/file/d/1iGiXcR0WeDKA2EOaMvQmtG2Yop7c2uhh/view?usp=sharing

**Comment by phillip-kruger** [comment]
Thanks ! I'll have a look.

**Comment by phillip-kruger** [comment]
Ig I take your reproducer and change the version to 1.13.6 (and .7) it still fails. I think this always worked liked this. Can you confirm ?

**Comment by phillip-kruger** [comment]
Also look at https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#status-codes

I think 200 is correct (given that the response contain the error). We can debate this again, or maybe make this configurable.

**Comment by Andro999b** [comment]
@phillip-kruger yes you are right. Behavior still same. So i am closing this
