### ISSUE TITLE
Variables failing when used for objects

### ISSUE THREAD

**Issue by andymc12** [smallrye/smallrye-graphql#90]
I have a mutation that has an argument that is an Input type - schema looks like this:
```
"Mutation root"
type Mutation {
  "Create a new widget for sale."
  createWidget(widget: WidgetInput): Widget
  quantityOnAllWidgets(newQuantity: Int!): [Widget]
}

"Query root"
type Query {
  allWidgets: [Widget]
}

"A for-sale item."
type Widget {
  name: String
  quantity: Int!
  weight: Float!
}

"A for-sale item."
input WidgetInput {
  name: String
  quantity: Int!
  weight: Float!
}
```

My client (curl) uses variables to invoke the `createWidget` mutation:
```
curl http://localhost:9080/basicMutationApp/graphql -d '{"query":"mutation createWidget ($widget: WidgetInput) { createWidget(widget: $widget) {name, weight}}","variables":{"widget":{"name":"Earbuds","quantity":20,"weight":1.2}},"operationName":"createWidget"}'
```

That fails with this message:
```
"Variable 'widget' has an invalid value : Expected type 'Map' but was 'String'. Variables for input objects must be an instance of type 'Map'."
```

I believe that this happens because the ExecutionService is converting Objects to Strings when creating the map to pass to the executionBuilder. In the toObject method, this code just returns the JsonValue's string:
```
case OBJECT:
    ret = jsonValue.toString();
    break;
```

The problem with fixing this is that it is not easy to tell at this point what type of object it is - so it is hard to deserialize it here... The rest of the query tells us that it is supposed be of type, `WidgetInput`, but that isn't available at this point. Even with that, we'd need a way to map "WidgetInput" back to the actual type (i.e. `com.mypkg.Widget`) and then deserialize it.

I'll plan to investigate this, but could probably use some help on this one.

**Comment by phillip-kruger** [comment]
Thanks @andymc12 ! As discussed, if you can get a test case going for this, that would be awesome, then I can start helping with the fix.

**Comment by andymc12** [comment]
Thanks @phillip-kruger - I think I was able to reproduce it with MP GraphQL PR https://github.com/eclipse/microprofile-graphql/pull/203 - I originally tested this before the client/server structure change (using the 1.0.x-service branch), but then created the PR for master.  If it makes it easier for you, I can back port that PR to the 1.0.x-service branch.
