### ISSUE TITLE
Change type of scalar from `DateTime` to `Time`

### ISSUE THREAD

**Issue by wpater** [smallrye/smallrye-graphql#904]
I am trying to use GitLab GraphQL API and there is [timelogs](https://docs.gitlab.com/ee/api/graphql/reference/index.html#grouptimelogs) which have argument for filtering - for example `endDate` which require [`Time` type](https://docs.gitlab.com/ee/api/graphql/reference/index.html#time).

I have prepared an interface to retrieve those timelogs:
```
@GraphQLClientApi(endpoint = "https://gitlab.com/api/graphql")
@AuthorizationHeader(confPrefix = "gitlab", type = AuthorizationHeader.Type.BEARER)
public interface GitLabGroupApi {
    Group getGroup(@NonNull @Id String fullPath,
                   @NestedParameter("timelogs") LocalDateTime startDate,
                   @NestedParameter("timelogs") LocalDateTime endDate);
}
````

Query fails on the validation because `LocalDateTime` is resolved to the `DateTime` and API expects `Time`.

Is there any option to resolve this? I cannot find anything in the docs/GitHub issues.

**Comment by phillip-kruger** [comment]
@t1 @jmartisk

**Comment by t1** [comment]
If I understand this correctly, the GitLab API defines a type `Time`, which is a scalar containing an ISO date-time, e.g. `2021-03-09T14:58:50+00:00`. The typesafe client maps the Java `LocalDateTime` type (as well as `ZonedDateTime` and `OffsetDateTime`) to a GraphQL type named `DateTime`, which the GitLab API doesn't accept.

First of all: I think this is a bug in the GitLab API. This is not a `Time`, but a `DateTime` (or maybe `Timestamp` or so).

With the `@Name` annotation, you can rename of your own types, but not build-in types. So you'll have to define a wrapper scalar. If it has a constructor method like `of` and a `toString`, it should work:

```java
@Name("Time")
public class GitLabDateTime {
    private final LocalDateTime dateTime;

    public static GitLabDateTime of(String string) {
        return new GitLabDateTime(LocalDateTime.parse(string));
    }

    public GitLabDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    @Override public String toString() {
        return dateTime.toString();
    }

    public LocalDateTime getDateTime() {
        return dateTime;
    }
}
```

Please tell me if this works for you.

**Comment by wpater** [comment]
Yes, this is working. I will create issue in GitLab. Thank you for your help.
