### ISSUE TITLE
@Subscription, onNext() has no subscribers

### ISSUE THREAD

**Issue by doublefx** [smallrye/smallrye-graphql#909]
Hi,

I was trying Quarkus 2.0.1.Final with quarkus-smallrye-graphql and the new io.smallrye.graphql.api.Subscription annotation:

```
@GraphQLApi
@Slf4j
public class HeroAPI {
	BroadcastProcessor<HeroResponse> heroProcessor = BroadcastProcessor.create();

	void onStart(@Observes StartupEvent ev) {
		emitRandomHero();
	}

	@Query("randomHero")
	@Description("Get a random Hero")
	public Uni<HeroResponse> randomHero() {
		return Hero.getRandomHero()
		           .onItem().transform(HeroResponse::from);
	}

	@Subscription("randomHeroEmitted")
	@Description("Get a random emitted Hero")
	public Multi<HeroResponse> randomHeroEmitted() {
		return heroProcessor;
	}

	private void emitRandomHero() {
		Multi.createFrom().ticks().every(ofSeconds(2))
		     .subscribe().with(subscription -> {
			     Hero.getRandomHero()
			         .subscribe().with(hero -> {
				         final var heroResponse = HeroResponse.from(hero);
				         log.info(heroResponse.toString());
				         heroProcessor.onNext(heroResponse);
			         });
		     });
	}
}
```

I'm getting:

![image](https://user-images.githubusercontent.com/1222171/125199498-5e30ed00-e25e-11eb-9343-8650fc9e1257.png)

My HeroResponse is logged but the onNext() does not have any subbcribers:

![image](https://user-images.githubusercontent.com/1222171/125199573-b10aa480-e25e-11eb-8288-4d6ef6ca2341.png)

Even though the subscriber seems to be added:

![image](https://user-images.githubusercontent.com/1222171/125199638-0c3c9700-e25f-11eb-8e88-7be5e249bf84.png)

Did I do something wrong or it is not yet ready?

**Comment by phillip-kruger** [comment]
This is ready, so should be working, can you share a reproducer ?

**Comment by doublefx** [comment]
Sure: https://github.com/doublefx/smallrye-graphql-issues-909-reproducer.git

**Comment by doublefx** [comment]
@phillip-kruger I just had the idea to make the BroadcastProcessor static and it has been working like a charm.

Maybe https://quarkus.io/guides/smallrye-graphql#subscriptions can be updated.

**Comment by t1** [comment]
Maybe it would be sufficient to make the `HeroAPI` application scoped instead of making the `BroadcastProcessor` static?

**Comment by doublefx** [comment]
:-) clearly my bad, sorry, closing...

**Comment by phillip-kruger** [comment]
Yes I think Application Scope is the way to go

**Comment by phillip-kruger** [comment]
Although, GraphQLAPI should be application scope by default, so this might be an issue
