### ISSUE TITLE
Uni and IO Thread

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#918]
At the moment Uni return execute on the Worker thread, we need to enhance this to execute on the IO Thread

**Comment by phillip-kruger** [comment]
Also see https://github.com/quarkusio/quarkus/issues/19879

When using a reactive db and a source field, you get `java.lang.IllegalStateException: HR000068: This method should exclusively be invoked from a Vert.x EventLoop thread; currently running on thread 'executor-thread-0'
`

The main query runs on the `worker-thread ` while the source method runs on the `eventloop`

**Comment by rsvoboda** [comment]
@phillip-kruger can you pls link the PR which handles Uni on IO Thread?

**Comment by phillip-kruger** [comment]
@rsvoboda ^^^

**Comment by rsvoboda** [comment]
thanks
