### ISSUE TITLE
Java interface should only be mapped to GraphQL interface if `@Interface` is annotated

### ISSUE THREAD

**Issue by beikov** [smallrye/smallrye-graphql#926]
Hi,

I tried to work further on the Blaze-Persistence integration with MP GraphQL but I hit another roadblock because I get the following error:

```
interface type 'SomeInterface' cannot implement 'SomeInterface' because that would result on a circular reference
```

That is because I have a query that returns the type 'SomeInterface' which is a Java interface. But why would SmallRye GraphQL even care what kind of class this is for the GraphQL schema? IMO a Java interface should be modeled as GraphQL object type unless it was annotated as `@Interface`.

I tried using SmallRye GraphQL 1.0.26.Final with Quarkus 1.13.7.Final

**Comment by phillip-kruger** [comment]
I think it makes more sense to map interfaces to interfaces. Have you tried adding `@Type` to your interface ?

**Comment by beikov** [comment]
I did try that, but it didn't help. I don't think the concept of Java interfaces maps perfectly onto GraphQL interfaces, that's why I would prefer explicitness, but I would be fine if annotating `@Type` would produce the expected outcome.

**Comment by phillip-kruger** [comment]
I think adding `@Type` to an interface is the way to go. But I do recall that that is still a TODO in code. I'll have a look a.s.a.p
