### ISSUE TITLE
Serializable are ignored for types

### ISSUE THREAD

**Issue by beikov** [smallrye/smallrye-graphql#927]
I have a model similar to the following:

```
public class MyClass {
  private final Serializable something;

  public String getSomething() {
    return something.toString();
  }
}
```

But when I try to start a Quarkus application with such a model, I get the following error: `type Serializable not found in schema`

When I mark the `something` field as `transient`, the field disappears completely from the type definition i.e. the getter is ignored.

**Comment by phillip-kruger** [comment]
Hi @beikov - thanks for this. We check the type in the field (first), then the method. This should be possible to check the type in the method in case the type is Serializable. I'll look at this a.s.a.p

**Comment by beikov** [comment]
It's nice that you support this now, but don't you think it might be better to just let the getter type have a precedence over the field type in case it is more concrete?

**Comment by phillip-kruger** [comment]
We could do that yes. We support public fields, so there is not always a method, hence the field first approach, but we can code around that. I'll have a look. Thanks :)
