### ISSUE TITLE
bad performance and high memory usage when returning large array of nested objects

### ISSUE THREAD

**Issue by Felk** [smallrye/smallrye-graphql#930]
I encountered a performance issue when returning a large array of nested objects as response to a GraphQL query and was wondering whether it would be considered an actual performance issue or out of scope. This is a minimal GraphQL API to reproduce the issue, using a generated project with smallrye-graphql and lombok from `code.quarkus.io`:

```java
@GraphQLApi
public class TestGraphQLAPI {
    private static final List<SomeWrapper> objects = IntStream
            .range(0, 10_000_000)
            .mapToObj(i -> new SomeWrapper("value #" + i))
            .collect(Collectors.toList());

    @Value
    public static class SomeWrapper {
        String someValue;
    }

    @Query
    public List<SomeWrapper> giveMeLargeResponse() {
        return objects;
    }
}
```

I am querying the endpoint using curl:

```bash
curl 'http://localhost:8080/graphql' --data-raw '{"query":"{giveMeLargeResponse {someValue}}","variables":null}' > /dev/null
```
If I pipe the response to a file, the file is roughly 300MB in size.

The request takes roughly 72s to return on an `Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz` (1 core fully utilized) and intermittedly takes up around 8.2GB of RAM. 

I know 10 million entries is a lot, but I expected the query to return much faster, given that it only needs to serialize and output the data. The majority of the time seems to be spent within `completeValueForList`:
![grafik](https://user-images.githubusercontent.com/1996138/127003418-2d32418c-b567-4467-93b7-0bd5dce067ae.png)

I attached the VisualVM snapshot data: [graphql-performance-10mio.zip](https://github.com/smallrye/smallrye-graphql/files/6878831/graphql-performance-10mio.zip)

**Comment by phillip-kruger** [comment]
Hi @Felk - Thanks for this. From the screenshot above it seems like this is more a graphql-java problem ? Maybe you can confirm by creating a graphql-java only reproducer ? If we can confirm it, we can log a issue at their repo.

**Comment by Felk** [comment]
Sorry for the late reply. You're probably right, I will take a look, but won't be able to get to it before the end of the week or next week.

**Comment by Felk** [comment]
This kinda went under, but I finally got around to build a graphql-java only reproducer. I'm closing this issue in favor of that one.

**Comment by phillip-kruger** [comment]
Thanks ! Please share the issue here, then we can follow

**Comment by Felk** [comment]
Here it is: https://github.com/graphql-java/graphql-java/issues/2605
It was also automatically linked already above my comment
