### ISSUE TITLE
graphql error handler support

### ISSUE THREAD

**Issue by pipinet** [smallrye/smallrye-graphql#938]
https://github.com/quarkusio/quarkus/issues/14719

**Comment by t1** [comment]
This is actually what we also need in our project: we have `@RolesAllowed` annotations on our code and want to map the resulting `EjbAccessException` to our custom `UserNotPermittedToException` (while doing some reflection magic to find the method that failed).

Our current workaround is with a CDI interceptor on the boundary class that catches the exception from thte service class and throws our own.

**Comment by t1** [comment]
This is a duplicate to #776
