### ISSUE TITLE
NPE while implementing java.io.Serializable

### ISSUE THREAD

**Issue by paschm** [smallrye/smallrye-graphql#94]
Implementing java.io.Serializable in a bean used in the GraphQL-schema leads to

```
java.lang.NullPointerException
at deployment.person-example-1.0.0-SNAPSHOT.war//io.smallrye.graphql.schema.type.OutputTypeCreator.createInterface(OutputTypeCreator.java:166)
```

Attached you find the full stacktrace and a modified graphql-example-project for reproduction. There I changed com.github.phillipkruger.user.Person, so that it implements java.io.Serializable.

Thank you very much.

[modifed_graphql-example-master.zip](https://github.com/smallrye/smallrye-graphql/files/4403530/modifed_graphql-example-master.zip)
[stacktrace.txt](https://github.com/smallrye/smallrye-graphql/files/4403531/stacktrace.txt)

**Comment by andymc12** [comment]
I think that is occurring because the runtime is trying to create a GraphQL interface to put in the schema.  I almost think we should intentionally avoid that for `java.io.Serializable` since it won't have any meaning in the GraphQL schema.

**Comment by phillip-kruger** [comment]
Yea, might have to check for more that just Serializable. We need some ignore list, maybe based on package ?

**Comment by phillip-kruger** [comment]
This should be fixed once we switch over to the Serializable model version (#93)

**Comment by phillip-kruger** [comment]
This should be fixed in master. @paschm can you confirm ?

**Comment by paschm** [comment]
Hello @phillip-kruger, thumbs up the NPE is gone. Thanks for fixing.
