### ISSUE TITLE
how can i define a graphql interface by a java object?

### ISSUE THREAD

**Issue by kulame** [smallrye/smallrye-graphql#940]
i try to define a simple graphql interface like this.

```java

interface Node {
  id: ID!
}
```

i found no solution when i try to use samllrye-gaphql .

**Comment by phillip-kruger** [comment]
A java interface will map to a graphql interface.

**Comment by kulame** [comment]
i define a java interface
```java
public interface Node {
   @NonNull @Id String id ="";
}
···

and try to implement it.
```java
@Data
public class Address implements Node{
    @NonNull @Id String id;
}
```

the exception is 
```shell
Caused by: graphql.schema.validation.InvalidSchemaException: invalid schema:
"Node" must define one or more fields.
        at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:647)
        at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:622)
        at io.smallrye.graphql.bootstrap.Bootstrap.generateGraphQLSchema(Bootstrap.java:182)
```

**Comment by phillip-kruger** [comment]
I think we are only looking for methods in an interface...

**Comment by phillip-kruger** [comment]
So try
```
public interface Node {
   @NonNull @Id 
   public String getId();
   public void setId(String id);
}
```

**Comment by kulame** [comment]
I appreciate your help.

**Comment by phillip-kruger** [comment]
No problem. Did that work for you ? If so we can close this I think ?

**Comment by kulame** [comment]
hmm  i also have a question.
the graphql code is 
'''graphql 
union Entity = Address | User | Group | ServiceAccount | App | ProductVariant | Product | ProductType | Collection | Category | ProductImage
```
i try to autogenerate code by graphql-java-codegen.
it generate a empty interface.
```java
package net.feelapp.eshop.graphql.models;


@javax.annotation.processing.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2021-08-03T00:19:03+0800"
)
public interface EntityTO {

}        
```
i try to run this code by smallrye-graphql.  it's the same problem on it.
```shell
Caused by: graphql.schema.validation.InvalidSchemaException: invalid schema:
"EntityTO" must define one or more fields.
```
how can i use a java object to write the enum?

**Comment by kulame** [comment]
has any plans to support union?

**Comment by t1** [comment]
Field on an interface, are implicitly `static`, i.e. they are just constants.

We have an completely experimental `smallrye-graphql-client-generator`, but this is about `graphql-java-codegen`, right?

IIUC, you want the `EntityTO` interface to define an `id` field. So, as Phillip said, you need to make it declare the getter and setter for `id`. I don't know how to do that with `graphql-java-codegen`. Is this an issue for us?

But IIRC in GraphQL it is possible to have an interface _without_ any fields. Maybe we should support that.

**Comment by kulame** [comment]
hi @t1 

I need a function to generate code on the server side.

it like this.
https://docs.nestjs.com/graphql/quick-start#schema-first

**Comment by t1** [comment]
There's a boundless discussion about whether code-first or schema-first is better. MP GraphQL is explicitly designed as a code-first framework, and this is what I prefer. Technology vendors have an agenda to position the schema into the core of your work, but I experienced many cases where schemas looked ideal but where cumbersome to use in actual code. And I think the domain-logic is better expressed in real code and tests than in an abstract schema. But I must admit that I also may be biased against generating API code from using SOAP for too long ;-)

See my comment on https://github.com/smallrye/smallrye-graphql/issues/944#issuecomment-891537052

**Comment by kulame** [comment]
I understand it, bu it will be hard without automatic code generation funciton if a legacy system needs to reimplement the code based on graphql.

**Comment by kulame** [comment]
and how can i implement union by smallrye-graphql?

**Comment by phillip-kruger** [comment]
@kulame - Let;s move this to Discussions: https://github.com/smallrye/smallrye-graphql/discussions

Closing here.

**Comment by t1** [comment]
Oh, and SmallRye GraphQL doesn't yet support Union types. See #400
