### ISSUE TITLE
Are smallrye plans to support schema first?

### ISSUE THREAD

**Issue by kulame** [smallrye/smallrye-graphql#944]
import a java-auto-gen tools to generate code by schema file

**Comment by t1** [comment]
I think the code-first and the schema-first approach don't have a lot in common (other than using the same underlying libs, `graphql-java` in this case). So there is hardly any benefit from unifying the libraries. If you want to go schema-first, just use one of those libs. If you want to go code-first, MP GraphQL is a good choice. I don't know why you would want to mix them.

**Comment by phillip-kruger** [comment]
No plans at the moment.
