### ISSUE TITLE
unsupportedOperationException on Quarkus startup with custom directive with params

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#962]
As reported by @nuratsree in [discussions](https://github.com/smallrye/smallrye-graphql/discussions/880#discussioncomment-1010456), starting Quarkus fails if there's a custom directive with arguments. It works fine in WildFly.

I have created a reproducer project [here](https://github.com/smallrye/smallrye-graphql/issues/962).

**Comment by t1** [comment]
@phillip-kruger: I don't understand what's happening, as the `UnsupportedOperationException` happens in the `buildExecutionService` build step of the `SmallRyeGraphQLProcessor`, but there's no `add` call in that method! Has to be something in the Quarkus Extension magic.

**Comment by phillip-kruger** [comment]
I'll have a look a.s.a.p

**Comment by jmartisk** [comment]
This has been resolved for some time, @mskacelik has now verified that it's no longer reproducible
