### ISSUE TITLE
VertxDynamicGraphQLClient

### ISSUE THREAD

**Issue by hogmuzzle** [smallrye/smallrye-graphql#976]
In RequestImpl

private JsonObject _formatJsonVariables() {
        JsonObjectBuilder varBuilder = Json.createObjectBuilder();

        variables.forEach((k, v) -> {
            // Other types to process here
            if (v instanceof String) {
                varBuilder.add(k, (String) v);
            } else if (v instanceof Integer) {
                varBuilder.add(k, (Integer) v);
            }
        });

        return varBuilder.build();
    }

Why only String and Integer why can not I keep maps in variables? JsonBuilderFactory can create nested objects as well.

**Comment by hogmuzzle** [comment]
I changed to

private JsonObject _formatJsonVariables() {
        JsonObjectBuilder varBuilder = Json.createObjectBuilder();

        variables.forEach((k, v) -> {
            // Other types to process here
            if (v instanceof String) {
                varBuilder.add(k, (String) v);
            } else if (v instanceof Integer) {
                varBuilder.add(k, (Integer) v);
            } else {
                try(Jsonb jsonb = JsonbBuilder.create()) {
                    JsonStructure str = ((JsonBinding)jsonb).toJsonStructure(v);
                    varBuilder.add(k, str);

                } catch (Exception ignore) {}
            }
        });

        return varBuilder.build();
    }

**Comment by t1** [comment]
It would be cool if you could create a PR for this! If you are not sure about how to do that, just ask.

**Comment by jmartisk** [comment]
+1 for a PR. Just a few comments:

- Maybe we should also allow the user to pass a `JsonValue` directly if they prefer? so, 
```
} else if (v instanceof JsonValue) {
   varBuilder.add(k, (JsonValue)v);
}
```

- Adding a small test into `io.smallrye.graphql.tests.client.dynamic.DynamicClientTest` would be cool too! Similar to `testQueryWithVars`, just a bit more complex)

**Comment by hogmuzzle** [comment]
How can I create a PR? I cloned the repo and made modifications to code and tests but when I try to push my changes to a new branch I get an 403 error.

**Comment by phillip-kruger** [comment]
You can make modifications in your own fork, and then open a PR from there.

**Comment by t1** [comment]
The documentation in GitHub is actually very good. Maybe [this](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork) page is what you need.

**Comment by jmartisk** [comment]
done in #996
