### ISSUE TITLE
Generated Schema for SuperHero idNumber is incorrect

### ISSUE THREAD

**Issue by tmiddlet2666** [smallrye/smallrye-graphql#99]
According to the graphql-mp spec 1.0.1 - 

On SuperHero we see.
```
@JsonbNumberFormat("ID-########")
private Long idNumber;
``

The generated graphql schema is 
```
 "0000,0000"
  idNumber: BigInteger
```

Shouldn't this be
```
 "ID-########""
  idNumber: String
```

**Comment by phillip-kruger** [comment]
Thanks @tmiddlet2666 . This is linked to https://github.com/eclipse/microprofile-graphql/issues/209. Once we fix that and add a Test, SmallRye should fail and we can fix.
