### ISSUE TITLE
Graphql with authentication

### ISSUE THREAD

**Issue by AnakinPt** [smallrye/smallrye-graphql#994]
I need to connect to a service requiring authentication.
First time I connect to it, I must use the User and password to connect and I'm fine to connect. But, in the service answer, they add a cookie, jwt, to the response that I must use in the following requests.

I would like to have a way to read these cookies from the response so I can act on this.

I create the client this way:
```
        UsernamePasswordCredentials creds = new UsernamePasswordCredentials(username, password);
        Header authenticate = new BasicScheme().authenticate(creds, new HttpPost(url), null);


        DynamicGraphQLClient dynamicGraphQLClient = DynamicGraphQLClientBuilder.newBuilder()
                .url(url)
                .header(authenticate.getName(), authenticate.getValue())
                .build();
        this.dynamicGraphQLClient = dynamicGraphQLClient;
```

and I fetch the data this way:
```
Response response = getDynamicGraphQLClient().executeSync(query);
```

I would like to do some magic, after the first request, so I could recreate the client using an additional header.

**Comment by phillip-kruger** [comment]
@jmartisk

**Comment by AnakinPt** [comment]
I used a big hammer for my tests and seems to work, but I only applied it for the code I really need.

In class VertxDynamicGraphQLClient I rewrote the private method executeSync to this:
```
    private Response executeSync(Buffer buffer) throws ExecutionException, InterruptedException {
        HttpResponse<Buffer> result = webClient.postAbs(url)
                .putHeaders(headers)
                .sendBuffer(buffer)
                .toCompletionStage()
                .toCompletableFuture()
                .get();
        MyResponseImpl response = readFrom(result.body());
        response.setHeaders(result.headers().entries());
        return response;
    }
```

And I created a new class MyResponseImpl like this:
```
@ToString
public class MyResponseImpl  extends ResponseImpl implements Response {

    @Setter
    @Getter
    private List<Map.Entry<String, String>> headers;

    public MyResponseImpl(JsonObject data, List<Error> errors) {
        super(data, errors);
    }

}

```

This was just an hack, but seems to serve my goal. I don't know if we can apply a similar solution for all methods.

**Comment by AnakinPt** [comment]
I just opened a PR with the change I propose.
